 //////////////////////////////////////////////////////////
 // This file was auto-generated by arch_client_header.zig //
 //              Do not manually modify.                 //
 //////////////////////////////////////////////////////////

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct geo_event_t {
    pub id: u128,
    pub entity_id: u128,
    pub correlation_id: u128,
    pub user_data: u128,
    pub lat_nano: i64,
    pub lon_nano: i64,
    pub group_id: u64,
    pub timestamp: u64,
    pub altitude_mm: i32,
    pub velocity_mms: u32,
    pub ttl_seconds: u32,
    pub accuracy_mm: u32,
    pub heading_cdeg: u16,
    pub flags: u16,
    pub reserved: [u8; 12],
}

pub type GEO_EVENT_FLAGS = u16;
pub const GEO_EVENT_FLAGS_GEO_EVENT_LINKED: GEO_EVENT_FLAGS = 1 << 0;
pub const GEO_EVENT_FLAGS_GEO_EVENT_IMPORTED: GEO_EVENT_FLAGS = 1 << 1;
pub const GEO_EVENT_FLAGS_GEO_EVENT_STATIONARY: GEO_EVENT_FLAGS = 1 << 2;
pub const GEO_EVENT_FLAGS_GEO_EVENT_LOW_ACCURACY: GEO_EVENT_FLAGS = 1 << 3;
pub const GEO_EVENT_FLAGS_GEO_EVENT_OFFLINE: GEO_EVENT_FLAGS = 1 << 4;
pub const GEO_EVENT_FLAGS_GEO_EVENT_DELETED: GEO_EVENT_FLAGS = 1 << 5;

pub type INSERT_GEO_EVENT_RESULT = u32;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_OK: INSERT_GEO_EVENT_RESULT = 0;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LINKED_EVENT_FAILED: INSERT_GEO_EVENT_RESULT = 1;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LINKED_EVENT_CHAIN_OPEN: INSERT_GEO_EVENT_RESULT = 2;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_TIMESTAMP_MUST_BE_ZERO: INSERT_GEO_EVENT_RESULT = 3;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_RESERVED_FIELD: INSERT_GEO_EVENT_RESULT = 4;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_RESERVED_FLAG: INSERT_GEO_EVENT_RESULT = 5;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_ID_MUST_NOT_BE_ZERO: INSERT_GEO_EVENT_RESULT = 6;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_ZERO: INSERT_GEO_EVENT_RESULT = 7;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_INVALID_COORDINATES: INSERT_GEO_EVENT_RESULT = 8;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LAT_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 9;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LON_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 10;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_ENTITY_ID: INSERT_GEO_EVENT_RESULT = 11;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_COORDINATES: INSERT_GEO_EVENT_RESULT = 12;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS: INSERT_GEO_EVENT_RESULT = 13;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_HEADING_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 14;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_TTL_INVALID: INSERT_GEO_EVENT_RESULT = 15;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_INT_MAX: INSERT_GEO_EVENT_RESULT = 16;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct insert_geo_events_result_t {
    pub index: u32,
    pub result: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct delete_entities_result_t {
    pub index: u32,
    pub result: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_uuid_filter_t {
    pub entity_id: u128,
    pub reserved: [u8; 16],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_uuid_response_t {
    pub status: u8,
    pub reserved: [u8; 15],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_radius_filter_t {
    pub center_lat_nano: i64,
    pub center_lon_nano: i64,
    pub radius_mm: u32,
    pub limit: u32,
    pub timestamp_min: u64,
    pub timestamp_max: u64,
    pub group_id: u64,
    pub reserved: [u8; 80],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_polygon_filter_t {
    pub vertex_count: u32,
    pub hole_count: u32,
    pub limit: u32,
    pub _reserved_align: u32,
    pub timestamp_min: u64,
    pub timestamp_max: u64,
    pub group_id: u64,
    pub reserved: [u8; 88],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_latest_filter_t {
    pub limit: u32,
    pub _reserved_align: u32,
    pub group_id: u64,
    pub cursor_timestamp: u64,
    pub reserved: [u8; 104],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_response_t {
    pub count: u32,
    pub has_more: u8,
    pub partial_result: u8,
    pub reserved: [u8; 10],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct polygon_vertex_t {
    pub lat_nano: i64,
    pub lon_nano: i64,
}

// Opaque struct serving as a handle for the client instance.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the client instance.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct arch_client_t {
    pub opaque: [u64; 4],
}

// Struct containing the state of a request submitted through the client.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the request.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct arch_packet_t {
    pub user_data: *mut ::std::os::raw::c_void,
    pub data: *mut ::std::os::raw::c_void,
    pub data_size: u32,
    pub user_tag: u16,
    pub operation: u8,
    pub status: u8,
    pub opaque: [u8; 64],
}

pub type ARCH_OPERATION = u8;
pub const ARCH_OPERATION_ARCH_OPERATION_PULSE: ARCH_OPERATION = 128;
pub const ARCH_OPERATION_ARCH_OPERATION_INSERT_EVENTS: ARCH_OPERATION = 146;
pub const ARCH_OPERATION_ARCH_OPERATION_UPSERT_EVENTS: ARCH_OPERATION = 147;
pub const ARCH_OPERATION_ARCH_OPERATION_DELETE_ENTITIES: ARCH_OPERATION = 148;
pub const ARCH_OPERATION_ARCH_OPERATION_QUERY_UUID: ARCH_OPERATION = 149;
pub const ARCH_OPERATION_ARCH_OPERATION_QUERY_RADIUS: ARCH_OPERATION = 150;
pub const ARCH_OPERATION_ARCH_OPERATION_QUERY_POLYGON: ARCH_OPERATION = 151;
pub const ARCH_OPERATION_ARCH_OPERATION_QUERY_LATEST: ARCH_OPERATION = 154;
pub const ARCH_OPERATION_ARCH_OPERATION_QUERY_UUID_BATCH: ARCH_OPERATION = 156;
pub const ARCH_OPERATION_ARCH_OPERATION_ARCHERDB_PING: ARCH_OPERATION = 152;
pub const ARCH_OPERATION_ARCH_OPERATION_ARCHERDB_GET_STATUS: ARCH_OPERATION = 153;
pub const ARCH_OPERATION_ARCH_OPERATION_CLEANUP_EXPIRED: ARCH_OPERATION = 155;
pub const ARCH_OPERATION_ARCH_OPERATION_GET_TOPOLOGY: ARCH_OPERATION = 157;
pub const ARCH_OPERATION_ARCH_OPERATION_TTL_SET: ARCH_OPERATION = 158;
pub const ARCH_OPERATION_ARCH_OPERATION_TTL_EXTEND: ARCH_OPERATION = 159;
pub const ARCH_OPERATION_ARCH_OPERATION_TTL_CLEAR: ARCH_OPERATION = 160;

pub type ARCH_PACKET_STATUS = u8;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_OK: ARCH_PACKET_STATUS = 0;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_TOO_MUCH_DATA: ARCH_PACKET_STATUS = 1;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_EVICTED: ARCH_PACKET_STATUS = 2;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_LOW: ARCH_PACKET_STATUS = 3;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_HIGH: ARCH_PACKET_STATUS = 4;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_SHUTDOWN: ARCH_PACKET_STATUS = 5;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_OPERATION: ARCH_PACKET_STATUS = 6;
pub const ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_DATA_SIZE: ARCH_PACKET_STATUS = 7;

pub type ARCH_INIT_STATUS = i32;
pub const ARCH_INIT_STATUS_ARCH_INIT_SUCCESS: ARCH_INIT_STATUS = 0;
pub const ARCH_INIT_STATUS_ARCH_INIT_UNEXPECTED: ARCH_INIT_STATUS = 1;
pub const ARCH_INIT_STATUS_ARCH_INIT_OUT_OF_MEMORY: ARCH_INIT_STATUS = 2;
pub const ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_INVALID: ARCH_INIT_STATUS = 3;
pub const ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_LIMIT_EXCEEDED: ARCH_INIT_STATUS = 4;
pub const ARCH_INIT_STATUS_ARCH_INIT_SYSTEM_RESOURCES: ARCH_INIT_STATUS = 5;
pub const ARCH_INIT_STATUS_ARCH_INIT_NETWORK_SUBSYSTEM: ARCH_INIT_STATUS = 6;

pub type ARCH_CLIENT_STATUS = i32;
pub const ARCH_CLIENT_STATUS_ARCH_CLIENT_OK: ARCH_CLIENT_STATUS = 0;
pub const ARCH_CLIENT_STATUS_ARCH_CLIENT_INVALID: ARCH_CLIENT_STATUS = 1;

pub type ARCH_REGISTER_LOG_CALLBACK_STATUS = i32;
pub const ARCH_REGISTER_LOG_CALLBACK_STATUS_ARCH_REGISTER_LOG_CALLBACK_SUCCESS: ARCH_REGISTER_LOG_CALLBACK_STATUS = 0;
pub const ARCH_REGISTER_LOG_CALLBACK_STATUS_ARCH_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED: ARCH_REGISTER_LOG_CALLBACK_STATUS = 1;
pub const ARCH_REGISTER_LOG_CALLBACK_STATUS_ARCH_REGISTER_LOG_CALLBACK_NOT_REGISTERED: ARCH_REGISTER_LOG_CALLBACK_STATUS = 2;

pub type ARCH_LOG_LEVEL = i32;
pub const ARCH_LOG_LEVEL_ARCH_LOG_ERR: ARCH_LOG_LEVEL = 0;
pub const ARCH_LOG_LEVEL_ARCH_LOG_WARN: ARCH_LOG_LEVEL = 1;
pub const ARCH_LOG_LEVEL_ARCH_LOG_INFO: ARCH_LOG_LEVEL = 2;
pub const ARCH_LOG_LEVEL_ARCH_LOG_DEBUG: ARCH_LOG_LEVEL = 3;

extern "C" {
    // Initialize a new ArcherDB client which connects to the addresses provided and
    // completes submitted packets by invoking the callback with the given context.
    pub fn arch_client_init(
        client_out: *mut arch_client_t,
        // 128-bit unsigned integer represented as a 16-byte little-endian array.
        cluster_id: *const [u8; 16],
        address_ptr: *const ::std::os::raw::c_char,
        address_len: u32,
        completion_ctx: usize,
        completion_callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: usize,
                arg3: *mut arch_packet_t,
                arg4: u64,
                arg5: *const u8,
                arg6: u32,
            ),
        >,
    ) -> ARCH_INIT_STATUS;

    // Initialize a new ArcherDB client which echos back any data submitted.
    pub fn arch_client_init_echo(
        client_out: *mut arch_client_t,
        // 128-bit unsigned integer represented as a 16-byte little-endian array.
        cluster_id: *const [u8; 16],
        address_ptr: *const ::std::os::raw::c_char,
        address_len: u32,
        completion_ctx: usize,
        completion_callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: usize,
                arg3: *mut arch_packet_t,
                arg4: u64,
                arg5: *const u8,
                arg6: u32,
            ),
        >,
    ) -> ARCH_INIT_STATUS;

    // Retrieve the callback context initially passed into `arch_client_init` or
    // `arch_client_init_echo`.
    pub fn arch_client_completion_context(
        client: *mut arch_client_t,
        completion_ctx_out: *mut usize,
    ) -> ARCH_CLIENT_STATUS;

    // Submit a packet with its operation, data, and data_size fields set.
    // Once completed, `on_completion` will be invoked with `on_completion_ctx` and the given
    // packet on the `arch_client` thread (separate from caller's thread).
    pub fn arch_client_submit(
        client: *mut arch_client_t,
        packet: *mut arch_packet_t,
    ) -> ARCH_CLIENT_STATUS;

    // Closes the client, causing any previously submitted packets to be completed with
    // `ARCH_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
    // It is undefined behavior to use any functions on the client once deinit is called.
    pub fn arch_client_deinit(
        client: *mut arch_client_t,
    ) -> ARCH_CLIENT_STATUS;

    // Registers or unregisters the application log callback.
    pub fn register_log_callback(
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                ARCH_LOG_LEVEL,
                *const u8,
                u32,
            ),
        >,
        debug: bool,
    ) -> ARCH_REGISTER_LOG_CALLBACK_STATUS;
}