pub use super::*;

#[rustfmt::skip]
impl From<u32> for CreateAccountResult {
    fn from(other: u32) -> CreateAccountResult {
        use tbc::*;
        use CreateAccountResult::*;

        match other {
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_OK => Ok,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LINKED_EVENT_FAILED => LinkedEventFailed,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LINKED_EVENT_CHAIN_OPEN => LinkedEventChainOpen,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_EXPECTED => ImportedEventExpected,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_NOT_EXPECTED => ImportedEventNotExpected,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_TIMESTAMP_MUST_BE_ZERO => TimestampMustBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE => ImportedEventTimestampOutOfRange,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE => ImportedEventTimestampMustNotAdvance,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_RESERVED_FIELD => ReservedField,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_RESERVED_FLAG => ReservedFlag,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_ID_MUST_NOT_BE_ZERO => IdMustNotBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_ID_MUST_NOT_BE_INT_MAX => IdMustNotBeIntMax,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_FLAGS => ExistsWithDifferentFlags,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_128 => ExistsWithDifferentUserData128,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_64 => ExistsWithDifferentUserData64,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_32 => ExistsWithDifferentUserData32,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_LEDGER => ExistsWithDifferentLedger,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_CODE => ExistsWithDifferentCode,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS => Exists,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_FLAGS_ARE_MUTUALLY_EXCLUSIVE => FlagsAreMutuallyExclusive,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_DEBITS_PENDING_MUST_BE_ZERO => DebitsPendingMustBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_DEBITS_POSTED_MUST_BE_ZERO => DebitsPostedMustBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CREDITS_PENDING_MUST_BE_ZERO => CreditsPendingMustBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CREDITS_POSTED_MUST_BE_ZERO => CreditsPostedMustBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LEDGER_MUST_NOT_BE_ZERO => LedgerMustNotBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CODE_MUST_NOT_BE_ZERO => CodeMustNotBeZero,
            ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS => ImportedEventTimestampMustNotRegress,
            v => panic!("Unknown CreateAccountResult: {v}"),
        }
    }
}

#[rustfmt::skip]
impl From<CreateAccountResult> for u32 {
    fn from(other: CreateAccountResult) -> u32 {
        use tbc::*;
        use CreateAccountResult::*;

        match other {
            Ok => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_OK,
            LinkedEventFailed => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LINKED_EVENT_FAILED,
            LinkedEventChainOpen => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LINKED_EVENT_CHAIN_OPEN,
            ImportedEventExpected => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_EXPECTED,
            ImportedEventNotExpected => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_NOT_EXPECTED,
            TimestampMustBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_TIMESTAMP_MUST_BE_ZERO,
            ImportedEventTimestampOutOfRange => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE,
            ImportedEventTimestampMustNotAdvance => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE,
            ReservedField => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_RESERVED_FIELD,
            ReservedFlag => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_RESERVED_FLAG,
            IdMustNotBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_ID_MUST_NOT_BE_ZERO,
            IdMustNotBeIntMax => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_ID_MUST_NOT_BE_INT_MAX,
            ExistsWithDifferentFlags => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_FLAGS,
            ExistsWithDifferentUserData128 => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_128,
            ExistsWithDifferentUserData64 => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_64,
            ExistsWithDifferentUserData32 => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_USER_DATA_32,
            ExistsWithDifferentLedger => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_LEDGER,
            ExistsWithDifferentCode => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS_WITH_DIFFERENT_CODE,
            Exists => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_EXISTS,
            FlagsAreMutuallyExclusive => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_FLAGS_ARE_MUTUALLY_EXCLUSIVE,
            DebitsPendingMustBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_DEBITS_PENDING_MUST_BE_ZERO,
            DebitsPostedMustBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_DEBITS_POSTED_MUST_BE_ZERO,
            CreditsPendingMustBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CREDITS_PENDING_MUST_BE_ZERO,
            CreditsPostedMustBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CREDITS_POSTED_MUST_BE_ZERO,
            LedgerMustNotBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_LEDGER_MUST_NOT_BE_ZERO,
            CodeMustNotBeZero => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_CODE_MUST_NOT_BE_ZERO,
            ImportedEventTimestampMustNotRegress => ARCH_CREATE_ACCOUNT_RESULT_ARCH_CREATE_ACCOUNT_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS,
        }
    }
}

#[rustfmt::skip]
impl From<u32> for CreateTransferResult {
    fn from(other: u32) -> CreateTransferResult {
        use tbc::*;
        use CreateTransferResult::*;

        match other {
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OK => Ok,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LINKED_EVENT_FAILED => LinkedEventFailed,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LINKED_EVENT_CHAIN_OPEN => LinkedEventChainOpen,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_EXPECTED => ImportedEventExpected,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_NOT_EXPECTED => ImportedEventNotExpected,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TIMESTAMP_MUST_BE_ZERO => TimestampMustBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE => ImportedEventTimestampOutOfRange,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE => ImportedEventTimestampMustNotAdvance,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_RESERVED_FLAG => ReservedFlag,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_MUST_NOT_BE_ZERO => IdMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_MUST_NOT_BE_INT_MAX => IdMustNotBeIntMax,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_FLAGS => ExistsWithDifferentFlags,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_PENDING_ID => ExistsWithDifferentPendingId,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_TIMEOUT => ExistsWithDifferentTimeout,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID => ExistsWithDifferentDebitAccountId,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID => ExistsWithDifferentCreditAccountId,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_AMOUNT => ExistsWithDifferentAmount,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_128 => ExistsWithDifferentUserData128,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_64 => ExistsWithDifferentUserData64,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_32 => ExistsWithDifferentUserData32,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_LEDGER => ExistsWithDifferentLedger,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_CODE => ExistsWithDifferentCode,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS => Exists,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_ALREADY_FAILED => IdAlreadyFailed,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_FLAGS_ARE_MUTUALLY_EXCLUSIVE => FlagsAreMutuallyExclusive,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO => DebitAccountIdMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX => DebitAccountIdMustNotBeIntMax,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO => CreditAccountIdMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX => CreditAccountIdMustNotBeIntMax,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ACCOUNTS_MUST_BE_DIFFERENT => AccountsMustBeDifferent,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_BE_ZERO => PendingIdMustBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_NOT_BE_ZERO => PendingIdMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_NOT_BE_INT_MAX => PendingIdMustNotBeIntMax,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_BE_DIFFERENT => PendingIdMustBeDifferent,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TIMEOUT_RESERVED_FOR_PENDING_TRANSFER => TimeoutReservedForPendingTransfer,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CLOSING_TRANSFER_MUST_BE_PENDING => ClosingTransferMustBePending,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LEDGER_MUST_NOT_BE_ZERO => LedgerMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CODE_MUST_NOT_BE_ZERO => CodeMustNotBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_NOT_FOUND => DebitAccountNotFound,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_NOT_FOUND => CreditAccountNotFound,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER => AccountsMustHaveTheSameLedger,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS => TransferMustHaveTheSameLedgerAsAccounts,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_NOT_FOUND => PendingTransferNotFound,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_NOT_PENDING => PendingTransferNotPending,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID => PendingTransferHasDifferentDebitAccountId,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID => PendingTransferHasDifferentCreditAccountId,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_LEDGER => PendingTransferHasDifferentLedger,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_CODE => PendingTransferHasDifferentCode,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_PENDING_TRANSFER_AMOUNT => ExceedsPendingTransferAmount,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT => PendingTransferHasDifferentAmount,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_ALREADY_POSTED => PendingTransferAlreadyPosted,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_ALREADY_VOIDED => PendingTransferAlreadyVoided,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_EXPIRED => PendingTransferExpired,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS => ImportedEventTimestampMustNotRegress,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT => ImportedEventTimestampMustPostdateDebitAccount,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT => ImportedEventTimestampMustPostdateCreditAccount,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO => ImportedEventTimeoutMustBeZero,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ALREADY_CLOSED => DebitAccountAlreadyClosed,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ALREADY_CLOSED => CreditAccountAlreadyClosed,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS_PENDING => OverflowsDebitsPending,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS_PENDING => OverflowsCreditsPending,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS_POSTED => OverflowsDebitsPosted,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS_POSTED => OverflowsCreditsPosted,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS => OverflowsDebits,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS => OverflowsCredits,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_TIMEOUT => OverflowsTimeout,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_CREDITS => ExceedsCredits,
            ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_DEBITS => ExceedsDebits,
            v => panic!("Unknown CreateTransferResult: {v}"),
        }
    }
}

#[rustfmt::skip]
impl From<CreateTransferResult> for u32 {
    fn from(other: CreateTransferResult) -> u32 {
        use tbc::*;
        use CreateTransferResult::*;

        match other {
            Ok => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OK,
            LinkedEventFailed => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LINKED_EVENT_FAILED,
            LinkedEventChainOpen => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LINKED_EVENT_CHAIN_OPEN,
            ImportedEventExpected => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_EXPECTED,
            ImportedEventNotExpected => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_NOT_EXPECTED,
            TimestampMustBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TIMESTAMP_MUST_BE_ZERO,
            ImportedEventTimestampOutOfRange => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE,
            ImportedEventTimestampMustNotAdvance => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE,
            ReservedFlag => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_RESERVED_FLAG,
            IdMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_MUST_NOT_BE_ZERO,
            IdMustNotBeIntMax => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_MUST_NOT_BE_INT_MAX,
            ExistsWithDifferentFlags => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_FLAGS,
            ExistsWithDifferentPendingId => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_PENDING_ID,
            ExistsWithDifferentTimeout => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_TIMEOUT,
            ExistsWithDifferentDebitAccountId => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID,
            ExistsWithDifferentCreditAccountId => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID,
            ExistsWithDifferentAmount => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_AMOUNT,
            ExistsWithDifferentUserData128 => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_128,
            ExistsWithDifferentUserData64 => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_64,
            ExistsWithDifferentUserData32 => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_USER_DATA_32,
            ExistsWithDifferentLedger => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_LEDGER,
            ExistsWithDifferentCode => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS_WITH_DIFFERENT_CODE,
            Exists => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXISTS,
            IdAlreadyFailed => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ID_ALREADY_FAILED,
            FlagsAreMutuallyExclusive => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_FLAGS_ARE_MUTUALLY_EXCLUSIVE,
            DebitAccountIdMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO,
            DebitAccountIdMustNotBeIntMax => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX,
            CreditAccountIdMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO,
            CreditAccountIdMustNotBeIntMax => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX,
            AccountsMustBeDifferent => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ACCOUNTS_MUST_BE_DIFFERENT,
            PendingIdMustBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_BE_ZERO,
            PendingIdMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_NOT_BE_ZERO,
            PendingIdMustNotBeIntMax => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_NOT_BE_INT_MAX,
            PendingIdMustBeDifferent => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_ID_MUST_BE_DIFFERENT,
            TimeoutReservedForPendingTransfer => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TIMEOUT_RESERVED_FOR_PENDING_TRANSFER,
            ClosingTransferMustBePending => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CLOSING_TRANSFER_MUST_BE_PENDING,
            LedgerMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_LEDGER_MUST_NOT_BE_ZERO,
            CodeMustNotBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CODE_MUST_NOT_BE_ZERO,
            DebitAccountNotFound => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_NOT_FOUND,
            CreditAccountNotFound => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_NOT_FOUND,
            AccountsMustHaveTheSameLedger => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER,
            TransferMustHaveTheSameLedgerAsAccounts => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS,
            PendingTransferNotFound => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_NOT_FOUND,
            PendingTransferNotPending => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_NOT_PENDING,
            PendingTransferHasDifferentDebitAccountId => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID,
            PendingTransferHasDifferentCreditAccountId => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID,
            PendingTransferHasDifferentLedger => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_LEDGER,
            PendingTransferHasDifferentCode => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_CODE,
            ExceedsPendingTransferAmount => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_PENDING_TRANSFER_AMOUNT,
            PendingTransferHasDifferentAmount => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT,
            PendingTransferAlreadyPosted => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_ALREADY_POSTED,
            PendingTransferAlreadyVoided => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_ALREADY_VOIDED,
            PendingTransferExpired => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_PENDING_TRANSFER_EXPIRED,
            ImportedEventTimestampMustNotRegress => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS,
            ImportedEventTimestampMustPostdateDebitAccount => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT,
            ImportedEventTimestampMustPostdateCreditAccount => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT,
            ImportedEventTimeoutMustBeZero => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO,
            DebitAccountAlreadyClosed => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_DEBIT_ACCOUNT_ALREADY_CLOSED,
            CreditAccountAlreadyClosed => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_CREDIT_ACCOUNT_ALREADY_CLOSED,
            OverflowsDebitsPending => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS_PENDING,
            OverflowsCreditsPending => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS_PENDING,
            OverflowsDebitsPosted => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS_POSTED,
            OverflowsCreditsPosted => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS_POSTED,
            OverflowsDebits => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_DEBITS,
            OverflowsCredits => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_CREDITS,
            OverflowsTimeout => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_OVERFLOWS_TIMEOUT,
            ExceedsCredits => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_CREDITS,
            ExceedsDebits => ARCH_CREATE_TRANSFER_RESULT_ARCH_CREATE_TRANSFER_EXCEEDS_DEBITS,
        }
    }
}

impl From<i32> for InitStatus {
    fn from(other: i32) -> InitStatus {
        use tbc::*;
        use InitStatus::*;

        match other {
            ARCH_INIT_STATUS_ARCH_INIT_SUCCESS => panic!(),
            ARCH_INIT_STATUS_ARCH_INIT_UNEXPECTED => Unexpected,
            ARCH_INIT_STATUS_ARCH_INIT_OUT_OF_MEMORY => OutOfMemory,
            ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_INVALID => AddressInvalid,
            ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_LIMIT_EXCEEDED => AddressLimitExceeded,
            ARCH_INIT_STATUS_ARCH_INIT_SYSTEM_RESOURCES => SystemResources,
            ARCH_INIT_STATUS_ARCH_INIT_NETWORK_SUBSYSTEM => NetworkSubsystem,
            v => panic!("Unknown InitStatus: {v}"),
        }
    }
}

impl From<InitStatus> for i32 {
    fn from(other: InitStatus) -> i32 {
        use tbc::*;
        use InitStatus::*;

        match other {
            Unexpected => ARCH_INIT_STATUS_ARCH_INIT_UNEXPECTED,
            OutOfMemory => ARCH_INIT_STATUS_ARCH_INIT_OUT_OF_MEMORY,
            AddressInvalid => ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_INVALID,
            AddressLimitExceeded => ARCH_INIT_STATUS_ARCH_INIT_ADDRESS_LIMIT_EXCEEDED,
            SystemResources => ARCH_INIT_STATUS_ARCH_INIT_SYSTEM_RESOURCES,
            NetworkSubsystem => ARCH_INIT_STATUS_ARCH_INIT_NETWORK_SUBSYSTEM,
        }
    }
}

impl From<u8> for PacketStatus {
    fn from(other: u8) -> PacketStatus {
        use tbc::*;
        use PacketStatus::*;

        match other {
            ARCH_PACKET_STATUS_ARCH_PACKET_OK => panic!(),
            ARCH_PACKET_STATUS_ARCH_PACKET_TOO_MUCH_DATA => TooMuchData,
            ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_EVICTED => ClientEvicted,
            ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_LOW => ClientReleaseTooLow,
            ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_HIGH => ClientReleaseTooHigh,
            ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_SHUTDOWN => ClientShutdown,
            ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_OPERATION => InvalidOperation,
            ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_DATA_SIZE => InvalidDataSize,
            v => panic!("Unknown PacketStatus: {v}"),
        }
    }
}

impl From<PacketStatus> for u8 {
    fn from(other: PacketStatus) -> u8 {
        use tbc::*;
        use PacketStatus::*;

        match other {
            TooMuchData => ARCH_PACKET_STATUS_ARCH_PACKET_TOO_MUCH_DATA,
            ClientEvicted => ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_EVICTED,
            ClientReleaseTooLow => ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_LOW,
            ClientReleaseTooHigh => ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_RELEASE_TOO_HIGH,
            ClientShutdown => ARCH_PACKET_STATUS_ARCH_PACKET_CLIENT_SHUTDOWN,
            InvalidOperation => ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_OPERATION,
            InvalidDataSize => ARCH_PACKET_STATUS_ARCH_PACKET_INVALID_DATA_SIZE,
        }
    }
}
