 //////////////////////////////////////////////////////////
 // This file was auto-generated by tb_client_header.zig //
 //              Do not manually modify.                 //
 //////////////////////////////////////////////////////////

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct geo_event_t {
    pub id: u128,
    pub entity_id: u128,
    pub correlation_id: u128,
    pub user_data: u128,
    pub lat_nano: i64,
    pub lon_nano: i64,
    pub group_id: u64,
    pub timestamp: u64,
    pub altitude_mm: i32,
    pub velocity_mms: u32,
    pub ttl_seconds: u32,
    pub accuracy_mm: u32,
    pub heading_cdeg: u16,
    pub flags: u16,
    pub reserved: [u8; 12],
}

pub type GEO_EVENT_FLAGS = u16;
pub const GEO_EVENT_FLAGS_GEO_EVENT_LINKED: GEO_EVENT_FLAGS = 1 << 0;
pub const GEO_EVENT_FLAGS_GEO_EVENT_IMPORTED: GEO_EVENT_FLAGS = 1 << 1;
pub const GEO_EVENT_FLAGS_GEO_EVENT_STATIONARY: GEO_EVENT_FLAGS = 1 << 2;
pub const GEO_EVENT_FLAGS_GEO_EVENT_LOW_ACCURACY: GEO_EVENT_FLAGS = 1 << 3;
pub const GEO_EVENT_FLAGS_GEO_EVENT_OFFLINE: GEO_EVENT_FLAGS = 1 << 4;
pub const GEO_EVENT_FLAGS_GEO_EVENT_DELETED: GEO_EVENT_FLAGS = 1 << 5;

pub type INSERT_GEO_EVENT_RESULT = u32;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_OK: INSERT_GEO_EVENT_RESULT = 0;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LINKED_EVENT_FAILED: INSERT_GEO_EVENT_RESULT = 1;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LINKED_EVENT_CHAIN_OPEN: INSERT_GEO_EVENT_RESULT = 2;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_TIMESTAMP_MUST_BE_ZERO: INSERT_GEO_EVENT_RESULT = 3;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_RESERVED_FIELD: INSERT_GEO_EVENT_RESULT = 4;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_RESERVED_FLAG: INSERT_GEO_EVENT_RESULT = 5;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_ID_MUST_NOT_BE_ZERO: INSERT_GEO_EVENT_RESULT = 6;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_ZERO: INSERT_GEO_EVENT_RESULT = 7;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_INVALID_COORDINATES: INSERT_GEO_EVENT_RESULT = 8;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LAT_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 9;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_LON_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 10;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_ENTITY_ID: INSERT_GEO_EVENT_RESULT = 11;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_COORDINATES: INSERT_GEO_EVENT_RESULT = 12;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_EXISTS: INSERT_GEO_EVENT_RESULT = 13;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_HEADING_OUT_OF_RANGE: INSERT_GEO_EVENT_RESULT = 14;
pub const INSERT_GEO_EVENT_RESULT_INSERT_GEO_EVENT_TTL_INVALID: INSERT_GEO_EVENT_RESULT = 15;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct insert_geo_events_result_t {
    pub index: u32,
    pub result: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct delete_entities_result_t {
    pub index: u32,
    pub result: u32,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_uuid_filter_t {
    pub entity_id: u128,
    pub limit: u32,
    pub reserved: [u8; 108],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_radius_filter_t {
    pub center_lat_nano: i64,
    pub center_lon_nano: i64,
    pub radius_mm: u32,
    pub limit: u32,
    pub timestamp_min: u64,
    pub timestamp_max: u64,
    pub group_id: u64,
    pub reserved: [u8; 80],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_polygon_filter_t {
    pub vertex_count: u32,
    pub limit: u32,
    pub timestamp_min: u64,
    pub timestamp_max: u64,
    pub group_id: u64,
    pub reserved: [u8; 96],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_latest_filter_t {
    pub limit: u32,
    pub _reserved_align: u32,
    pub group_id: u64,
    pub cursor_timestamp: u64,
    pub reserved: [u8; 104],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct query_response_t {
    pub count: u32,
    pub has_more: u8,
    pub partial_result: u8,
    pub reserved: [u8; 10],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct polygon_vertex_t {
    pub lat_nano: i64,
    pub lon_nano: i64,
}

// Opaque struct serving as a handle for the client instance.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the client instance.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tb_client_t {
    pub opaque: [u64; 4],
}

// Struct containing the state of a request submitted through the client.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the request.
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tb_packet_t {
    pub user_data: *mut ::std::os::raw::c_void,
    pub data: *mut ::std::os::raw::c_void,
    pub data_size: u32,
    pub user_tag: u16,
    pub operation: u8,
    pub status: u8,
    pub opaque: [u8; 64],
}

pub type TB_OPERATION = u8;
pub const TB_OPERATION_TB_OPERATION_PULSE: TB_OPERATION = 128;
pub const TB_OPERATION_TB_OPERATION_GET_CHANGE_EVENTS: TB_OPERATION = 137;
pub const TB_OPERATION_TB_OPERATION_CREATE_ACCOUNTS: TB_OPERATION = 138;
pub const TB_OPERATION_TB_OPERATION_CREATE_TRANSFERS: TB_OPERATION = 139;
pub const TB_OPERATION_TB_OPERATION_LOOKUP_ACCOUNTS: TB_OPERATION = 140;
pub const TB_OPERATION_TB_OPERATION_LOOKUP_TRANSFERS: TB_OPERATION = 141;
pub const TB_OPERATION_TB_OPERATION_GET_ACCOUNT_TRANSFERS: TB_OPERATION = 142;
pub const TB_OPERATION_TB_OPERATION_GET_ACCOUNT_BALANCES: TB_OPERATION = 143;
pub const TB_OPERATION_TB_OPERATION_QUERY_ACCOUNTS: TB_OPERATION = 144;
pub const TB_OPERATION_TB_OPERATION_QUERY_TRANSFERS: TB_OPERATION = 145;
pub const TB_OPERATION_TB_OPERATION_INSERT_EVENTS: TB_OPERATION = 146;
pub const TB_OPERATION_TB_OPERATION_UPSERT_EVENTS: TB_OPERATION = 147;
pub const TB_OPERATION_TB_OPERATION_DELETE_ENTITIES: TB_OPERATION = 148;
pub const TB_OPERATION_TB_OPERATION_QUERY_UUID: TB_OPERATION = 149;
pub const TB_OPERATION_TB_OPERATION_QUERY_RADIUS: TB_OPERATION = 150;
pub const TB_OPERATION_TB_OPERATION_QUERY_POLYGON: TB_OPERATION = 151;
pub const TB_OPERATION_TB_OPERATION_QUERY_LATEST: TB_OPERATION = 154;
pub const TB_OPERATION_TB_OPERATION_ARCHERDB_PING: TB_OPERATION = 152;
pub const TB_OPERATION_TB_OPERATION_ARCHERDB_GET_STATUS: TB_OPERATION = 153;
pub const TB_OPERATION_TB_OPERATION_CLEANUP_EXPIRED: TB_OPERATION = 155;

pub type TB_PACKET_STATUS = u8;
pub const TB_PACKET_STATUS_TB_PACKET_OK: TB_PACKET_STATUS = 0;
pub const TB_PACKET_STATUS_TB_PACKET_TOO_MUCH_DATA: TB_PACKET_STATUS = 1;
pub const TB_PACKET_STATUS_TB_PACKET_CLIENT_EVICTED: TB_PACKET_STATUS = 2;
pub const TB_PACKET_STATUS_TB_PACKET_CLIENT_RELEASE_TOO_LOW: TB_PACKET_STATUS = 3;
pub const TB_PACKET_STATUS_TB_PACKET_CLIENT_RELEASE_TOO_HIGH: TB_PACKET_STATUS = 4;
pub const TB_PACKET_STATUS_TB_PACKET_CLIENT_SHUTDOWN: TB_PACKET_STATUS = 5;
pub const TB_PACKET_STATUS_TB_PACKET_INVALID_OPERATION: TB_PACKET_STATUS = 6;
pub const TB_PACKET_STATUS_TB_PACKET_INVALID_DATA_SIZE: TB_PACKET_STATUS = 7;

pub type TB_INIT_STATUS = i32;
pub const TB_INIT_STATUS_TB_INIT_SUCCESS: TB_INIT_STATUS = 0;
pub const TB_INIT_STATUS_TB_INIT_UNEXPECTED: TB_INIT_STATUS = 1;
pub const TB_INIT_STATUS_TB_INIT_OUT_OF_MEMORY: TB_INIT_STATUS = 2;
pub const TB_INIT_STATUS_TB_INIT_ADDRESS_INVALID: TB_INIT_STATUS = 3;
pub const TB_INIT_STATUS_TB_INIT_ADDRESS_LIMIT_EXCEEDED: TB_INIT_STATUS = 4;
pub const TB_INIT_STATUS_TB_INIT_SYSTEM_RESOURCES: TB_INIT_STATUS = 5;
pub const TB_INIT_STATUS_TB_INIT_NETWORK_SUBSYSTEM: TB_INIT_STATUS = 6;

pub type TB_CLIENT_STATUS = i32;
pub const TB_CLIENT_STATUS_TB_CLIENT_OK: TB_CLIENT_STATUS = 0;
pub const TB_CLIENT_STATUS_TB_CLIENT_INVALID: TB_CLIENT_STATUS = 1;

pub type TB_REGISTER_LOG_CALLBACK_STATUS = i32;
pub const TB_REGISTER_LOG_CALLBACK_STATUS_TB_REGISTER_LOG_CALLBACK_SUCCESS: TB_REGISTER_LOG_CALLBACK_STATUS = 0;
pub const TB_REGISTER_LOG_CALLBACK_STATUS_TB_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED: TB_REGISTER_LOG_CALLBACK_STATUS = 1;
pub const TB_REGISTER_LOG_CALLBACK_STATUS_TB_REGISTER_LOG_CALLBACK_NOT_REGISTERED: TB_REGISTER_LOG_CALLBACK_STATUS = 2;

pub type TB_LOG_LEVEL = i32;
pub const TB_LOG_LEVEL_TB_LOG_ERR: TB_LOG_LEVEL = 0;
pub const TB_LOG_LEVEL_TB_LOG_WARN: TB_LOG_LEVEL = 1;
pub const TB_LOG_LEVEL_TB_LOG_INFO: TB_LOG_LEVEL = 2;
pub const TB_LOG_LEVEL_TB_LOG_DEBUG: TB_LOG_LEVEL = 3;

extern "C" {
    // Initialize a new TigerBeetle client which connects to the addresses provided and
    // completes submitted packets by invoking the callback with the given context.
    pub fn tb_client_init(
        client_out: *mut tb_client_t,
        // 128-bit unsigned integer represented as a 16-byte little-endian array.
        cluster_id: *const [u8; 16],
        address_ptr: *const ::std::os::raw::c_char,
        address_len: u32,
        completion_ctx: usize,
        completion_callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: usize,
                arg3: *mut tb_packet_t,
                arg4: u64,
                arg5: *const u8,
                arg6: u32,
            ),
        >,
    ) -> TB_INIT_STATUS;

    // Initialize a new TigerBeetle client which echos back any data submitted.
    pub fn tb_client_init_echo(
        client_out: *mut tb_client_t,
        // 128-bit unsigned integer represented as a 16-byte little-endian array.
        cluster_id: *const [u8; 16],
        address_ptr: *const ::std::os::raw::c_char,
        address_len: u32,
        completion_ctx: usize,
        completion_callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: usize,
                arg3: *mut tb_packet_t,
                arg4: u64,
                arg5: *const u8,
                arg6: u32,
            ),
        >,
    ) -> TB_INIT_STATUS;

    // Retrieve the callback context initially passed into `tb_client_init` or
    // `tb_client_init_echo`.
    pub fn tb_client_completion_context(
        client: *mut tb_client_t,
        completion_ctx_out: *mut usize,
    ) -> TB_CLIENT_STATUS;

    // Submit a packet with its operation, data, and data_size fields set.
    // Once completed, `on_completion` will be invoked with `on_completion_ctx` and the given
    // packet on the `tb_client` thread (separate from caller's thread).
    pub fn tb_client_submit(
        client: *mut tb_client_t,
        packet: *mut tb_packet_t,
    ) -> TB_CLIENT_STATUS;

    // Closes the client, causing any previously submitted packets to be completed with
    // `TB_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
    // It is undefined behavior to use any functions on the client once deinit is called.
    pub fn tb_client_deinit(
        client: *mut tb_client_t,
    ) -> TB_CLIENT_STATUS;

    // Registers or unregisters the application log callback.
    pub fn register_log_callback(
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                TB_LOG_LEVEL,
                *const u8,
                u32,
            ),
        >,
        debug: bool,
    ) -> TB_REGISTER_LOG_CALLBACK_STATUS;
}