// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//! All language clients are sufficiently similar, and, for that reason, we generate the
//! corresponding READMEs by splicing language-specific code snippets into a language agnostic
//! template. This file handles the generation process.
//!
//! Code generation is written as a test that checks that generated READMEs are fresh. If they are
//! not, the file on disk is updated, and the overall test fails.

const std = @import("std");
const assert = std.debug.assert;
const log = std.log;

const stdx = @import("stdx");
const MiB = stdx.MiB;
const Shell = @import("../shell.zig");
const Docs = @import("../clients/docs_types.zig").Docs;
const Sample = @import("../clients/docs_types.zig").Sample;
const samples = @import("../clients/docs_samples.zig").samples;

const Language = @import("./ci.zig").Language;

const LanguageDocs = .{
    .go = @import("../clients/go/docs.zig").GoDocs,
    .rust = @import("../clients/rust/docs.zig").RustDocs,
    .node = @import("../clients/node/docs.zig").NodeDocs,
    .java = @import("../clients/java/docs.zig").JavaDocs,
    .dotnet = @import("../clients/dotnet/docs.zig").DotnetDocs,
    .python = @import("../clients/python/docs.zig").PythonDocs,
};

pub fn test_freshness(
    shell: *Shell,
    gpa: std.mem.Allocator,
    language: Language,
) !void {
    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();

    const docs = switch (language) {
        inline else => |l| @field(LanguageDocs, @tagName(l)),
    };

    const walkthrough_path = try shell.fmt(
        "./samples/walkthrough/{s}{s}.{s}",
        .{ docs.test_source_path, docs.test_file_name, docs.extension },
    );
    const walkthrough = try shell.cwd.readFileAlloc(
        arena.allocator(),
        walkthrough_path,
        1 * MiB,
    );

    var ctx = Context{
        .shell = shell,
        .arena = arena.allocator(),
        .buffer = std.ArrayList(u8).init(arena.allocator()),
        .docs = docs,
        .walkthrough = walkthrough,
    };

    var updated_any = false;

    { // Root README.md.
        ctx.buffer.clearRetainingCapacity();
        try readme_root(&ctx);

        const update = try shell.file_ensure_content("README.md", ctx.buffer.items, .{});
        updated_any = updated_any or (update == .updated);
    }

    for (samples) |sample| { // Per-sample README.md

        ctx.buffer.clearRetainingCapacity();
        try readme_sample(&ctx, sample);

        const sample_readme = try shell.fmt("samples/{s}/README.md", .{sample.directory});
        const update = try shell.file_ensure_content(sample_readme, ctx.buffer.items, .{});
        updated_any = updated_any or (update == .updated);
    }

    if (updated_any) return error.DocsUpdated;
}

// Can't use `@src().file` here as it uses forward slashes on Windows.
const this_file = "/src/scripts/client_readmes.zig";

fn readme_root(ctx: *Context) !void {
    assert(ctx.buffer.items.len == 0);

    ctx.print(
        \\<!-- This file is generated by [{s}]({s}). -->
        \\
    , .{ this_file, this_file });

    ctx.header(1, ctx.docs.name);
    ctx.paragraph(ctx.docs.description);

    {
        ctx.header(2, "Prerequisites");
        ctx.print(
            \\Linux >= 5.6 is the only production environment we
            \\support. But for ease of development we also support macOS and Windows.
            \\
        , .{});
        ctx.paragraph(ctx.docs.prerequisites);
    }

    {
        ctx.header(2, "Setup");
        ctx.paragraph("First, create a directory for your project and `cd` into the directory.");

        if (ctx.docs.project_file.len > 0) {
            ctx.print(
                "Then create `{s}` and copy this into it:\n\n",
                .{ctx.docs.project_file_name},
            );
            _, const project_file_language = stdx.cut(ctx.docs.project_file_name, ".").?;
            ctx.code(project_file_language, ctx.docs.project_file);
        }

        if (ctx.docs.install_commands.len > 0) {
            ctx.paragraph("Then, install the ArcherDB client:");
            ctx.commands(ctx.docs.install_commands);
        }

        ctx.print("Now, create `{s}{s}.{s}` and copy this into it:\n\n", .{
            ctx.docs.test_source_path,
            ctx.docs.test_file_name,
            ctx.docs.extension,
        });
        ctx.code_section("imports");
        ctx.paragraph("Finally, build and run:");
        ctx.commands(ctx.docs.run_commands);

        ctx.paragraph(
            \\Now that all prerequisites and dependencies are correctly set
            \\up, let's dig into using ArcherDB.
            ,
        );
    }

    {
        ctx.header(2, "Sample projects");
        ctx.paragraph(
            \\This document is primarily a reference guide to
            \\the client. Below are various sample projects demonstrating
            \\features of ArcherDB.
            ,
        );
        // Absolute paths here are necessary for resolving within the docs site.
        for (samples) |sample| {
            if (try ctx.sample_exists(sample)) {
                ctx.print("* [{s}](/src/clients/{s}/samples/{s}/): {s}\n", .{
                    sample.proper_name,
                    ctx.docs.directory,
                    sample.directory,
                    sample.short_description,
                });
            }
        }

        if (ctx.docs.examples.len != 0) {
            ctx.paragraph(ctx.docs.examples);
        }
    }

    {
        ctx.header(2, "Creating a Client");
        ctx.paragraph(
            \\A client is created with a cluster ID and replica
            \\addresses for all replicas in the cluster. The cluster
            \\ID and replica addresses are both chosen by the system that
            \\starts the ArcherDB cluster.
            \\
            \\Clients are thread-safe and a single instance should be shared
            \\between multiple concurrent tasks. This allows events to be 
            \\[automatically batched](https://docs.archerdb.com/coding/requests/#batching-events).
            \\
            \\Multiple clients are useful when connecting to more than
            \\one ArcherDB cluster.
            \\
            \\In this example the cluster ID is `0` and there is one
            \\replica. The address is read from the `ARCHERDB_ADDRESS`
            \\environment variable and defaults to port `3000`.
        );
        ctx.paragraph(ctx.docs.client_object_documentation);

        ctx.paragraph(
            \\The following are valid addresses:
            \\* `3000` (interpreted as `127.0.0.1:3000`)
            \\* `127.0.0.1:3000` (interpreted as `127.0.0.1:3000`)
            \\* `127.0.0.1` (interpreted as `127.0.0.1:3001`, `3001` is the default port)
        );
    }

    {
        ctx.header(2, "Insert Events");
        ctx.paragraph(ctx.docs.insert_events_documentation);
        ctx.paragraph(ctx.docs.insert_events_errors_documentation);
    }

    {
        ctx.header(2, "GeoEvent Flags");
        ctx.paragraph(ctx.docs.geo_event_flags_documentation);
    }

    {
        ctx.header(2, "Query Operations");
        ctx.paragraph(ctx.docs.query_operations_documentation);
    }

    {
        ctx.header(2, "Delete Entities");
        ctx.paragraph(ctx.docs.delete_entities_documentation);
    }

    ctx.ensure_final_newline();
}

fn readme_sample(ctx: *Context, sample: Sample) !void {
    ctx.print(
        \\<!-- This file is generated by [{s}]({s}). -->
        \\
    , .{ this_file, this_file });

    ctx.print(
        \\# {s} {s} Sample
        \\
        \\Code for this sample is in [./{s}{s}.{s}](./{s}{s}.{s}).
        \\
        \\
    , .{
        sample.proper_name,
        ctx.docs.proper_name,
        ctx.docs.test_source_path,
        ctx.docs.test_file_name,
        ctx.docs.extension,
        ctx.docs.test_source_path,
        ctx.docs.test_file_name,
        ctx.docs.extension,
    });

    {
        ctx.header(2, "Prerequisites");
        ctx.print(
            \\Linux >= 5.6 is the only production environment we
            \\support. But for ease of development we also support macOS and Windows.
            \\
        , .{});
        ctx.paragraph(ctx.docs.prerequisites);
    }

    {
        ctx.header(2, "Setup");
        ctx.paragraph(try ctx.shell.fmt(
            \\First, clone this repo and `cd` into `archerdb/src/clients/{s}/samples/{s}`.
        , .{ ctx.docs.directory, sample.directory }));

        ctx.paragraph("Then, install the ArcherDB client:");
        ctx.commands(ctx.docs.install_commands);
    }

    {
        ctx.header(2, "Start the ArcherDB server");
        ctx.paragraph(
            \\Follow steps in the repo README to [run
            \\ArcherDB](/README.md#running-archerdb).
            \\
            \\If you are not running on port `localhost:3000`, set
            \\the environment variable `ARCHERDB_ADDRESS` to the full
            \\address of the ArcherDB server you started.
        );
    }

    {
        ctx.header(2, "Run this sample");
        ctx.paragraph("Now you can run this sample:");
        ctx.commands(ctx.docs.run_commands);
    }

    {
        ctx.header(2, "Walkthrough");
        ctx.paragraph("Here's what this project does.");
        ctx.paragraph(sample.long_description);
    }

    ctx.ensure_final_newline();
}

const Context = struct {
    shell: *Shell,
    arena: std.mem.Allocator,
    buffer: std.ArrayList(u8),
    docs: Docs,
    walkthrough: []const u8,

    fn sample_exists(ctx: *Context, sample: @TypeOf(samples[0])) !bool {
        const sample_directory = try ctx.shell.fmt("samples/{s}/", .{sample.directory});
        return try ctx.shell.dir_exists(sample_directory);
    }

    // Pulls a single "section" of code out of the entire walkthrough sample.
    //
    // A section is delimited by a pair of `section:SECTION_NAME` and `endsection:SECTION_NAME`
    // comments. If there are several such pairs, their contents is concatenated (see the `imports`
    // section in the Java sample for a motivational example for concatenation behavior).
    fn read_section(ctx: *Context, section_name: []const u8) []const u8 {
        var section_content = std.ArrayList(u8).init(ctx.arena);
        const section_start =
            ctx.shell.fmt("section:{s}\n", .{section_name}) catch @panic("OOM");
        const section_end =
            ctx.shell.fmt("endsection:{s}\n", .{section_name}) catch @panic("OOM");

        var rest = ctx.walkthrough;
        for (0..10) |_| {
            _, rest = stdx.cut(rest, section_start) orelse break;

            var section, rest = stdx.cut(rest, section_end).?;
            const newline_index = std.mem.lastIndexOfScalar(u8, section, '\n') orelse {
                log.warn("empty section fragment: {s}", .{section_name});
                @panic("empty section fragement");
            };
            section = section[0..newline_index];

            var indent_min: usize = std.math.maxInt(usize);
            var lines = std.mem.splitScalar(u8, section, '\n');
            while (lines.next()) |line| {
                if (line.len == 0) continue;
                var indent_line: usize = 0;
                while (line[indent_line] == ' ' or line[indent_line] == '\t') indent_line += 1;
                indent_min = @min(indent_min, indent_line);
            }
            assert(indent_min < 18);

            lines = std.mem.splitScalar(u8, section, '\n');
            while (lines.next()) |line| {
                if (line.len > 0) {
                    assert(line.len > indent_min);
                    section_content.appendSlice(line[indent_min..]) catch unreachable;
                }
                section_content.append('\n') catch unreachable;
            }
        } else @panic("too many parts in a section");
        assert(section_content.pop() == '\n');

        const result = section_content.items;
        assert(result.len > 0);
        return result;
    }

    fn header(ctx: *Context, comptime level: u8, content: []const u8) void {
        ctx.print(("#" ** level) ++ " {s}\n\n", .{content});
    }

    fn paragraph(ctx: *Context, content: []const u8) void {
        // Don't print empty lines.
        if (content.len == 0) return;
        ctx.print("{s}\n\n", .{content});
    }

    fn code(ctx: *Context, language: []const u8, content: []const u8) void {
        // Don't print empty lines.
        if (content.len == 0) return;
        ctx.print("```{s}\n{s}\n```\n\n", .{ language, content });
    }

    fn code_section(ctx: *Context, section_name: []const u8) void {
        const section_content = ctx.read_section(section_name);
        ctx.code(ctx.docs.markdown_name, section_content);
    }

    fn commands(ctx: *Context, content: []const u8) void {
        ctx.code("console", content);
    }

    fn print(ctx: *Context, comptime fmt: []const u8, args: anytype) void {
        ctx.buffer.writer().print(fmt, args) catch @panic("OOM");
    }

    fn ensure_final_newline(ctx: *Context) void {
        assert(ctx.buffer.pop() == '\n');
        assert(std.mem.endsWith(u8, ctx.buffer.items, "\n"));
        assert(!std.mem.endsWith(u8, ctx.buffer.items, "\n\n"));
    }
};
