// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

public enum DeleteEntityResult {
    Ok((int) 0),
    LinkedEventFailed((int) 1),
    EntityIdMustNotBeZero((int) 2),
    EntityNotFound((int) 3),
    EntityIdMustNotBeIntMax((int) 4),
    StorageSpaceExhausted((int) 5);

    public final int value;

    DeleteEntityResult(int value) {
        this.value = value;
    }

    public static DeleteEntityResult fromValue(int value) {
        switch (value) {
            case 0:
                return Ok;
            case 1:
                return LinkedEventFailed;
            case 2:
                return EntityIdMustNotBeZero;
            case 3:
                return EntityNotFound;
            case 4:
                return EntityIdMustNotBeIntMax;
            case 5:
                return StorageSpaceExhausted;
            default:
                throw new IllegalArgumentException(
                        String.format("Invalid DeleteEntityResult value=%d", value));
        }
    }
}

