//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

public interface GeoEventFlags {
    int NONE = (int) 0;

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagslinked">linked</a>
     */
    int LINKED = (int) (1 << 0);

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagsimported">imported</a>
     */
    int IMPORTED = (int) (1 << 1);

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagsstationary">stationary</a>
     */
    int STATIONARY = (int) (1 << 2);

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagslow_accuracy">low_accuracy</a>
     */
    int LOW_ACCURACY = (int) (1 << 3);

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagsoffline">offline</a>
     */
    int OFFLINE = (int) (1 << 4);

    /**
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flagsdeleted">deleted</a>
     */
    int DELETED = (int) (1 << 5);

    static boolean hasLinked(final int flags) {
        return (flags & LINKED) == LINKED;
    }

    static boolean hasImported(final int flags) {
        return (flags & IMPORTED) == IMPORTED;
    }

    static boolean hasStationary(final int flags) {
        return (flags & STATIONARY) == STATIONARY;
    }

    static boolean hasLowAccuracy(final int flags) {
        return (flags & LOW_ACCURACY) == LOW_ACCURACY;
    }

    static boolean hasOffline(final int flags) {
        return (flags & OFFLINE) == OFFLINE;
    }

    static boolean hasDeleted(final int flags) {
        return (flags & DELETED) == DELETED;
    }

}
