// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class GeoEventBatch extends Batch {


    interface Struct {
        int SIZE = 128;

        int Id = 0;
        int EntityId = 16;
        int CorrelationId = 32;
        int UserData = 48;
        int LatNano = 64;
        int LonNano = 72;
        int GroupId = 80;
        int Timestamp = 88;
        int AltitudeMm = 96;
        int VelocityMms = 100;
        int TtlSeconds = 104;
        int AccuracyMm = 108;
        int HeadingCdeg = 112;
        int Flags = 114;
        int Reserved = 116;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public GeoEventBatch(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    GeoEventBatch(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#id">id</a>
     */
    public byte[] getId() {
        return getUInt128(at(Struct.Id));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#id">id</a>
     */
    public long getId(final UInt128 part) {
        return getUInt128(at(Struct.Id), part);
    }

    /**
     * @param id an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code id} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#id">id</a>
     */
    public void setId(final byte[] id) {
        putUInt128(at(Struct.Id), id);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#id">id</a>
     */
    public void setId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.Id), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#id">id</a>
     */
    public void setId(final long leastSignificant) {
        putUInt128(at(Struct.Id), leastSignificant, 0);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#entity_id">entity_id</a>
     */
    public byte[] getEntityId() {
        return getUInt128(at(Struct.EntityId));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#entity_id">entity_id</a>
     */
    public long getEntityId(final UInt128 part) {
        return getUInt128(at(Struct.EntityId), part);
    }

    /**
     * @param entityId an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code entityId} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#entity_id">entity_id</a>
     */
    public void setEntityId(final byte[] entityId) {
        putUInt128(at(Struct.EntityId), entityId);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#entity_id">entity_id</a>
     */
    public void setEntityId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#entity_id">entity_id</a>
     */
    public void setEntityId(final long leastSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, 0);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#correlation_id">correlation_id</a>
     */
    public byte[] getCorrelationId() {
        return getUInt128(at(Struct.CorrelationId));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#correlation_id">correlation_id</a>
     */
    public long getCorrelationId(final UInt128 part) {
        return getUInt128(at(Struct.CorrelationId), part);
    }

    /**
     * @param correlationId an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code correlationId} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#correlation_id">correlation_id</a>
     */
    public void setCorrelationId(final byte[] correlationId) {
        putUInt128(at(Struct.CorrelationId), correlationId);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#correlation_id">correlation_id</a>
     */
    public void setCorrelationId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.CorrelationId), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#correlation_id">correlation_id</a>
     */
    public void setCorrelationId(final long leastSignificant) {
        putUInt128(at(Struct.CorrelationId), leastSignificant, 0);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#user_data">user_data</a>
     */
    public byte[] getUserData() {
        return getUInt128(at(Struct.UserData));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#user_data">user_data</a>
     */
    public long getUserData(final UInt128 part) {
        return getUInt128(at(Struct.UserData), part);
    }

    /**
     * @param userData an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code userData} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#user_data">user_data</a>
     */
    public void setUserData(final byte[] userData) {
        putUInt128(at(Struct.UserData), userData);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#user_data">user_data</a>
     */
    public void setUserData(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.UserData), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#user_data">user_data</a>
     */
    public void setUserData(final long leastSignificant) {
        putUInt128(at(Struct.UserData), leastSignificant, 0);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#lat_nano">lat_nano</a>
     */
    public long getLatNano() {
        final var value = getUInt64(at(Struct.LatNano));
        return value;
    }

    /**
     * @param latNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#lat_nano">lat_nano</a>
     */
    public void setLatNano(final long latNano) {
        putUInt64(at(Struct.LatNano), latNano);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#lon_nano">lon_nano</a>
     */
    public long getLonNano() {
        final var value = getUInt64(at(Struct.LonNano));
        return value;
    }

    /**
     * @param lonNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#lon_nano">lon_nano</a>
     */
    public void setLonNano(final long lonNano) {
        putUInt64(at(Struct.LonNano), lonNano);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#group_id">group_id</a>
     */
    public long getGroupId() {
        final var value = getUInt64(at(Struct.GroupId));
        return value;
    }

    /**
     * @param groupId
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#group_id">group_id</a>
     */
    public void setGroupId(final long groupId) {
        putUInt64(at(Struct.GroupId), groupId);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#timestamp">timestamp</a>
     */
    public long getTimestamp() {
        final var value = getUInt64(at(Struct.Timestamp));
        return value;
    }

    /**
     * @param timestamp
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#timestamp">timestamp</a>
     */
    public void setTimestamp(final long timestamp) {
        putUInt64(at(Struct.Timestamp), timestamp);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#altitude_mm">altitude_mm</a>
     */
    public int getAltitudeMm() {
        final var value = getUInt32(at(Struct.AltitudeMm));
        return value;
    }

    /**
     * @param altitudeMm
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#altitude_mm">altitude_mm</a>
     */
    public void setAltitudeMm(final int altitudeMm) {
        putUInt32(at(Struct.AltitudeMm), altitudeMm);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#velocity_mms">velocity_mms</a>
     */
    public int getVelocityMms() {
        final var value = getUInt32(at(Struct.VelocityMms));
        return value;
    }

    /**
     * @param velocityMms
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#velocity_mms">velocity_mms</a>
     */
    public void setVelocityMms(final int velocityMms) {
        putUInt32(at(Struct.VelocityMms), velocityMms);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#ttl_seconds">ttl_seconds</a>
     */
    public int getTtlSeconds() {
        final var value = getUInt32(at(Struct.TtlSeconds));
        return value;
    }

    /**
     * @param ttlSeconds
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#ttl_seconds">ttl_seconds</a>
     */
    public void setTtlSeconds(final int ttlSeconds) {
        putUInt32(at(Struct.TtlSeconds), ttlSeconds);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#accuracy_mm">accuracy_mm</a>
     */
    public int getAccuracyMm() {
        final var value = getUInt32(at(Struct.AccuracyMm));
        return value;
    }

    /**
     * @param accuracyMm
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#accuracy_mm">accuracy_mm</a>
     */
    public void setAccuracyMm(final int accuracyMm) {
        putUInt32(at(Struct.AccuracyMm), accuracyMm);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#heading_cdeg">heading_cdeg</a>
     */
    public int getHeadingCdeg() {
        final var value = getUInt16(at(Struct.HeadingCdeg));
        return value;
    }

    /**
     * @param headingCdeg
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#heading_cdeg">heading_cdeg</a>
     */
    public void setHeadingCdeg(final int headingCdeg) {
        putUInt16(at(Struct.HeadingCdeg), headingCdeg);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flags">flags</a>
     */
    public int getFlags() {
        final var value = getUInt16(at(Struct.Flags));
        return value;
    }

    /**
     * @param flags
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#flags">flags</a>
     */
    public void setFlags(final int flags) {
        putUInt16(at(Struct.Flags), flags);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#reserved">reserved</a>
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 12);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/geo-event#reserved">reserved</a>
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[12];
        if (reserved.length != 12)
            throw new IllegalArgumentException("Reserved must be 12 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

