//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class HoleDescriptor extends Batch {


    interface Struct {
        int SIZE = 8;

        int VertexCount = 0;
        int Reserved = 4;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public HoleDescriptor(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    HoleDescriptor(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getVertexCount() {
        final var value = getUInt32(at(Struct.VertexCount));
        return value;
    }

    /**
     * @param vertexCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setVertexCount(final int vertexCount) {
        putUInt32(at(Struct.VertexCount), vertexCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    int getReserved() {
        final var value = getUInt32(at(Struct.Reserved));
        return value;
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setReserved(final int reserved) {
        putUInt32(at(Struct.Reserved), reserved);
    }

}

