// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class PingRequest extends Batch {


    interface Struct {
        int SIZE = 8;

        int PingData = 0;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public PingRequest(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    PingRequest(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getPingData() {
        final var value = getUInt64(at(Struct.PingData));
        return value;
    }

    /**
     * @param pingData
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setPingData(final long pingData) {
        putUInt64(at(Struct.PingData), pingData);
    }

}

