//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class PolygonVertex extends Batch {


    interface Struct {
        int SIZE = 16;

        int LatNano = 0;
        int LonNano = 8;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public PolygonVertex(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    PolygonVertex(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getLatNano() {
        final var value = getUInt64(at(Struct.LatNano));
        return value;
    }

    /**
     * @param latNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setLatNano(final long latNano) {
        putUInt64(at(Struct.LatNano), latNano);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getLonNano() {
        final var value = getUInt64(at(Struct.LonNano));
        return value;
    }

    /**
     * @param lonNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setLonNano(final long lonNano) {
        putUInt64(at(Struct.LonNano), lonNano);
    }

}

