//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryLatestFilterBatch extends Batch {


    interface Struct {
        int SIZE = 128;

        int Limit = 0;
        int ReservedAlign = 4;
        int GroupId = 8;
        int CursorTimestamp = 16;
        int Reserved = 24;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryLatestFilterBatch(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryLatestFilterBatch(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#limit">limit</a>
     */
    public int getLimit() {
        final var value = getUInt32(at(Struct.Limit));
        return value;
    }

    /**
     * @param limit
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#limit">limit</a>
     */
    public void setLimit(final int limit) {
        putUInt32(at(Struct.Limit), limit);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-latest-filter#_reserved_align">_reserved_align</a>
     */
    public int getReservedAlign() {
        final var value = getUInt32(at(Struct.ReservedAlign));
        return value;
    }

    /**
     * @param reservedAlign
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-latest-filter#_reserved_align">_reserved_align</a>
     */
    public void setReservedAlign(final int reservedAlign) {
        putUInt32(at(Struct.ReservedAlign), reservedAlign);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#group_id">group_id</a>
     */
    public long getGroupId() {
        final var value = getUInt64(at(Struct.GroupId));
        return value;
    }

    /**
     * @param groupId
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#group_id">group_id</a>
     */
    public void setGroupId(final long groupId) {
        putUInt64(at(Struct.GroupId), groupId);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-latest-filter#cursor_timestamp">cursor_timestamp</a>
     */
    public long getCursorTimestamp() {
        final var value = getUInt64(at(Struct.CursorTimestamp));
        return value;
    }

    /**
     * @param cursorTimestamp
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-latest-filter#cursor_timestamp">cursor_timestamp</a>
     */
    public void setCursorTimestamp(final long cursorTimestamp) {
        putUInt64(at(Struct.CursorTimestamp), cursorTimestamp);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#reserved">reserved</a>
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 104);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-latest-filter#reserved">reserved</a>
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[104];
        if (reserved.length != 104)
            throw new IllegalArgumentException("Reserved must be 104 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

