//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryResponse extends Batch {


    interface Struct {
        int SIZE = 16;

        int Count = 0;
        int HasMore = 4;
        int PartialResult = 5;
        int Reserved = 6;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryResponse(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryResponse(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getCount() {
        final var value = getUInt32(at(Struct.Count));
        return value;
    }

    /**
     * @param count
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setCount(final int count) {
        putUInt32(at(Struct.Count), count);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getHasMore() {
        final var value = getUInt8(at(Struct.HasMore));
        return value;
    }

    /**
     * @param hasMore
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setHasMore(final byte hasMore) {
        putUInt8(at(Struct.HasMore), hasMore);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getPartialResult() {
        final var value = getUInt8(at(Struct.PartialResult));
        return value;
    }

    /**
     * @param partialResult
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setPartialResult(final byte partialResult) {
        putUInt8(at(Struct.PartialResult), partialResult);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 10);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[10];
        if (reserved.length != 10)
            throw new IllegalArgumentException("Reserved must be 10 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

