//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryUuidFilterBatch extends Batch {


    interface Struct {
        int SIZE = 32;

        int EntityId = 0;
        int Reserved = 16;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryUuidFilterBatch(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryUuidFilterBatch(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#entity_id">entity_id</a>
     */
    public byte[] getEntityId() {
        return getUInt128(at(Struct.EntityId));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value is to be
     *        retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#entity_id">entity_id</a>
     */
    public long getEntityId(final UInt128 part) {
        return getUInt128(at(Struct.EntityId), part);
    }

    /**
     * @param entityId an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code entityId} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#entity_id">entity_id</a>
     */
    public void setEntityId(final byte[] entityId) {
        putUInt128(at(Struct.EntityId), entityId);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#entity_id">entity_id</a>
     */
    public void setEntityId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#entity_id">entity_id</a>
     */
    public void setEntityId(final long leastSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, 0);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#reserved">reserved</a>
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 16);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-uuid-filter#reserved">reserved</a>
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[16];
        if (reserved.length != 16)
            throw new IllegalArgumentException("Reserved must be 16 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

