// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryPolygonFilterBatch extends Batch {


    interface Struct {
        int SIZE = 128;

        int VertexCount = 0;
        int HoleCount = 4;
        int Limit = 8;
        int ReservedAlign = 12;
        int TimestampMin = 16;
        int TimestampMax = 24;
        int GroupId = 32;
        int Reserved = 40;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryPolygonFilterBatch(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryPolygonFilterBatch(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#vertex_count">vertex_count</a>
     */
    public int getVertexCount() {
        final var value = getUInt32(at(Struct.VertexCount));
        return value;
    }

    /**
     * @param vertexCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#vertex_count">vertex_count</a>
     */
    public void setVertexCount(final int vertexCount) {
        putUInt32(at(Struct.VertexCount), vertexCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#hole_count">hole_count</a>
     */
    public int getHoleCount() {
        final var value = getUInt32(at(Struct.HoleCount));
        return value;
    }

    /**
     * @param holeCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#hole_count">hole_count</a>
     */
    public void setHoleCount(final int holeCount) {
        putUInt32(at(Struct.HoleCount), holeCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#limit">limit</a>
     */
    public int getLimit() {
        final var value = getUInt32(at(Struct.Limit));
        return value;
    }

    /**
     * @param limit
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#limit">limit</a>
     */
    public void setLimit(final int limit) {
        putUInt32(at(Struct.Limit), limit);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#_reserved_align">_reserved_align</a>
     */
    public int getReservedAlign() {
        final var value = getUInt32(at(Struct.ReservedAlign));
        return value;
    }

    /**
     * @param reservedAlign
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#_reserved_align">_reserved_align</a>
     */
    public void setReservedAlign(final int reservedAlign) {
        putUInt32(at(Struct.ReservedAlign), reservedAlign);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#timestamp_min">timestamp_min</a>
     */
    public long getTimestampMin() {
        final var value = getUInt64(at(Struct.TimestampMin));
        return value;
    }

    /**
     * @param timestampMin
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#timestamp_min">timestamp_min</a>
     */
    public void setTimestampMin(final long timestampMin) {
        putUInt64(at(Struct.TimestampMin), timestampMin);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#timestamp_max">timestamp_max</a>
     */
    public long getTimestampMax() {
        final var value = getUInt64(at(Struct.TimestampMax));
        return value;
    }

    /**
     * @param timestampMax
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#timestamp_max">timestamp_max</a>
     */
    public void setTimestampMax(final long timestampMax) {
        putUInt64(at(Struct.TimestampMax), timestampMax);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#group_id">group_id</a>
     */
    public long getGroupId() {
        final var value = getUInt64(at(Struct.GroupId));
        return value;
    }

    /**
     * @param groupId
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#group_id">group_id</a>
     */
    public void setGroupId(final long groupId) {
        putUInt64(at(Struct.GroupId), groupId);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#reserved">reserved</a>
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 88);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-polygon-filter#reserved">reserved</a>
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[88];
        if (reserved.length != 88)
            throw new IllegalArgumentException("Reserved must be 88 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

