//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryRadiusFilterBatch extends Batch {


    interface Struct {
        int SIZE = 128;

        int CenterLatNano = 0;
        int CenterLonNano = 8;
        int RadiusMm = 16;
        int Limit = 20;
        int TimestampMin = 24;
        int TimestampMax = 32;
        int GroupId = 40;
        int Reserved = 48;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryRadiusFilterBatch(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryRadiusFilterBatch(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#center_lat_nano">center_lat_nano</a>
     */
    public long getCenterLatNano() {
        final var value = getUInt64(at(Struct.CenterLatNano));
        return value;
    }

    /**
     * @param centerLatNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#center_lat_nano">center_lat_nano</a>
     */
    public void setCenterLatNano(final long centerLatNano) {
        putUInt64(at(Struct.CenterLatNano), centerLatNano);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#center_lon_nano">center_lon_nano</a>
     */
    public long getCenterLonNano() {
        final var value = getUInt64(at(Struct.CenterLonNano));
        return value;
    }

    /**
     * @param centerLonNano
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#center_lon_nano">center_lon_nano</a>
     */
    public void setCenterLonNano(final long centerLonNano) {
        putUInt64(at(Struct.CenterLonNano), centerLonNano);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#radius_mm">radius_mm</a>
     */
    public int getRadiusMm() {
        final var value = getUInt32(at(Struct.RadiusMm));
        return value;
    }

    /**
     * @param radiusMm
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#radius_mm">radius_mm</a>
     */
    public void setRadiusMm(final int radiusMm) {
        putUInt32(at(Struct.RadiusMm), radiusMm);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#limit">limit</a>
     */
    public int getLimit() {
        final var value = getUInt32(at(Struct.Limit));
        return value;
    }

    /**
     * @param limit
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#limit">limit</a>
     */
    public void setLimit(final int limit) {
        putUInt32(at(Struct.Limit), limit);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#timestamp_min">timestamp_min</a>
     */
    public long getTimestampMin() {
        final var value = getUInt64(at(Struct.TimestampMin));
        return value;
    }

    /**
     * @param timestampMin
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#timestamp_min">timestamp_min</a>
     */
    public void setTimestampMin(final long timestampMin) {
        putUInt64(at(Struct.TimestampMin), timestampMin);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#timestamp_max">timestamp_max</a>
     */
    public long getTimestampMax() {
        final var value = getUInt64(at(Struct.TimestampMax));
        return value;
    }

    /**
     * @param timestampMax
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href=
     *      "https://docs.archerdb.io/reference/query-radius-filter#timestamp_max">timestamp_max</a>
     */
    public void setTimestampMax(final long timestampMax) {
        putUInt64(at(Struct.TimestampMax), timestampMax);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#group_id">group_id</a>
     */
    public long getGroupId() {
        final var value = getUInt64(at(Struct.GroupId));
        return value;
    }

    /**
     * @param groupId
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#group_id">group_id</a>
     */
    public void setGroupId(final long groupId) {
        putUInt64(at(Struct.GroupId), groupId);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#reserved">reserved</a>
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 80);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     * @see <a href="https://docs.archerdb.io/reference/query-radius-filter#reserved">reserved</a>
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[80];
        if (reserved.length != 80)
            throw new IllegalArgumentException("Reserved must be 80 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

