// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryUuidBatchResult extends Batch {


    interface Struct {
        int SIZE = 16;

        int FoundCount = 0;
        int NotFoundCount = 4;
        int Reserved = 8;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryUuidBatchResult(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryUuidBatchResult(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getFoundCount() {
        final var value = getUInt32(at(Struct.FoundCount));
        return value;
    }

    /**
     * @param foundCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setFoundCount(final int foundCount) {
        putUInt32(at(Struct.FoundCount), foundCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getNotFoundCount() {
        final var value = getUInt32(at(Struct.NotFoundCount));
        return value;
    }

    /**
     * @param notFoundCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setNotFoundCount(final int notFoundCount) {
        putUInt32(at(Struct.NotFoundCount), notFoundCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 8);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[8];
        if (reserved.length != 8)
            throw new IllegalArgumentException("Reserved must be 8 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

