//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class QueryUuidResponse extends Batch {


    interface Struct {
        int SIZE = 16;

        int Status = 0;
        int Reserved = 1;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public QueryUuidResponse(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    QueryUuidResponse(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getStatus() {
        final var value = getUInt8(at(Struct.Status));
        return value;
    }

    /**
     * @param status
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setStatus(final byte status) {
        putUInt8(at(Struct.Status), status);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 15);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[15];
        if (reserved.length != 15)
            throw new IllegalArgumentException("Reserved must be 15 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

