//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

public enum ShardStatus {
    Active((byte) 0),
    Syncing((byte) 1),
    Unavailable((byte) 2),
    Migrating((byte) 3),
    Decommissioning((byte) 4);

    public final byte value;

    ShardStatus(byte value) {
        this.value = value;
    }

    public static ShardStatus fromValue(byte value) {
        switch (value) {
            case 0:
                return Active;
            case 1:
                return Syncing;
            case 2:
                return Unavailable;
            case 3:
                return Migrating;
            case 4:
                return Decommissioning;
            default:
                throw new IllegalArgumentException(
                        String.format("Invalid ShardStatus value=%d", value));
        }
    }
}

