// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class ShardInfo extends Batch {


    interface Struct {
        int SIZE = 472;

        int Id = 0;
        int Primary = 4;
        int Replicas = 68;
        int ReplicaCount = 452;
        int Status = 453;
        int EntityCount = 454;
        int SizeBytes = 462;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public ShardInfo(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    ShardInfo(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getId() {
        final var value = getUInt32(at(Struct.Id));
        return value;
    }

    /**
     * @param id
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setId(final int id) {
        putUInt32(at(Struct.Id), id);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getPrimary() {
        return getArray(at(Struct.Primary), 64);
    }

    /**
     * @param primary
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setPrimary(byte[] primary) {
        if (primary == null)
            primary = new byte[64];
        if (primary.length != 64)
            throw new IllegalArgumentException("Reserved must be 64 bytes long");
        putArray(at(Struct.Primary), primary);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getReplicas() {
        return getArray(at(Struct.Replicas), 6);
    }

    /**
     * @param replicas
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setReplicas(byte[] replicas) {
        if (replicas == null)
            replicas = new byte[6];
        if (replicas.length != 6)
            throw new IllegalArgumentException("Reserved must be 6 bytes long");
        putArray(at(Struct.Replicas), replicas);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getReplicaCount() {
        final var value = getUInt8(at(Struct.ReplicaCount));
        return value;
    }

    /**
     * @param replicaCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setReplicaCount(final byte replicaCount) {
        putUInt8(at(Struct.ReplicaCount), replicaCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public ShardStatus getStatus() {
        final var value = getUInt8(at(Struct.Status));
        return ShardStatus.fromValue(value);
    }

    /**
     * @param status
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setStatus(final ShardStatus status) {
        putUInt8(at(Struct.Status), status.value);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getEntityCount() {
        final var value = getUInt64(at(Struct.EntityCount));
        return value;
    }

    /**
     * @param entityCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setEntityCount(final long entityCount) {
        putUInt64(at(Struct.EntityCount), entityCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getSizeBytes() {
        final var value = getUInt64(at(Struct.SizeBytes));
        return value;
    }

    /**
     * @param sizeBytes
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setSizeBytes(final long sizeBytes) {
        putUInt64(at(Struct.SizeBytes), sizeBytes);
    }

}

