// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors
//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class StatusResponse extends Batch {


    interface Struct {
        int SIZE = 64;

        int RamIndexCount = 0;
        int RamIndexCapacity = 8;
        int RamIndexLoadPct = 16;
        int Padding = 20;
        int TombstoneCount = 24;
        int TtlExpirations = 32;
        int DeletionCount = 40;
        int IndexResizeStatus = 48;
        int MembershipState = 49;
        int StatusPadding = 50;
        int IndexResizeProgress = 52;
        int MembershipVotersCount = 56;
        int MembershipLearnersCount = 60;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public StatusResponse(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    StatusResponse(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getRamIndexCount() {
        final var value = getUInt64(at(Struct.RamIndexCount));
        return value;
    }

    /**
     * @param ramIndexCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setRamIndexCount(final long ramIndexCount) {
        putUInt64(at(Struct.RamIndexCount), ramIndexCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getRamIndexCapacity() {
        final var value = getUInt64(at(Struct.RamIndexCapacity));
        return value;
    }

    /**
     * @param ramIndexCapacity
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setRamIndexCapacity(final long ramIndexCapacity) {
        putUInt64(at(Struct.RamIndexCapacity), ramIndexCapacity);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getRamIndexLoadPct() {
        final var value = getUInt32(at(Struct.RamIndexLoadPct));
        return value;
    }

    /**
     * @param ramIndexLoadPct
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setRamIndexLoadPct(final int ramIndexLoadPct) {
        putUInt32(at(Struct.RamIndexLoadPct), ramIndexLoadPct);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    int getPadding() {
        final var value = getUInt32(at(Struct.Padding));
        return value;
    }

    /**
     * @param padding
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setPadding(final int padding) {
        putUInt32(at(Struct.Padding), padding);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getTombstoneCount() {
        final var value = getUInt64(at(Struct.TombstoneCount));
        return value;
    }

    /**
     * @param tombstoneCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setTombstoneCount(final long tombstoneCount) {
        putUInt64(at(Struct.TombstoneCount), tombstoneCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getTtlExpirations() {
        final var value = getUInt64(at(Struct.TtlExpirations));
        return value;
    }

    /**
     * @param ttlExpirations
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setTtlExpirations(final long ttlExpirations) {
        putUInt64(at(Struct.TtlExpirations), ttlExpirations);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getDeletionCount() {
        final var value = getUInt64(at(Struct.DeletionCount));
        return value;
    }

    /**
     * @param deletionCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setDeletionCount(final long deletionCount) {
        putUInt64(at(Struct.DeletionCount), deletionCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getIndexResizeStatus() {
        final var value = getUInt8(at(Struct.IndexResizeStatus));
        return value;
    }

    /**
     * @param indexResizeStatus
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setIndexResizeStatus(final byte indexResizeStatus) {
        putUInt8(at(Struct.IndexResizeStatus), indexResizeStatus);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getMembershipState() {
        final var value = getUInt8(at(Struct.MembershipState));
        return value;
    }

    /**
     * @param membershipState
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setMembershipState(final byte membershipState) {
        putUInt8(at(Struct.MembershipState), membershipState);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getStatusPadding() {
        final var value = getUInt16(at(Struct.StatusPadding));
        return value;
    }

    /**
     * @param statusPadding
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setStatusPadding(final int statusPadding) {
        putUInt16(at(Struct.StatusPadding), statusPadding);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getIndexResizeProgress() {
        final var value = getUInt32(at(Struct.IndexResizeProgress));
        return value;
    }

    /**
     * @param indexResizeProgress
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setIndexResizeProgress(final int indexResizeProgress) {
        putUInt32(at(Struct.IndexResizeProgress), indexResizeProgress);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getMembershipVotersCount() {
        final var value = getUInt32(at(Struct.MembershipVotersCount));
        return value;
    }

    /**
     * @param membershipVotersCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setMembershipVotersCount(final int membershipVotersCount) {
        putUInt32(at(Struct.MembershipVotersCount), membershipVotersCount);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getMembershipLearnersCount() {
        final var value = getUInt32(at(Struct.MembershipLearnersCount));
        return value;
    }

    /**
     * @param membershipLearnersCount
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setMembershipLearnersCount(final int membershipLearnersCount) {
        putUInt32(at(Struct.MembershipLearnersCount), membershipLearnersCount);
    }

}

