//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class TopologyResponse extends Batch {


    interface Struct {
        int SIZE = 120896;

        int Version = 0;
        int NumShards = 8;
        int ClusterId = 12;
        int LastChangeNs = 28;
        int ReshardingStatus = 44;
        int Flags = 45;
        int Padding = 46;
        int Shards = 52;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public TopologyResponse(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    TopologyResponse(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getVersion() {
        final var value = getUInt64(at(Struct.Version));
        return value;
    }

    /**
     * @param version
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setVersion(final long version) {
        putUInt64(at(Struct.Version), version);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getNumShards() {
        final var value = getUInt32(at(Struct.NumShards));
        return value;
    }

    /**
     * @param numShards
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setNumShards(final int numShards) {
        putUInt32(at(Struct.NumShards), numShards);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getClusterId() {
        return getUInt128(at(Struct.ClusterId));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getClusterId(final UInt128 part) {
        return getUInt128(at(Struct.ClusterId), part);
    }

    /**
     * @param clusterId an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code clusterId} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setClusterId(final byte[] clusterId) {
        putUInt128(at(Struct.ClusterId), clusterId);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setClusterId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.ClusterId), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setClusterId(final long leastSignificant) {
        putUInt128(at(Struct.ClusterId), leastSignificant, 0);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getLastChangeNs() {
        return getUInt128(at(Struct.LastChangeNs));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value
              is to be retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getLastChangeNs(final UInt128 part) {
        return getUInt128(at(Struct.LastChangeNs), part);
    }

    /**
     * @param lastChangeNs an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code lastChangeNs} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setLastChangeNs(final byte[] lastChangeNs) {
        putUInt128(at(Struct.LastChangeNs), lastChangeNs);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setLastChangeNs(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.LastChangeNs), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setLastChangeNs(final long leastSignificant) {
        putUInt128(at(Struct.LastChangeNs), leastSignificant, 0);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getReshardingStatus() {
        final var value = getUInt8(at(Struct.ReshardingStatus));
        return value;
    }

    /**
     * @param reshardingStatus
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setReshardingStatus(final byte reshardingStatus) {
        putUInt8(at(Struct.ReshardingStatus), reshardingStatus);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte getFlags() {
        final var value = getUInt8(at(Struct.Flags));
        return value;
    }

    /**
     * @param flags
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setFlags(final byte flags) {
        putUInt8(at(Struct.Flags), flags);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getPadding() {
        return getArray(at(Struct.Padding), 6);
    }

    /**
     * @param padding
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setPadding(byte[] padding) {
        if (padding == null)
            padding = new byte[6];
        if (padding.length != 6)
            throw new IllegalArgumentException("Reserved must be 6 bytes long");
        putArray(at(Struct.Padding), padding);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getShards() {
        return getArray(at(Struct.Shards), 256);
    }

    /**
     * @param shards
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setShards(byte[] shards) {
        if (shards == null)
            shards = new byte[256];
        if (shards.length != 256)
            throw new IllegalArgumentException("Reserved must be 256 bytes long");
        putArray(at(Struct.Shards), shards);
    }

}

