//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

import java.nio.ByteBuffer;


public final class TtlExtendResponse extends Batch {


    interface Struct {
        int SIZE = 64;

        int EntityId = 0;
        int PreviousTtlSeconds = 16;
        int NewTtlSeconds = 20;
        int Result = 24;
        int Padding = 25;
        int Reserved = 28;
    }

    /**
     * Creates an empty batch with the desired maximum capacity.
     * <p>
     * Once created, an instance cannot be resized, however it may contain any number of elements
     * between zero and its {@link #getCapacity capacity}.
     *
     * @param capacity the maximum capacity.
     * @throws IllegalArgumentException if capacity is negative.
     */
    public TtlExtendResponse(final int capacity) {
        super(capacity, Struct.SIZE);
    }

    TtlExtendResponse(final ByteBuffer buffer) {
        super(buffer, Struct.SIZE);
    }

    /**
     * @return an array of 16 bytes representing the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public byte[] getEntityId() {
        return getUInt128(at(Struct.EntityId));
    }

    /**
     * @param part a {@link UInt128} enum indicating which part of the 128-bit value is to be
     *        retrieved.
     * @return a {@code long} representing the first 8 bytes of the 128-bit value if
     *         {@link UInt128#LeastSignificant} is informed, or the last 8 bytes if
     *         {@link UInt128#MostSignificant}.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public long getEntityId(final UInt128 part) {
        return getUInt128(at(Struct.EntityId), part);
    }

    /**
     * @param entityId an array of 16 bytes representing the 128-bit value.
     * @throws IllegalArgumentException if {@code entityId} is not 16 bytes long.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setEntityId(final byte[] entityId) {
        putUInt128(at(Struct.EntityId), entityId);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @param mostSignificant a {@code long} representing the last 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setEntityId(final long leastSignificant, final long mostSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, mostSignificant);
    }

    /**
     * @param leastSignificant a {@code long} representing the first 8 bytes of the 128-bit value.
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setEntityId(final long leastSignificant) {
        putUInt128(at(Struct.EntityId), leastSignificant, 0);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getPreviousTtlSeconds() {
        final var value = getUInt32(at(Struct.PreviousTtlSeconds));
        return value;
    }

    /**
     * @param previousTtlSeconds
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setPreviousTtlSeconds(final int previousTtlSeconds) {
        putUInt32(at(Struct.PreviousTtlSeconds), previousTtlSeconds);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public int getNewTtlSeconds() {
        final var value = getUInt32(at(Struct.NewTtlSeconds));
        return value;
    }

    /**
     * @param newTtlSeconds
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setNewTtlSeconds(final int newTtlSeconds) {
        putUInt32(at(Struct.NewTtlSeconds), newTtlSeconds);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    public TtlOperationResult getResult() {
        final var value = getUInt8(at(Struct.Result));
        return TtlOperationResult.fromValue(value);
    }

    /**
     * @param result
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    public void setResult(final TtlOperationResult result) {
        putUInt8(at(Struct.Result), result.value);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getPadding() {
        return getArray(at(Struct.Padding), 3);
    }

    /**
     * @param padding
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setPadding(byte[] padding) {
        if (padding == null)
            padding = new byte[3];
        if (padding.length != 3)
            throw new IllegalArgumentException("Reserved must be 3 bytes long");
        putArray(at(Struct.Padding), padding);
    }

    /**
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     */
    byte[] getReserved() {
        return getArray(at(Struct.Reserved), 32);
    }

    /**
     * @param reserved
     * @throws IllegalStateException if not at a {@link #isValidPosition valid position}.
     * @throws IllegalStateException if a {@link #isReadOnly() read-only} batch.
     */
    void setReserved(byte[] reserved) {
        if (reserved == null)
            reserved = new byte[32];
        if (reserved.length != 32)
            throw new IllegalArgumentException("Reserved must be 32 bytes long");
        putArray(at(Struct.Reserved), reserved);
    }

}

