//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package io.archerdb;

public enum TtlOperationResult {
    Success((byte) 0),
    EntityNotFound((byte) 1),
    InvalidTtl((byte) 2),
    NotPermitted((byte) 3),
    EntityImmutable((byte) 4);

    public final byte value;

    TtlOperationResult(byte value) {
        this.value = value;
    }

    public static TtlOperationResult fromValue(byte value) {
        switch (value) {
            case 0: return Success;
            case 1: return EntityNotFound;
            case 2: return InvalidTtl;
            case 3: return NotPermitted;
            case 4: return EntityImmutable;
            default: throw new IllegalArgumentException(
                String.format("Invalid TtlOperationResult value=%d", value));
        }
    }
}

