// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors

/**
 * @file arch_client.h
 * @brief ArcherDB C Client - High-performance geospatial database client
 * @version 0.1.0
 *
 * @details This header provides the C API for interacting with ArcherDB,
 *          a high-performance geospatial database optimized for real-time
 *          location tracking and spatial queries.
 *
 * @section memory_ownership Memory Ownership
 * - **Client resources**: The arch_client_t owns all connection and network resources.
 *   Call arch_client_deinit() to release these resources.
 * - **Request data**: Caller owns geo_event_t arrays and filter structs passed to operations.
 *   Data must remain valid until the completion callback is invoked.
 * - **Response data**: Data passed to completion callbacks is library-owned.
 *   Copy any data you need to retain before the callback returns.
 *
 * @section thread_safety Thread Safety
 * - The arch_client_t is NOT thread-safe. Do not call arch_client_submit() from
 *   multiple threads without external synchronization.
 * - **Recommended**: Create one arch_client_t per thread, or use a mutex.
 * - The completion callback may be invoked from a different thread than the
 *   thread that called arch_client_submit().
 *
 * @section error_codes Error Code Ranges
 * - 0: Success
 * - 1-99: Protocol errors (message format, checksums, version)
 * - 100-199: Validation errors (invalid inputs, constraint violations)
 * - 200-299: State errors (multi-region 213-218, sharding 220-224)
 * - 300-399: Resource errors (limits exceeded, capacity)
 * - 400-499: Security errors (auth, encryption 410-414)
 * - 500-599: Internal errors (bugs, should not occur)
 *
 * See error-codes.md for complete documentation.
 *
 * @warning This file is auto-generated by arch_client_header.zig. Do not modify directly.
 */

 //////////////////////////////////////////////////////////
 // This file was auto-generated by arch_client_header.zig //
 //              Do not manually modify.                 //
 //////////////////////////////////////////////////////////

#ifndef ARCH_CLIENT_H
#define ARCH_CLIENT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/** @brief 128-bit unsigned integer type */
typedef __uint128_t arch_uint128_t;
/** @brief 128-bit signed integer type */
typedef __int128_t arch_int128_t;

/**
 * @brief Flags for geo_event_t indicating event state and attributes.
 * @details Multiple flags can be combined using bitwise OR.
 *          These flags affect how events are processed and stored.
 */
typedef enum GEO_EVENT_FLAGS {
    GEO_EVENT_LINKED = 1 << 0,
    GEO_EVENT_IMPORTED = 1 << 1,
    GEO_EVENT_STATIONARY = 1 << 2,
    GEO_EVENT_LOW_ACCURACY = 1 << 3,
    GEO_EVENT_OFFLINE = 1 << 4,
    GEO_EVENT_DELETED = 1 << 5,
} GEO_EVENT_FLAGS;

/**
 * @brief A geospatial event representing an entity's location at a point in time.
 * @details This is the primary data structure for storing location data.
 *
 * @par Memory Ownership
 * Caller owns geo_event_t arrays passed to insert operations.
 * Events returned in query callbacks are library-owned and must not be freed.
 *
 * @par Field Units
 * - id: Unique 128-bit event identifier (must be non-zero)
 * - entity_id: 128-bit identifier for the tracked entity (must be non-zero, not INT_MAX)
 * - correlation_id: Optional 128-bit ID for linking related events
 * - user_data: 128-bit user-defined data (application-specific)
 * - lat_nano: Latitude in nanodegrees (1e-9 degrees), range: [-90e9, 90e9]
 * - lon_nano: Longitude in nanodegrees (1e-9 degrees), range: [-180e9, 180e9]
 * - group_id: Logical grouping for tenant isolation
 * - timestamp: Server-assigned timestamp in nanoseconds (set to 0 on insert)
 * - altitude_mm: Altitude in millimeters above sea level
 * - velocity_mms: Speed in millimeters per second
 * - ttl_seconds: Time-to-live in seconds (0 = no expiration)
 * - accuracy_mm: Location accuracy in millimeters
 * - heading_cdeg: Heading in centidegrees (0-36000, where 0=North, 9000=East)
 * - flags: Combination of GEO_EVENT_FLAGS values
 * - reserved: Must be zero (reserved for future use)
 */
typedef struct geo_event_t {
    arch_uint128_t id;
    arch_uint128_t entity_id;
    arch_uint128_t correlation_id;
    arch_uint128_t user_data;
    int64_t lat_nano;
    int64_t lon_nano;
    uint64_t group_id;
    uint64_t timestamp;
    int32_t altitude_mm;
    uint32_t velocity_mms;
    uint32_t ttl_seconds;
    uint32_t accuracy_mm;
    uint16_t heading_cdeg;
    uint16_t flags;
    uint8_t reserved[12];
} geo_event_t;

/**
 * @brief Result codes for individual geo event insertions.
 * @details Error codes 100-199 are validation errors (client should fix request).
 *          See error-codes.md for complete error code documentation.
 */
typedef enum INSERT_GEO_EVENT_RESULT {
    INSERT_GEO_EVENT_OK = 0,
    INSERT_GEO_EVENT_LINKED_EVENT_FAILED = 1,
    INSERT_GEO_EVENT_LINKED_EVENT_CHAIN_OPEN = 2,
    INSERT_GEO_EVENT_TIMESTAMP_MUST_BE_ZERO = 3,
    INSERT_GEO_EVENT_RESERVED_FIELD = 4,
    INSERT_GEO_EVENT_RESERVED_FLAG = 5,
    INSERT_GEO_EVENT_ID_MUST_NOT_BE_ZERO = 6,
    INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_ZERO = 7,
    INSERT_GEO_EVENT_INVALID_COORDINATES = 8,
    INSERT_GEO_EVENT_LAT_OUT_OF_RANGE = 9,
    INSERT_GEO_EVENT_LON_OUT_OF_RANGE = 10,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_ENTITY_ID = 11,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_COORDINATES = 12,
    INSERT_GEO_EVENT_EXISTS = 13,
    INSERT_GEO_EVENT_HEADING_OUT_OF_RANGE = 14,
    INSERT_GEO_EVENT_TTL_INVALID = 15,
    INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_INT_MAX = 16,
    INSERT_GEO_EVENT_STORAGE_SPACE_EXHAUSTED = 17,
} INSERT_GEO_EVENT_RESULT;

/**
 * @brief Result for a single event in a batch insert operation.
 * @details On successful batch insert with no errors, no results are returned.
 *          Results are only returned for events that failed validation.
 */
typedef struct insert_geo_events_result_t {
    uint32_t index;
    uint32_t result;
} insert_geo_events_result_t;

/**
 * @brief Result for a single entity deletion in a batch delete operation.
 * @details Contains the index of the entity in the request and the result code.
 */
typedef struct delete_entities_result_t {
    uint32_t index;
    uint32_t result;
} delete_entities_result_t;

/**
 * @brief Filter for querying the latest event of a specific entity.
 * @details Returns the most recent geo_event_t for the specified entity_id.
 */
typedef struct query_uuid_filter_t {
    arch_uint128_t entity_id;
    uint8_t reserved[16];
} query_uuid_filter_t;

/**
 * @brief Response header for UUID query operations.
 * @details Status 0 = found, non-zero = not found or error.
 */
typedef struct query_uuid_response_t {
    uint8_t status;
    uint8_t reserved[15];
} query_uuid_response_t;

/**
 * @brief Filter for querying latest events of multiple entities.
 * @details Entity IDs follow immediately after this header in the request data.
 */
typedef struct query_uuid_batch_filter_t {
    uint32_t count;
    uint8_t reserved[12];
} query_uuid_batch_filter_t;

/**
 * @brief Response header for batch UUID query operations.
 * @details Events are returned in the same order as requested entity_ids.
 *          Missing entities are indicated by found_count vs not_found_count.
 */
typedef struct query_uuid_batch_result_t {
    uint32_t found_count;
    uint32_t not_found_count;
    uint8_t reserved[8];
} query_uuid_batch_result_t;

/**
 * @brief Filter for querying events within a circular radius.
 * @details Uses Haversine formula for accurate great-circle distance.
 *
 * @par Required Fields
 * - center_lat_nano: Center latitude in nanodegrees
 * - center_lon_nano: Center longitude in nanodegrees
 * - radius_mm: Search radius in millimeters
 *
 * @par Optional Fields (set to 0 for default)
 * - limit: Maximum events to return (0 = server default)
 * - timestamp_min: Minimum timestamp filter (0 = no minimum)
 * - timestamp_max: Maximum timestamp filter (0 = no maximum)
 * - group_id: Filter by group (0 = all groups)
 */
typedef struct query_radius_filter_t {
    int64_t center_lat_nano;
    int64_t center_lon_nano;
    uint32_t radius_mm;
    uint32_t limit;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[80];
} query_radius_filter_t;

/**
 * @brief Filter for querying events within a polygon boundary.
 * @details Polygon vertices follow this header, then hole descriptors (if any),
 *          then vertices for each hole. Uses ray-casting point-in-polygon test.
 *
 * @par Polygon Format
 * - Exterior ring: counter-clockwise winding order
 * - Holes: clockwise winding order (GeoJSON convention)
 * - vertex_count: Number of exterior polygon vertices
 * - hole_count: Number of interior holes (0 for simple polygons)
 *
 * @par Optional Fields (set to 0 for default)
 * - limit: Maximum events to return (0 = server default)
 * - timestamp_min: Minimum timestamp filter
 * - timestamp_max: Maximum timestamp filter
 * - group_id: Filter by group
 */
typedef struct query_polygon_filter_t {
    uint32_t vertex_count;
    uint32_t hole_count;
    uint32_t limit;
    uint32_t _reserved_align;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[88];
} query_polygon_filter_t;

/**
 * @brief Filter for querying the most recent events across all entities.
 * @details Returns events ordered by timestamp descending.
 *          Use cursor_timestamp for pagination.
 */
typedef struct query_latest_filter_t {
    uint32_t limit;
    uint32_t _reserved_align;
    uint64_t group_id;
    uint64_t cursor_timestamp;
    uint8_t reserved[104];
} query_latest_filter_t;

/**
 * @brief Response header for query operations.
 * @details Followed by count geo_event_t structures in the response data.
 *
 * @par Fields
 * - count: Number of events in this response
 * - has_more: Non-zero if more results available (pagination needed)
 * - partial_result: Non-zero if query timed out before completion
 */
typedef struct query_response_t {
    uint32_t count;
    uint8_t has_more;
    uint8_t partial_result;
    uint8_t reserved[10];
} query_response_t;

/**
 * @brief A vertex point in a polygon for geospatial queries.
 * @details Coordinates are in nanodegrees (1e-9 degrees).
 */
typedef struct polygon_vertex_t {
    int64_t lat_nano;
    int64_t lon_nano;
} polygon_vertex_t;

/**
 * @brief Descriptor for a hole within a polygon.
 * @details Holes use clockwise winding order (opposite of exterior ring).
 */
typedef struct hole_descriptor_t {
    uint32_t vertex_count;
    uint32_t reserved;
} hole_descriptor_t;

/**
 * @brief Request structure for ping/health check operation.
 */
typedef struct ping_request_t {
    uint64_t ping_data;
} ping_request_t;

/**
 * @brief Request structure for server status operation.
 */
typedef struct status_request_t {
    uint64_t reserved;
} status_request_t;

/**
 * @brief Response structure for ping/health check operation.
 */
typedef struct ping_response_t {
    uint32_t pong;
} ping_response_t;

/**
 * @brief Server status response with index statistics.
 * @details Provides insight into server capacity and resource usage.
 */
typedef struct status_response_t {
    uint64_t ram_index_count;
    uint64_t ram_index_capacity;
    uint32_t ram_index_load_pct;
    uint32_t _padding;
    uint64_t tombstone_count;
    uint64_t ttl_expirations;
    uint64_t deletion_count;
    uint8_t index_resize_status;
    uint8_t membership_state;
    uint16_t _status_padding;
    uint32_t index_resize_progress;
    uint32_t membership_voters_count;
    uint32_t membership_learners_count;
} status_response_t;

/**
 * @brief Request structure for cluster topology information.
 */
typedef struct topology_request_t {
    uint64_t reserved;
} topology_request_t;

/**
 * @brief Information about a single shard in the cluster.
 */
typedef struct shard_info_t {
    uint32_t id;
    uint8_t primary[64];
    uint8_t replicas[6];
    uint8_t replica_count;
    uint8_t status;
    uint64_t entity_count;
    uint64_t size_bytes;
} shard_info_t;

/**
 * @brief Status values for shards in the cluster topology.
 */
typedef enum SHARD_STATUS {
    SHARD_STATUS_ACTIVE = 0,
    SHARD_STATUS_SYNCING = 1,
    SHARD_STATUS_UNAVAILABLE = 2,
    SHARD_STATUS_MIGRATING = 3,
    SHARD_STATUS_DECOMMISSIONING = 4,
} SHARD_STATUS;

/**
 * @brief Cluster topology response with shard information.
 * @details Contains current cluster state and shard assignments.
 */
typedef struct topology_response_t {
    uint64_t version;
    uint32_t num_shards;
    arch_uint128_t cluster_id;
    arch_int128_t last_change_ns;
    uint8_t resharding_status;
    uint8_t flags;
    uint8_t _padding[6];
    shard_info_t shards[256];
} topology_response_t;

/**
 * @brief Result codes for TTL (time-to-live) operations.
 */
typedef enum TTL_OPERATION_RESULT {
    TTL_OPERATION_SUCCESS = 0,
    TTL_OPERATION_ENTITY_NOT_FOUND = 1,
    TTL_OPERATION_INVALID_TTL = 2,
    TTL_OPERATION_NOT_PERMITTED = 3,
    TTL_OPERATION_ENTITY_IMMUTABLE = 4,
    TTL_OPERATION_STORAGE_SPACE_EXHAUSTED = 5,
} TTL_OPERATION_RESULT;

/**
 * @brief Request to set TTL on an entity.
 * @details TTL is specified in seconds from the current time.
 */
typedef struct ttl_set_request_t {
    arch_uint128_t entity_id;
    uint32_t ttl_seconds;
    uint32_t flags;
    uint8_t reserved[40];
} ttl_set_request_t;

/**
 * @brief Response for TTL set operation.
 * @details Contains both previous and new TTL values.
 */
typedef struct ttl_set_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint32_t new_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[32];
} ttl_set_response_t;

/**
 * @brief Request to extend TTL on an entity.
 * @details Extends existing TTL by the specified number of seconds.
 */
typedef struct ttl_extend_request_t {
    arch_uint128_t entity_id;
    uint32_t extend_by_seconds;
    uint32_t flags;
    uint8_t reserved[40];
} ttl_extend_request_t;

/**
 * @brief Response for TTL extend operation.
 * @details Contains both previous and new TTL values.
 */
typedef struct ttl_extend_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint32_t new_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[32];
} ttl_extend_response_t;

/**
 * @brief Request to clear (remove) TTL from an entity.
 * @details Entity will no longer expire automatically.
 */
typedef struct ttl_clear_request_t {
    arch_uint128_t entity_id;
    uint32_t flags;
    uint8_t reserved[44];
} ttl_clear_request_t;

/**
 * @brief Response for TTL clear operation.
 * @details Contains the previous TTL value before clearing.
 */
typedef struct ttl_clear_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[36];
} ttl_clear_response_t;

/**
 * @brief Opaque client handle for ArcherDB connections.
 * @details This struct must be "pinned" (not copyable or movable), as its
 *          address must remain stable throughout the lifetime of the client.
 *
 * @par Memory Ownership
 * The client owns all connection resources. Call arch_client_deinit() to release.
 *
 * @par Thread Safety
 * NOT thread-safe. Create one client per thread, or use external synchronization.
 * The completion callback may be invoked from a different thread than arch_client_submit().
 */
typedef struct arch_client_t {
    uint64_t opaque[4];
} arch_client_t;

/**
 * @brief Packet structure for submitting requests to the server.
 * @details This struct must be "pinned" (not copyable or movable), as its
 *          address must remain stable throughout the lifetime of the request.
 *
 * @par Fields
 * - user_data: Application-defined context pointer
 * - data: Pointer to request data (operation-specific)
 * - data_size: Size of request data in bytes
 * - user_tag: Application-defined request identifier
 * - operation: ARCH_OPERATION value for this request
 * - status: ARCH_PACKET_STATUS set on completion
 */
typedef struct arch_packet_t {
    void* user_data;
    void* data;
    uint32_t data_size;
    uint16_t user_tag;
    uint8_t operation;
    uint8_t status;
    uint8_t opaque[64];
} arch_packet_t;

/**
 * @brief Operation codes for ArcherDB requests.
 * @details Set packet.operation to one of these values before calling arch_client_submit().
 */
typedef enum ARCH_OPERATION {
    ARCH_OPERATION_PULSE = 128,
    ARCH_OPERATION_INSERT_EVENTS = 146,
    ARCH_OPERATION_UPSERT_EVENTS = 147,
    ARCH_OPERATION_DELETE_ENTITIES = 148,
    ARCH_OPERATION_QUERY_UUID = 149,
    ARCH_OPERATION_QUERY_RADIUS = 150,
    ARCH_OPERATION_QUERY_POLYGON = 151,
    ARCH_OPERATION_QUERY_LATEST = 154,
    ARCH_OPERATION_QUERY_UUID_BATCH = 156,
    ARCH_OPERATION_ARCHERDB_PING = 152,
    ARCH_OPERATION_ARCHERDB_GET_STATUS = 153,
    ARCH_OPERATION_CLEANUP_EXPIRED = 155,
    ARCH_OPERATION_GET_TOPOLOGY = 157,
    ARCH_OPERATION_TTL_SET = 158,
    ARCH_OPERATION_TTL_EXTEND = 159,
    ARCH_OPERATION_TTL_CLEAR = 160,
    ARCH_OPERATION_BATCH_QUERY = 161,
    ARCH_OPERATION_PREPARE_QUERY = 162,
    ARCH_OPERATION_EXECUTE_PREPARED = 163,
    ARCH_OPERATION_DEALLOCATE_PREPARED = 164,
} ARCH_OPERATION;

/**
 * @brief Status codes for completed packets.
 * @details Check packet.status after completion callback to determine result.
 */
typedef enum ARCH_PACKET_STATUS {
    ARCH_PACKET_OK = 0,
    ARCH_PACKET_TOO_MUCH_DATA = 1,
    ARCH_PACKET_CLIENT_EVICTED = 2,
    ARCH_PACKET_CLIENT_RELEASE_TOO_LOW = 3,
    ARCH_PACKET_CLIENT_RELEASE_TOO_HIGH = 4,
    ARCH_PACKET_CLIENT_SHUTDOWN = 5,
    ARCH_PACKET_INVALID_OPERATION = 6,
    ARCH_PACKET_INVALID_DATA_SIZE = 7,
} ARCH_PACKET_STATUS;

/**
 * @brief Status codes for client initialization.
 * @details Returned by arch_client_init() and arch_client_init_echo().
 */
typedef enum ARCH_INIT_STATUS {
    ARCH_INIT_SUCCESS = 0,
    ARCH_INIT_UNEXPECTED = 1,
    ARCH_INIT_OUT_OF_MEMORY = 2,
    ARCH_INIT_ADDRESS_INVALID = 3,
    ARCH_INIT_ADDRESS_LIMIT_EXCEEDED = 4,
    ARCH_INIT_SYSTEM_RESOURCES = 5,
    ARCH_INIT_NETWORK_SUBSYSTEM = 6,
} ARCH_INIT_STATUS;

/**
 * @brief Status codes for client operations.
 * @details Returned by arch_client_submit(), arch_client_deinit(), etc.
 */
typedef enum ARCH_CLIENT_STATUS {
    ARCH_CLIENT_OK = 0,
    ARCH_CLIENT_INVALID = 1,
} ARCH_CLIENT_STATUS;

/**
 * @brief Status codes for log callback registration.
 */
typedef enum ARCH_REGISTER_LOG_CALLBACK_STATUS {
    ARCH_REGISTER_LOG_CALLBACK_SUCCESS = 0,
    ARCH_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED = 1,
    ARCH_REGISTER_LOG_CALLBACK_NOT_REGISTERED = 2,
} ARCH_REGISTER_LOG_CALLBACK_STATUS;

/**
 * @brief Log levels for the log callback.
 */
typedef enum ARCH_LOG_LEVEL {
    ARCH_LOG_ERR = 0,
    ARCH_LOG_WARN = 1,
    ARCH_LOG_INFO = 2,
    ARCH_LOG_DEBUG = 3,
} ARCH_LOG_LEVEL;

/**
 * @brief Parameters used during client initialization.
 * @details Retrieved via arch_client_init_parameters().
 */
typedef struct arch_init_parameters_t {
    arch_uint128_t cluster_id;
    arch_uint128_t client_id;
    uint8_t* addresses_ptr;
    uint64_t addresses_len;
} arch_init_parameters_t;

/**
 * @brief Initialize a new ArcherDB client.
 * @details Connects to the cluster at the specified addresses and completes
 *          submitted packets by invoking the callback with the given context.
 *
 * @param[out] client_out  Pointer to client handle to initialize (must be pinned)
 * @param[in]  cluster_id  128-bit cluster ID as 16-byte little-endian array
 * @param[in]  address_ptr Null-terminated string of comma-separated addresses (e.g., "host:port,host:port")
 * @param[in]  address_len Length of address string in bytes
 * @param[in]  completion_ctx  Application context passed to completion callback
 * @param[in]  completion_callback  Function called when requests complete
 *
 * @return ARCH_INIT_SUCCESS on success, or an error code on failure
 *
 * @note The client handle must remain at a stable address (pinned memory).
 * @note Call arch_client_deinit() to release resources when done.
 *
 * @par Thread Safety
 * This function is NOT thread-safe. Initialize clients from a single thread.
 */
ARCH_INIT_STATUS arch_client_init(
    arch_client_t *client_out,
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, arch_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

/**
 * @brief Initialize a new ArcherDB echo client for testing.
 * @details Creates a client that echoes back any submitted data without
 *          connecting to a real cluster. Useful for unit testing.
 *
 * @param[out] client_out  Pointer to client handle to initialize
 * @param[in]  cluster_id  128-bit cluster ID as 16-byte little-endian array
 * @param[in]  address_ptr Address string (not used for echo client)
 * @param[in]  address_len Length of address string
 * @param[in]  completion_ctx  Application context passed to completion callback
 * @param[in]  completion_callback  Function called when requests complete
 *
 * @return ARCH_INIT_SUCCESS on success, or an error code on failure
 */
ARCH_INIT_STATUS arch_client_init_echo(
    arch_client_t *client_out,
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, arch_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

/**
 * @brief Retrieve the initialization parameters for a client.
 *
 * @param[in]  client  Initialized client handle
 * @param[out] init_parameters_out  Pointer to receive initialization parameters
 *
 * @return ARCH_CLIENT_OK on success, ARCH_CLIENT_INVALID if client is invalid
 */
ARCH_CLIENT_STATUS arch_client_init_parameters(
    arch_client_t* client,
    arch_init_parameters_t* init_parameters_out
);

/**
 * @brief Retrieve the completion context for a client.
 *
 * @param[in]  client  Initialized client handle
 * @param[out] completion_ctx_out  Pointer to receive the completion context
 *
 * @return ARCH_CLIENT_OK on success, ARCH_CLIENT_INVALID if client is invalid
 */
ARCH_CLIENT_STATUS arch_client_completion_context(
    arch_client_t* client,
    uintptr_t* completion_ctx_out
);

/**
 * @brief Submit a request packet to the server.
 * @details The packet must have its operation, data, and data_size fields set.
 *          Once completed, the completion_callback will be invoked with the
 *          completion_ctx and the packet from a separate thread.
 *
 * @param[in] client  Initialized client handle
 * @param[in] packet  Request packet (must be pinned until callback is invoked)
 *
 * @return ARCH_CLIENT_OK on success, ARCH_CLIENT_INVALID if client is invalid
 *
 * @note The packet must remain valid and at a stable address until the
 *       completion callback is invoked.
 * @note The completion callback may be invoked from a different thread.
 *
 * @par Memory Ownership
 * Caller owns the packet and its data until the completion callback.
 * Data in the callback is library-owned and must be copied if needed.
 */
ARCH_CLIENT_STATUS arch_client_submit(
    arch_client_t *client,
    arch_packet_t *packet
);

/**
 * @brief Close the client and release all resources.
 * @details Any previously submitted packets will be completed with
 *          ARCH_PACKET_CLIENT_SHUTDOWN status before resources are freed.
 *
 * @param[in] client  Client handle to close
 *
 * @return ARCH_CLIENT_OK on success, ARCH_CLIENT_INVALID if client is invalid
 *
 * @note After this call, the client handle is invalid and must not be used.
 * @note Wait for all pending callbacks to complete before calling this.
 */
ARCH_CLIENT_STATUS arch_client_deinit(
    arch_client_t *client
);

/**
 * @brief Register or unregister a log callback for client diagnostics.
 *
 * @param[in] callback  Log callback function, or NULL to unregister
 * @param[in] debug     If true, include debug-level messages
 *
 * @return ARCH_REGISTER_LOG_CALLBACK_SUCCESS on success
 * @return ARCH_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED if already registered
 * @return ARCH_REGISTER_LOG_CALLBACK_NOT_REGISTERED if unregistering when not registered
 */
ARCH_REGISTER_LOG_CALLBACK_STATUS arch_client_register_log_callback(
    void (*callback)(ARCH_LOG_LEVEL, const uint8_t*, uint32_t),
    bool debug
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // ARCH_CLIENT_H
