 //////////////////////////////////////////////////////////
 // This file was auto-generated by tb_client_header.zig //
 //              Do not manually modify.                 //
 //////////////////////////////////////////////////////////

#ifndef TB_CLIENT_H
#define TB_CLIENT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef __uint128_t tb_uint128_t;
typedef __int128_t tb_int128_t;

typedef enum GEO_EVENT_FLAGS {
    GEO_EVENT_LINKED = 1 << 0,
    GEO_EVENT_IMPORTED = 1 << 1,
    GEO_EVENT_STATIONARY = 1 << 2,
    GEO_EVENT_LOW_ACCURACY = 1 << 3,
    GEO_EVENT_OFFLINE = 1 << 4,
    GEO_EVENT_DELETED = 1 << 5,
} GEO_EVENT_FLAGS;

typedef struct geo_event_t {
    tb_uint128_t id;
    tb_uint128_t entity_id;
    tb_uint128_t correlation_id;
    tb_uint128_t user_data;
    int64_t lat_nano;
    int64_t lon_nano;
    uint64_t group_id;
    uint64_t timestamp;
    int32_t altitude_mm;
    uint32_t velocity_mms;
    uint32_t ttl_seconds;
    uint32_t accuracy_mm;
    uint16_t heading_cdeg;
    uint16_t flags;
    uint8_t reserved[12];
} geo_event_t;

typedef enum INSERT_GEO_EVENT_RESULT {
    INSERT_GEO_EVENT_OK = 0,
    INSERT_GEO_EVENT_LINKED_EVENT_FAILED = 1,
    INSERT_GEO_EVENT_LINKED_EVENT_CHAIN_OPEN = 2,
    INSERT_GEO_EVENT_TIMESTAMP_MUST_BE_ZERO = 3,
    INSERT_GEO_EVENT_RESERVED_FIELD = 4,
    INSERT_GEO_EVENT_RESERVED_FLAG = 5,
    INSERT_GEO_EVENT_ID_MUST_NOT_BE_ZERO = 6,
    INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_ZERO = 7,
    INSERT_GEO_EVENT_INVALID_COORDINATES = 8,
    INSERT_GEO_EVENT_LAT_OUT_OF_RANGE = 9,
    INSERT_GEO_EVENT_LON_OUT_OF_RANGE = 10,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_ENTITY_ID = 11,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_COORDINATES = 12,
    INSERT_GEO_EVENT_EXISTS = 13,
    INSERT_GEO_EVENT_HEADING_OUT_OF_RANGE = 14,
    INSERT_GEO_EVENT_TTL_INVALID = 15,
} INSERT_GEO_EVENT_RESULT;

typedef struct insert_geo_events_result_t {
    uint32_t index;
    uint32_t result;
} insert_geo_events_result_t;

typedef struct delete_entities_result_t {
    uint32_t index;
    uint32_t result;
} delete_entities_result_t;

typedef struct query_uuid_filter_t {
    tb_uint128_t entity_id;
    uint32_t limit;
    uint8_t reserved[108];
} query_uuid_filter_t;

typedef struct query_radius_filter_t {
    int64_t center_lat_nano;
    int64_t center_lon_nano;
    uint32_t radius_mm;
    uint32_t limit;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[80];
} query_radius_filter_t;

typedef struct query_polygon_filter_t {
    uint32_t vertex_count;
    uint32_t limit;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[96];
} query_polygon_filter_t;

typedef struct query_latest_filter_t {
    uint32_t limit;
    uint32_t _reserved_align;
    uint64_t group_id;
    uint64_t cursor_timestamp;
    uint8_t reserved[104];
} query_latest_filter_t;

typedef struct query_response_t {
    uint32_t count;
    uint8_t has_more;
    uint8_t partial_result;
    uint8_t reserved[10];
} query_response_t;

typedef struct polygon_vertex_t {
    int64_t lat_nano;
    int64_t lon_nano;
} polygon_vertex_t;

// Opaque struct serving as a handle for the client instance.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the client instance.
typedef struct tb_client_t {
    uint64_t opaque[4];
} tb_client_t;

// Struct containing the state of a request submitted through the client.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the request.
typedef struct tb_packet_t {
    void* user_data;
    void* data;
    uint32_t data_size;
    uint16_t user_tag;
    uint8_t operation;
    uint8_t status;
    uint8_t opaque[64];
} tb_packet_t;

typedef enum TB_OPERATION {
    TB_OPERATION_PULSE = 128,
    TB_OPERATION_GET_CHANGE_EVENTS = 137,
    TB_OPERATION_CREATE_ACCOUNTS = 138,
    TB_OPERATION_CREATE_TRANSFERS = 139,
    TB_OPERATION_LOOKUP_ACCOUNTS = 140,
    TB_OPERATION_LOOKUP_TRANSFERS = 141,
    TB_OPERATION_GET_ACCOUNT_TRANSFERS = 142,
    TB_OPERATION_GET_ACCOUNT_BALANCES = 143,
    TB_OPERATION_QUERY_ACCOUNTS = 144,
    TB_OPERATION_QUERY_TRANSFERS = 145,
    TB_OPERATION_INSERT_EVENTS = 146,
    TB_OPERATION_UPSERT_EVENTS = 147,
    TB_OPERATION_DELETE_ENTITIES = 148,
    TB_OPERATION_QUERY_UUID = 149,
    TB_OPERATION_QUERY_RADIUS = 150,
    TB_OPERATION_QUERY_POLYGON = 151,
    TB_OPERATION_QUERY_LATEST = 154,
    TB_OPERATION_ARCHERDB_PING = 152,
    TB_OPERATION_ARCHERDB_GET_STATUS = 153,
    TB_OPERATION_CLEANUP_EXPIRED = 155,
} TB_OPERATION;

typedef enum TB_PACKET_STATUS {
    TB_PACKET_OK = 0,
    TB_PACKET_TOO_MUCH_DATA = 1,
    TB_PACKET_CLIENT_EVICTED = 2,
    TB_PACKET_CLIENT_RELEASE_TOO_LOW = 3,
    TB_PACKET_CLIENT_RELEASE_TOO_HIGH = 4,
    TB_PACKET_CLIENT_SHUTDOWN = 5,
    TB_PACKET_INVALID_OPERATION = 6,
    TB_PACKET_INVALID_DATA_SIZE = 7,
} TB_PACKET_STATUS;

typedef enum TB_INIT_STATUS {
    TB_INIT_SUCCESS = 0,
    TB_INIT_UNEXPECTED = 1,
    TB_INIT_OUT_OF_MEMORY = 2,
    TB_INIT_ADDRESS_INVALID = 3,
    TB_INIT_ADDRESS_LIMIT_EXCEEDED = 4,
    TB_INIT_SYSTEM_RESOURCES = 5,
    TB_INIT_NETWORK_SUBSYSTEM = 6,
} TB_INIT_STATUS;

typedef enum TB_CLIENT_STATUS {
    TB_CLIENT_OK = 0,
    TB_CLIENT_INVALID = 1,
} TB_CLIENT_STATUS;

typedef enum TB_REGISTER_LOG_CALLBACK_STATUS {
    TB_REGISTER_LOG_CALLBACK_SUCCESS = 0,
    TB_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED = 1,
    TB_REGISTER_LOG_CALLBACK_NOT_REGISTERED = 2,
} TB_REGISTER_LOG_CALLBACK_STATUS;

typedef enum TB_LOG_LEVEL {
    TB_LOG_ERR = 0,
    TB_LOG_WARN = 1,
    TB_LOG_INFO = 2,
    TB_LOG_DEBUG = 3,
} TB_LOG_LEVEL;

typedef struct tb_init_parameters_t {
    tb_uint128_t cluster_id;
    tb_uint128_t client_id;
    uint8_t* addresses_ptr;
    uint64_t addresses_len;
} tb_init_parameters_t;

// Initialize a new TigerBeetle client which connects to the addresses provided and
// completes submitted packets by invoking the callback with the given context.
TB_INIT_STATUS tb_client_init(
    tb_client_t *client_out,
    // 128-bit unsigned integer represented as a 16-byte little-endian array.
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, tb_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

// Initialize a new TigerBeetle client that echoes back any submitted data.
TB_INIT_STATUS tb_client_init_echo(
    tb_client_t *client_out,
    // 128-bit unsigned integer represented as a 16-byte little-endian array.
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, tb_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

// Retrieve the parameters initially passed to `tb_client_init` or `tb_client_init_echo`.
// Return value: `TB_CLIENT_OK` on success, or `TB_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
TB_CLIENT_STATUS tb_client_init_parameters(
    tb_client_t* client,
    tb_init_parameters_t* init_parameters_out
);

// Retrieve the callback context initially passed to `tb_client_init` or `tb_client_init_echo`.
// Return value: `TB_CLIENT_OK` on success, or `TB_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
TB_CLIENT_STATUS tb_client_completion_context(
    tb_client_t* client,
    uintptr_t* completion_ctx_out
);

// Submit a packet with its `operation`, `data`, and `data_size` fields set.
// Once completed, `completion_callback` will be invoked with `completion_ctx`
// and the given packet on the `tb_client` thread (separate from the caller's thread).
// Return value: `TB_CLIENT_OK` on success, or `TB_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
TB_CLIENT_STATUS tb_client_submit(
    tb_client_t *client,
    tb_packet_t *packet
);

// Closes the client, causing any previously submitted packets to be completed with
// `TB_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
// Return value: `TB_CLIENT_OK` on success, or `TB_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
TB_CLIENT_STATUS tb_client_deinit(
    tb_client_t *client
);

// Registers or unregisters the application log callback.
TB_REGISTER_LOG_CALLBACK_STATUS tb_client_register_log_callback(
    void (*callback)(TB_LOG_LEVEL, const uint8_t*, uint32_t),
    bool debug
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // TB_CLIENT_H
