// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2025 ArcherDB Contributors

///////////////////////////////////////////////////////
// This file was auto-generated by go_bindings.zig   //
//              Do not manually modify.              //
///////////////////////////////////////////////////////

package types

/*
#include "../native/arch_client.h"
*/
import "C"
import "strconv"

type GeoEventFlagsRaw struct {
	Linked      bool
	Imported    bool
	Stationary  bool
	LowAccuracy bool
	Offline     bool
	Deleted     bool
}

func (f GeoEventFlagsRaw) ToUint16() uint16 {
	var ret uint16 = 0

	if f.Linked {
		ret |= (1 << 0)
	}

	if f.Imported {
		ret |= (1 << 1)
	}

	if f.Stationary {
		ret |= (1 << 2)
	}

	if f.LowAccuracy {
		ret |= (1 << 3)
	}

	if f.Offline {
		ret |= (1 << 4)
	}

	if f.Deleted {
		ret |= (1 << 5)
	}

	return ret
}

type GeoEventRaw struct {
	ID            Uint128
	EntityID      Uint128
	CorrelationID Uint128
	UserData      Uint128
	LatNano       int64
	LonNano       int64
	GroupID       uint64
	Timestamp     uint64
	AltitudeMm    int32
	VelocityMms   uint32
	TtlSeconds    uint32
	AccuracyMm    uint32
	HeadingCdeg   uint16
	Flags         uint16
	Reserved      [12]uint8
}

func (o GeoEventRaw) GetFlags() GeoEventFlagsRaw {
	var f GeoEventFlagsRaw
	f.Linked = ((o.Flags >> 0) & 0x1) == 1
	f.Imported = ((o.Flags >> 1) & 0x1) == 1
	f.Stationary = ((o.Flags >> 2) & 0x1) == 1
	f.LowAccuracy = ((o.Flags >> 3) & 0x1) == 1
	f.Offline = ((o.Flags >> 4) & 0x1) == 1
	f.Deleted = ((o.Flags >> 5) & 0x1) == 1
	return f
}

type InsertGeoEventResultRaw uint32

const (
	GeoEventOK                             InsertGeoEventResultRaw = 0
	GeoEventLinkedEventFailed              InsertGeoEventResultRaw = 1
	GeoEventLinkedEventChainOpen           InsertGeoEventResultRaw = 2
	GeoEventTimestampMustBeZero            InsertGeoEventResultRaw = 3
	GeoEventReservedField                  InsertGeoEventResultRaw = 4
	GeoEventReservedFlag                   InsertGeoEventResultRaw = 5
	GeoEventIDMustNotBeZero                InsertGeoEventResultRaw = 6
	GeoEventEntityIDMustNotBeZero          InsertGeoEventResultRaw = 7
	GeoEventInvalidCoordinates             InsertGeoEventResultRaw = 8
	GeoEventLatOutOfRange                  InsertGeoEventResultRaw = 9
	GeoEventLonOutOfRange                  InsertGeoEventResultRaw = 10
	GeoEventExistsWithDifferentEntityID    InsertGeoEventResultRaw = 11
	GeoEventExistsWithDifferentCoordinates InsertGeoEventResultRaw = 12
	GeoEventExists                         InsertGeoEventResultRaw = 13
	GeoEventHeadingOutOfRange              InsertGeoEventResultRaw = 14
	GeoEventTtlInvalid                     InsertGeoEventResultRaw = 15
	GeoEventEntityIDMustNotBeIntMax        InsertGeoEventResultRaw = 16
)

func (i InsertGeoEventResultRaw) String() string {
	switch i {
	case GeoEventOK:
		return "GeoEventOK"
	case GeoEventLinkedEventFailed:
		return "GeoEventLinkedEventFailed"
	case GeoEventLinkedEventChainOpen:
		return "GeoEventLinkedEventChainOpen"
	case GeoEventTimestampMustBeZero:
		return "GeoEventTimestampMustBeZero"
	case GeoEventReservedField:
		return "GeoEventReservedField"
	case GeoEventReservedFlag:
		return "GeoEventReservedFlag"
	case GeoEventIDMustNotBeZero:
		return "GeoEventIDMustNotBeZero"
	case GeoEventEntityIDMustNotBeZero:
		return "GeoEventEntityIDMustNotBeZero"
	case GeoEventInvalidCoordinates:
		return "GeoEventInvalidCoordinates"
	case GeoEventLatOutOfRange:
		return "GeoEventLatOutOfRange"
	case GeoEventLonOutOfRange:
		return "GeoEventLonOutOfRange"
	case GeoEventExistsWithDifferentEntityID:
		return "GeoEventExistsWithDifferentEntityID"
	case GeoEventExistsWithDifferentCoordinates:
		return "GeoEventExistsWithDifferentCoordinates"
	case GeoEventExists:
		return "GeoEventExists"
	case GeoEventHeadingOutOfRange:
		return "GeoEventHeadingOutOfRange"
	case GeoEventTtlInvalid:
		return "GeoEventTtlInvalid"
	case GeoEventEntityIDMustNotBeIntMax:
		return "GeoEventEntityIDMustNotBeIntMax"
	}
	return "InsertGeoEventResultRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type DeleteEntityResultRaw uint32

const (
	EntityOK                      DeleteEntityResultRaw = 0
	EntityLinkedEventFailed       DeleteEntityResultRaw = 1
	EntityEntityIDMustNotBeZero   DeleteEntityResultRaw = 2
	EntityEntityNotFound          DeleteEntityResultRaw = 3
	EntityEntityIDMustNotBeIntMax DeleteEntityResultRaw = 4
)

func (i DeleteEntityResultRaw) String() string {
	switch i {
	case EntityOK:
		return "EntityOK"
	case EntityLinkedEventFailed:
		return "EntityLinkedEventFailed"
	case EntityEntityIDMustNotBeZero:
		return "EntityEntityIDMustNotBeZero"
	case EntityEntityNotFound:
		return "EntityEntityNotFound"
	case EntityEntityIDMustNotBeIntMax:
		return "EntityEntityIDMustNotBeIntMax"
	}
	return "DeleteEntityResultRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type InsertGeoEventsResultRaw struct {
	Index  uint32
	Result InsertGeoEventResultRaw
}

type DeleteEntitiesResultRaw struct {
	Index  uint32
	Result DeleteEntityResultRaw
}

type QueryUuidFilterRaw struct {
	EntityID Uint128
	Reserved [16]uint8
}

type QueryUuidResponseRaw struct {
	Status   uint8
	Reserved [15]uint8
}

type QueryUuidBatchFilterRaw struct {
	Count    uint32
	Reserved [12]uint8
}

type QueryUuidBatchResultRaw struct {
	FoundCount    uint32
	NotFoundCount uint32
	Reserved      [8]uint8
}

type QueryRadiusFilterRaw struct {
	CenterLatNano int64
	CenterLonNano int64
	RadiusMm      uint32
	Limit         uint32
	TimestampMin  uint64
	TimestampMax  uint64
	GroupID       uint64
	Reserved      [80]uint8
}

type QueryPolygonFilterRaw struct {
	VertexCount   uint32
	HoleCount     uint32
	Limit         uint32
	ReservedAlign uint32
	TimestampMin  uint64
	TimestampMax  uint64
	GroupID       uint64
	Reserved      [88]uint8
}

type QueryLatestFilterRaw struct {
	Limit           uint32
	ReservedAlign   uint32
	GroupID         uint64
	CursorTimestamp uint64
	Reserved        [104]uint8
}

type QueryResponseRaw struct {
	Count         uint32
	HasMore       uint8
	PartialResult uint8
	Reserved      [10]uint8
}

type PolygonVertexRaw struct {
	LatNano int64
	LonNano int64
}

type HoleDescriptorRaw struct {
	VertexCount uint32
	Reserved    uint32
}

type PingRequestRaw struct {
	PingData uint64
}

type StatusRequestRaw struct {
	Reserved uint64
}

type PingResponseRaw struct {
	Pong uint32
}

type StatusResponseRaw struct {
	RamIndexCount           uint64
	RamIndexCapacity        uint64
	RamIndexLoadPct         uint32
	Padding                 uint32
	TombstoneCount          uint64
	TtlExpirations          uint64
	DeletionCount           uint64
	IndexResizeStatus       uint8
	MembershipState         uint8
	StatusPadding           uint16
	IndexResizeProgress     uint32
	MembershipVotersCount   uint32
	MembershipLearnersCount uint32
}

type TopologyRequestRaw struct {
	Reserved uint64
}

type TopologyResponseRaw struct {
	Version          uint64
	NumShards        uint32
	ClusterID        Uint128
	LastChangeNs     Int128
	ReshardingStatus uint8
	Flags            uint8
	Padding          [6]uint8
	Shards           [256]ShardInfoRaw
}

type ShardInfoRaw struct {
	ID           uint32
	Primary      [64]uint8
	Replicas     [6][64]uint8
	ReplicaCount uint8
	Status       ShardStatusRaw
	EntityCount  uint64
	SizeBytes    uint64
}

type ShardStatusRaw uint8

const (
	ShardStatusRawActive          ShardStatusRaw = 0
	ShardStatusRawSyncing         ShardStatusRaw = 1
	ShardStatusRawUnavailable     ShardStatusRaw = 2
	ShardStatusRawMigrating       ShardStatusRaw = 3
	ShardStatusRawDecommissioning ShardStatusRaw = 4
)

func (i ShardStatusRaw) String() string {
	switch i {
	case ShardStatusRawActive:
		return "ShardStatusRawActive"
	case ShardStatusRawSyncing:
		return "ShardStatusRawSyncing"
	case ShardStatusRawUnavailable:
		return "ShardStatusRawUnavailable"
	case ShardStatusRawMigrating:
		return "ShardStatusRawMigrating"
	case ShardStatusRawDecommissioning:
		return "ShardStatusRawDecommissioning"
	}
	return "ShardStatusRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type TtlOperationResultRaw uint8

const (
	TtlSuccess         TtlOperationResultRaw = 0
	TtlEntityNotFound  TtlOperationResultRaw = 1
	TtlInvalidTtl      TtlOperationResultRaw = 2
	TtlNotPermitted    TtlOperationResultRaw = 3
	TtlEntityImmutable TtlOperationResultRaw = 4
)

func (i TtlOperationResultRaw) String() string {
	switch i {
	case TtlSuccess:
		return "TtlSuccess"
	case TtlEntityNotFound:
		return "TtlEntityNotFound"
	case TtlInvalidTtl:
		return "TtlInvalidTtl"
	case TtlNotPermitted:
		return "TtlNotPermitted"
	case TtlEntityImmutable:
		return "TtlEntityImmutable"
	}
	return "TtlOperationResultRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type TtlSetRequestRaw struct {
	EntityID   Uint128
	TtlSeconds uint32
	Flags      uint32
	Reserved   [40]uint8
}

type TtlSetResponseRaw struct {
	EntityID           Uint128
	PreviousTtlSeconds uint32
	NewTtlSeconds      uint32
	Result             TtlOperationResultRaw
	Padding            [3]uint8
	Reserved           [32]uint8
}

type TtlExtendRequestRaw struct {
	EntityID        Uint128
	ExtendBySeconds uint32
	Flags           uint32
	Reserved        [40]uint8
}

type TtlExtendResponseRaw struct {
	EntityID           Uint128
	PreviousTtlSeconds uint32
	NewTtlSeconds      uint32
	Result             TtlOperationResultRaw
	Padding            [3]uint8
	Reserved           [32]uint8
}

type TtlClearRequestRaw struct {
	EntityID Uint128
	Flags    uint32
	Reserved [44]uint8
}

type TtlClearResponseRaw struct {
	EntityID           Uint128
	PreviousTtlSeconds uint32
	Result             TtlOperationResultRaw
	Padding            [3]uint8
	Reserved           [36]uint8
}
