///////////////////////////////////////////////////////
// This file was auto-generated by go_bindings.zig   //
//              Do not manually modify.              //
///////////////////////////////////////////////////////

package types

/*
#include "../native/arch_client.h"
*/
import "C"
import "strconv"

type GeoEventFlagsRaw struct {
	Linked      bool
	Imported    bool
	Stationary  bool
	LowAccuracy bool
	Offline     bool
	Deleted     bool
}

func (f GeoEventFlagsRaw) ToUint16() uint16 {
	var ret uint16 = 0

	if f.Linked {
		ret |= (1 << 0)
	}

	if f.Imported {
		ret |= (1 << 1)
	}

	if f.Stationary {
		ret |= (1 << 2)
	}

	if f.LowAccuracy {
		ret |= (1 << 3)
	}

	if f.Offline {
		ret |= (1 << 4)
	}

	if f.Deleted {
		ret |= (1 << 5)
	}

	return ret
}

type GeoEventRaw struct {
	ID            Uint128
	EntityID      Uint128
	CorrelationID Uint128
	UserData      Uint128
	LatNano       int64
	LonNano       int64
	GroupID       uint64
	Timestamp     uint64
	AltitudeMm    int32
	VelocityMms   uint32
	TtlSeconds    uint32
	AccuracyMm    uint32
	HeadingCdeg   uint16
	Flags         uint16
	Reserved      [12]uint8
}

func (o GeoEventRaw) GetFlags() GeoEventFlagsRaw {
	var f GeoEventFlagsRaw
	f.Linked = ((o.Flags >> 0) & 0x1) == 1
	f.Imported = ((o.Flags >> 1) & 0x1) == 1
	f.Stationary = ((o.Flags >> 2) & 0x1) == 1
	f.LowAccuracy = ((o.Flags >> 3) & 0x1) == 1
	f.Offline = ((o.Flags >> 4) & 0x1) == 1
	f.Deleted = ((o.Flags >> 5) & 0x1) == 1
	return f
}

type InsertGeoEventResultRaw uint32

const (
	GeoEventOK                             InsertGeoEventResultRaw = 0
	GeoEventLinkedEventFailed              InsertGeoEventResultRaw = 1
	GeoEventLinkedEventChainOpen           InsertGeoEventResultRaw = 2
	GeoEventTimestampMustBeZero            InsertGeoEventResultRaw = 3
	GeoEventReservedField                  InsertGeoEventResultRaw = 4
	GeoEventReservedFlag                   InsertGeoEventResultRaw = 5
	GeoEventIDMustNotBeZero                InsertGeoEventResultRaw = 6
	GeoEventEntityIDMustNotBeZero          InsertGeoEventResultRaw = 7
	GeoEventInvalidCoordinates             InsertGeoEventResultRaw = 8
	GeoEventLatOutOfRange                  InsertGeoEventResultRaw = 9
	GeoEventLonOutOfRange                  InsertGeoEventResultRaw = 10
	GeoEventExistsWithDifferentEntityID    InsertGeoEventResultRaw = 11
	GeoEventExistsWithDifferentCoordinates InsertGeoEventResultRaw = 12
	GeoEventExists                         InsertGeoEventResultRaw = 13
	GeoEventHeadingOutOfRange              InsertGeoEventResultRaw = 14
	GeoEventTtlInvalid                     InsertGeoEventResultRaw = 15
	GeoEventEntityIDMustNotBeIntMax        InsertGeoEventResultRaw = 16
)

func (i InsertGeoEventResultRaw) String() string {
	switch i {
	case GeoEventOK:
		return "GeoEventOK"
	case GeoEventLinkedEventFailed:
		return "GeoEventLinkedEventFailed"
	case GeoEventLinkedEventChainOpen:
		return "GeoEventLinkedEventChainOpen"
	case GeoEventTimestampMustBeZero:
		return "GeoEventTimestampMustBeZero"
	case GeoEventReservedField:
		return "GeoEventReservedField"
	case GeoEventReservedFlag:
		return "GeoEventReservedFlag"
	case GeoEventIDMustNotBeZero:
		return "GeoEventIDMustNotBeZero"
	case GeoEventEntityIDMustNotBeZero:
		return "GeoEventEntityIDMustNotBeZero"
	case GeoEventInvalidCoordinates:
		return "GeoEventInvalidCoordinates"
	case GeoEventLatOutOfRange:
		return "GeoEventLatOutOfRange"
	case GeoEventLonOutOfRange:
		return "GeoEventLonOutOfRange"
	case GeoEventExistsWithDifferentEntityID:
		return "GeoEventExistsWithDifferentEntityID"
	case GeoEventExistsWithDifferentCoordinates:
		return "GeoEventExistsWithDifferentCoordinates"
	case GeoEventExists:
		return "GeoEventExists"
	case GeoEventHeadingOutOfRange:
		return "GeoEventHeadingOutOfRange"
	case GeoEventTtlInvalid:
		return "GeoEventTtlInvalid"
	case GeoEventEntityIDMustNotBeIntMax:
		return "GeoEventEntityIDMustNotBeIntMax"
	}
	return "InsertGeoEventResultRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type DeleteEntityResultRaw uint32

const (
	EntityOK                      DeleteEntityResultRaw = 0
	EntityLinkedEventFailed       DeleteEntityResultRaw = 1
	EntityEntityIDMustNotBeZero   DeleteEntityResultRaw = 2
	EntityEntityNotFound          DeleteEntityResultRaw = 3
	EntityEntityIDMustNotBeIntMax DeleteEntityResultRaw = 4
)

func (i DeleteEntityResultRaw) String() string {
	switch i {
	case EntityOK:
		return "EntityOK"
	case EntityLinkedEventFailed:
		return "EntityLinkedEventFailed"
	case EntityEntityIDMustNotBeZero:
		return "EntityEntityIDMustNotBeZero"
	case EntityEntityNotFound:
		return "EntityEntityNotFound"
	case EntityEntityIDMustNotBeIntMax:
		return "EntityEntityIDMustNotBeIntMax"
	}
	return "DeleteEntityResultRaw(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type InsertGeoEventsResultRaw struct {
	Index  uint32
	Result InsertGeoEventResultRaw
}

type DeleteEntitiesResultRaw struct {
	Index  uint32
	Result DeleteEntityResultRaw
}

type QueryUuidFilterRaw struct {
	EntityID Uint128
	Reserved [16]uint8
}

type QueryResponseRaw struct {
	Count         uint32
	HasMore       uint8
	PartialResult uint8
	Reserved      [10]uint8
}
