 //////////////////////////////////////////////////////////
 // This file was auto-generated by arch_client_header.zig //
 //              Do not manually modify.                 //
 //////////////////////////////////////////////////////////

#ifndef ARCH_CLIENT_H
#define ARCH_CLIENT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef __uint128_t arch_uint128_t;
typedef __int128_t arch_int128_t;

typedef enum GEO_EVENT_FLAGS {
    GEO_EVENT_LINKED = 1 << 0,
    GEO_EVENT_IMPORTED = 1 << 1,
    GEO_EVENT_STATIONARY = 1 << 2,
    GEO_EVENT_LOW_ACCURACY = 1 << 3,
    GEO_EVENT_OFFLINE = 1 << 4,
    GEO_EVENT_DELETED = 1 << 5,
} GEO_EVENT_FLAGS;

typedef struct geo_event_t {
    arch_uint128_t id;
    arch_uint128_t entity_id;
    arch_uint128_t correlation_id;
    arch_uint128_t user_data;
    int64_t lat_nano;
    int64_t lon_nano;
    uint64_t group_id;
    uint64_t timestamp;
    int32_t altitude_mm;
    uint32_t velocity_mms;
    uint32_t ttl_seconds;
    uint32_t accuracy_mm;
    uint16_t heading_cdeg;
    GEO_EVENT_FLAGS flags;
    uint8_t reserved[12];
} geo_event_t;

typedef enum INSERT_GEO_EVENT_RESULT {
    INSERT_GEO_EVENT_OK = 0,
    INSERT_GEO_EVENT_LINKED_EVENT_FAILED = 1,
    INSERT_GEO_EVENT_LINKED_EVENT_CHAIN_OPEN = 2,
    INSERT_GEO_EVENT_TIMESTAMP_MUST_BE_ZERO = 3,
    INSERT_GEO_EVENT_RESERVED_FIELD = 4,
    INSERT_GEO_EVENT_RESERVED_FLAG = 5,
    INSERT_GEO_EVENT_ID_MUST_NOT_BE_ZERO = 6,
    INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_ZERO = 7,
    INSERT_GEO_EVENT_INVALID_COORDINATES = 8,
    INSERT_GEO_EVENT_LAT_OUT_OF_RANGE = 9,
    INSERT_GEO_EVENT_LON_OUT_OF_RANGE = 10,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_ENTITY_ID = 11,
    INSERT_GEO_EVENT_EXISTS_WITH_DIFFERENT_COORDINATES = 12,
    INSERT_GEO_EVENT_EXISTS = 13,
    INSERT_GEO_EVENT_HEADING_OUT_OF_RANGE = 14,
    INSERT_GEO_EVENT_TTL_INVALID = 15,
    INSERT_GEO_EVENT_ENTITY_ID_MUST_NOT_BE_INT_MAX = 16,
} INSERT_GEO_EVENT_RESULT;

typedef struct insert_geo_events_result_t {
    uint32_t index;
    uint32_t result;
} insert_geo_events_result_t;

typedef struct delete_entities_result_t {
    uint32_t index;
    uint32_t result;
} delete_entities_result_t;

typedef struct query_uuid_filter_t {
    arch_uint128_t entity_id;
    uint8_t reserved[16];
} query_uuid_filter_t;

typedef struct query_uuid_response_t {
    uint8_t status;
    uint8_t reserved[15];
} query_uuid_response_t;

typedef struct query_uuid_batch_filter_t {
    uint32_t count;
    uint32_t reserved;
} query_uuid_batch_filter_t;

typedef struct query_uuid_batch_result_t {
    uint32_t found_count;
    uint32_t not_found_count;
    uint8_t reserved[8];
} query_uuid_batch_result_t;

typedef struct query_radius_filter_t {
    int64_t center_lat_nano;
    int64_t center_lon_nano;
    uint32_t radius_mm;
    uint32_t limit;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[80];
} query_radius_filter_t;

typedef struct query_polygon_filter_t {
    uint32_t vertex_count;
    uint32_t hole_count;
    uint32_t limit;
    uint32_t _reserved_align;
    uint64_t timestamp_min;
    uint64_t timestamp_max;
    uint64_t group_id;
    uint8_t reserved[88];
} query_polygon_filter_t;

typedef struct query_latest_filter_t {
    uint32_t limit;
    uint32_t _reserved_align;
    uint64_t group_id;
    uint64_t cursor_timestamp;
    uint8_t reserved[104];
} query_latest_filter_t;

typedef struct query_response_t {
    uint32_t count;
    uint8_t has_more;
    uint8_t partial_result;
    uint8_t reserved[10];
} query_response_t;

typedef struct polygon_vertex_t {
    int64_t lat_nano;
    int64_t lon_nano;
} polygon_vertex_t;

typedef struct hole_descriptor_t {
    uint32_t vertex_count;
    uint32_t reserved;
} hole_descriptor_t;

typedef struct ping_request_t {
    uint64_t ping_data;
} ping_request_t;

typedef struct status_request_t {
    uint64_t reserved;
} status_request_t;

typedef struct ping_response_t {
    uint32_t pong;
} ping_response_t;

typedef struct status_response_t {
    uint64_t ram_index_count;
    uint64_t ram_index_capacity;
    uint32_t ram_index_load_pct;
    uint32_t _padding;
    uint64_t tombstone_count;
    uint64_t ttl_expirations;
    uint64_t deletion_count;
    uint8_t reserved[16];
} status_response_t;

typedef struct topology_request_t {
    uint64_t reserved;
} topology_request_t;

typedef struct shard_info_t {
    uint32_t id;
    uint8_t primary[64];
    uint8_t replicas[6];
    uint8_t replica_count;
    uint8_t status;
    uint64_t entity_count;
    uint64_t size_bytes;
} shard_info_t;

typedef enum SHARD_STATUS {
    SHARD_STATUS_ACTIVE = 0,
    SHARD_STATUS_SYNCING = 1,
    SHARD_STATUS_UNAVAILABLE = 2,
    SHARD_STATUS_MIGRATING = 3,
    SHARD_STATUS_DECOMMISSIONING = 4,
} SHARD_STATUS;

typedef struct topology_response_t {
    uint64_t version;
    uint32_t num_shards;
    arch_uint128_t cluster_id;
    arch_int128_t last_change_ns;
    uint8_t resharding_status;
    uint8_t flags;
    uint8_t _padding[6];
    shard_info_t shards[256];
} topology_response_t;

typedef enum TTL_OPERATION_RESULT {
    TTL_OPERATION_SUCCESS = 0,
    TTL_OPERATION_ENTITY_NOT_FOUND = 1,
    TTL_OPERATION_INVALID_TTL = 2,
    TTL_OPERATION_NOT_PERMITTED = 3,
    TTL_OPERATION_ENTITY_IMMUTABLE = 4,
} TTL_OPERATION_RESULT;

typedef struct ttl_set_request_t {
    arch_uint128_t entity_id;
    uint32_t ttl_seconds;
    uint32_t flags;
    uint8_t reserved[40];
} ttl_set_request_t;

typedef struct ttl_set_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint32_t new_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[32];
} ttl_set_response_t;

typedef struct ttl_extend_request_t {
    arch_uint128_t entity_id;
    uint32_t extend_by_seconds;
    uint32_t flags;
    uint8_t reserved[40];
} ttl_extend_request_t;

typedef struct ttl_extend_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint32_t new_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[32];
} ttl_extend_response_t;

typedef struct ttl_clear_request_t {
    arch_uint128_t entity_id;
    uint32_t flags;
    uint8_t reserved[44];
} ttl_clear_request_t;

typedef struct ttl_clear_response_t {
    arch_uint128_t entity_id;
    uint32_t previous_ttl_seconds;
    uint8_t result;
    uint8_t _padding[3];
    uint8_t reserved[36];
} ttl_clear_response_t;

// Opaque struct serving as a handle for the client instance.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the client instance.
typedef struct arch_client_t {
    uint64_t opaque[4];
} arch_client_t;

// Struct containing the state of a request submitted through the client.
// This struct must be "pinned" (not copyable or movable), as its address must remain stable
// throughout the lifetime of the request.
typedef struct arch_packet_t {
    void* user_data;
    void* data;
    uint32_t data_size;
    uint16_t user_tag;
    uint8_t operation;
    uint8_t status;
    uint8_t opaque[64];
} arch_packet_t;

typedef enum ARCH_OPERATION {
    ARCH_OPERATION_PULSE = 128,
    ARCH_OPERATION_INSERT_EVENTS = 146,
    ARCH_OPERATION_UPSERT_EVENTS = 147,
    ARCH_OPERATION_DELETE_ENTITIES = 148,
    ARCH_OPERATION_QUERY_UUID = 149,
    ARCH_OPERATION_QUERY_RADIUS = 150,
    ARCH_OPERATION_QUERY_POLYGON = 151,
    ARCH_OPERATION_QUERY_LATEST = 154,
    ARCH_OPERATION_QUERY_UUID_BATCH = 156,
    ARCH_OPERATION_ARCHERDB_PING = 152,
    ARCH_OPERATION_ARCHERDB_GET_STATUS = 153,
    ARCH_OPERATION_CLEANUP_EXPIRED = 155,
    ARCH_OPERATION_GET_TOPOLOGY = 157,
    ARCH_OPERATION_TTL_SET = 158,
    ARCH_OPERATION_TTL_EXTEND = 159,
    ARCH_OPERATION_TTL_CLEAR = 160,
} ARCH_OPERATION;

typedef enum ARCH_PACKET_STATUS {
    ARCH_PACKET_OK = 0,
    ARCH_PACKET_TOO_MUCH_DATA = 1,
    ARCH_PACKET_CLIENT_EVICTED = 2,
    ARCH_PACKET_CLIENT_RELEASE_TOO_LOW = 3,
    ARCH_PACKET_CLIENT_RELEASE_TOO_HIGH = 4,
    ARCH_PACKET_CLIENT_SHUTDOWN = 5,
    ARCH_PACKET_INVALID_OPERATION = 6,
    ARCH_PACKET_INVALID_DATA_SIZE = 7,
} ARCH_PACKET_STATUS;

typedef enum ARCH_INIT_STATUS {
    ARCH_INIT_SUCCESS = 0,
    ARCH_INIT_UNEXPECTED = 1,
    ARCH_INIT_OUT_OF_MEMORY = 2,
    ARCH_INIT_ADDRESS_INVALID = 3,
    ARCH_INIT_ADDRESS_LIMIT_EXCEEDED = 4,
    ARCH_INIT_SYSTEM_RESOURCES = 5,
    ARCH_INIT_NETWORK_SUBSYSTEM = 6,
} ARCH_INIT_STATUS;

typedef enum ARCH_CLIENT_STATUS {
    ARCH_CLIENT_OK = 0,
    ARCH_CLIENT_INVALID = 1,
} ARCH_CLIENT_STATUS;

typedef enum ARCH_REGISTER_LOG_CALLBACK_STATUS {
    ARCH_REGISTER_LOG_CALLBACK_SUCCESS = 0,
    ARCH_REGISTER_LOG_CALLBACK_ALREADY_REGISTERED = 1,
    ARCH_REGISTER_LOG_CALLBACK_NOT_REGISTERED = 2,
} ARCH_REGISTER_LOG_CALLBACK_STATUS;

typedef enum ARCH_LOG_LEVEL {
    ARCH_LOG_ERR = 0,
    ARCH_LOG_WARN = 1,
    ARCH_LOG_INFO = 2,
    ARCH_LOG_DEBUG = 3,
} ARCH_LOG_LEVEL;

typedef struct arch_init_parameters_t {
    arch_uint128_t cluster_id;
    arch_uint128_t client_id;
    uint8_t* addresses_ptr;
    uint64_t addresses_len;
} arch_init_parameters_t;

// Initialize a new ArcherDB client which connects to the addresses provided and
// completes submitted packets by invoking the callback with the given context.
ARCH_INIT_STATUS arch_client_init(
    arch_client_t *client_out,
    // 128-bit unsigned integer represented as a 16-byte little-endian array.
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, arch_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

// Initialize a new ArcherDB client that echoes back any submitted data.
ARCH_INIT_STATUS arch_client_init_echo(
    arch_client_t *client_out,
    // 128-bit unsigned integer represented as a 16-byte little-endian array.
    const uint8_t cluster_id[16],
    const char *address_ptr,
    uint32_t address_len,
    uintptr_t completion_ctx,
    void (*completion_callback)(uintptr_t, arch_packet_t*, uint64_t, const uint8_t*, uint32_t)
);

// Retrieve the parameters initially passed to `arch_client_init` or `arch_client_init_echo`.
// Return value: `ARCH_CLIENT_OK` on success, or `ARCH_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
ARCH_CLIENT_STATUS arch_client_init_parameters(
    arch_client_t* client,
    arch_init_parameters_t* init_parameters_out
);

// Retrieve the callback context initially passed to `arch_client_init` or `arch_client_init_echo`.
// Return value: `ARCH_CLIENT_OK` on success, or `ARCH_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
ARCH_CLIENT_STATUS arch_client_completion_context(
    arch_client_t* client,
    uintptr_t* completion_ctx_out
);

// Submit a packet with its `operation`, `data`, and `data_size` fields set.
// Once completed, `completion_callback` will be invoked with `completion_ctx`
// and the given packet on the `arch_client` thread (separate from the caller's thread).
// Return value: `ARCH_CLIENT_OK` on success, or `ARCH_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
ARCH_CLIENT_STATUS arch_client_submit(
    arch_client_t *client,
    arch_packet_t *packet
);

// Closes the client, causing any previously submitted packets to be completed with
// `ARCH_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
// Return value: `ARCH_CLIENT_OK` on success, or `ARCH_CLIENT_INVALID` if the client handle was
// not initialized or has already been closed.
ARCH_CLIENT_STATUS arch_client_deinit(
    arch_client_t *client
);

// Registers or unregisters the application log callback.
ARCH_REGISTER_LOG_CALLBACK_STATUS arch_client_register_log_callback(
    void (*callback)(ARCH_LOG_LEVEL, const uint8_t*, uint32_t),
    bool debug
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // ARCH_CLIENT_H
