//////////////////////////////////////////////////////////
// This file was auto-generated by dotnet_bindings.zig  //
//              Do not manually modify.                 //
//////////////////////////////////////////////////////////

using System;
using System.Runtime.InteropServices;

namespace ArcherDB;

[Flags]
public enum GeoEventFlags : ushort
{
    None = 0,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagslinked
    /// </summary>
    Linked = 1 << 0,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagsimported
    /// </summary>
    Imported = 1 << 1,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagsstationary
    /// </summary>
    Stationary = 1 << 2,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagslow_accuracy
    /// </summary>
    LowAccuracy = 1 << 3,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagsoffline
    /// </summary>
    Offline = 1 << 4,

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flagsdeleted
    /// </summary>
    Deleted = 1 << 5,

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct GeoEvent
{
    public const int SIZE = 128;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 12;
        private const int LENGTH = 12;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 id;

    private UInt128 entityId;

    private UInt128 correlationId;

    private UInt128 userData;

    private long latNano;

    private long lonNano;

    private ulong groupId;

    private ulong timestamp;

    private int altitudeMm;

    private uint velocityMms;

    private uint ttlSeconds;

    private uint accuracyMm;

    private ushort headingCdeg;

    private GeoEventFlags flags;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#id
    /// </summary>
    public UInt128 Id { get => id; set => id = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#entity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#correlation_id
    /// </summary>
    public UInt128 CorrelationId { get => correlationId; set => correlationId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#user_data
    /// </summary>
    public UInt128 UserData { get => userData; set => userData = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#lat_nano
    /// </summary>
    public long LatNano { get => latNano; set => latNano = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#lon_nano
    /// </summary>
    public long LonNano { get => lonNano; set => lonNano = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#group_id
    /// </summary>
    public ulong GroupId { get => groupId; set => groupId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#timestamp
    /// </summary>
    public ulong Timestamp { get => timestamp; set => timestamp = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#altitude_mm
    /// </summary>
    public int AltitudeMm { get => altitudeMm; set => altitudeMm = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#velocity_mms
    /// </summary>
    public uint VelocityMms { get => velocityMms; set => velocityMms = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#ttl_seconds
    /// </summary>
    public uint TtlSeconds { get => ttlSeconds; set => ttlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#accuracy_mm
    /// </summary>
    public uint AccuracyMm { get => accuracyMm; set => accuracyMm = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#heading_cdeg
    /// </summary>
    public ushort HeadingCdeg { get => headingCdeg; set => headingCdeg = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#flags
    /// </summary>
    public GeoEventFlags Flags { get => flags; set => flags = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/geo-event#reserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

public enum InsertGeoEventResult : uint
{
    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#ok
    /// </summary>
    Ok = 0,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#linked_event_failed
    /// </summary>
    LinkedEventFailed = 1,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#linked_event_chain_open
    /// </summary>
    LinkedEventChainOpen = 2,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#timestamp_must_be_zero
    /// </summary>
    TimestampMustBeZero = 3,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#reserved_field
    /// </summary>
    ReservedField = 4,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#reserved_flag
    /// </summary>
    ReservedFlag = 5,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#id_must_not_be_zero
    /// </summary>
    IdMustNotBeZero = 6,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#entity_id_must_not_be_zero
    /// </summary>
    EntityIdMustNotBeZero = 7,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#invalid_coordinates
    /// </summary>
    InvalidCoordinates = 8,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#lat_out_of_range
    /// </summary>
    LatOutOfRange = 9,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#lon_out_of_range
    /// </summary>
    LonOutOfRange = 10,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#exists_with_different_entity_id
    /// </summary>
    ExistsWithDifferentEntityId = 11,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#exists_with_different_coordinates
    /// </summary>
    ExistsWithDifferentCoordinates = 12,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#exists
    /// </summary>
    Exists = 13,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#heading_out_of_range
    /// </summary>
    HeadingOutOfRange = 14,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#ttl_invalid
    /// </summary>
    TtlInvalid = 15,

    /// <summary>
    /// https://docs.archerdb.io/reference/requests/insert_events#entity_id_must_not_be_int_max
    /// </summary>
    EntityIdMustNotBeIntMax = 16,

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct InsertGeoEventsResult
{
    public const int SIZE = 8;


    private uint index;

    private InsertGeoEventResult result;

    public uint Index { get => index; set => index = value; }

    public InsertGeoEventResult Result { get => result; set => result = value; }

}

public enum DeleteEntityResult : uint
{
    Ok = 0,

    LinkedEventFailed = 1,

    EntityIdMustNotBeZero = 2,

    EntityNotFound = 3,

    EntityIdMustNotBeIntMax = 4,

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct DeleteEntitiesResult
{
    public const int SIZE = 8;


    private uint index;

    private DeleteEntityResult result;

    public uint Index { get => index; set => index = value; }

    public DeleteEntityResult Result { get => result; set => result = value; }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct QueryUuidFilter
{
    public const int SIZE = 32;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 16;
        private const int LENGTH = 16;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/query-uuid-filter#entity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-uuid-filter#reserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct QueryRadiusFilter
{
    public const int SIZE = 128;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 80;
        private const int LENGTH = 80;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private long centerLatNano;

    private long centerLonNano;

    private uint radiusMm;

    private uint limit;

    private ulong timestampMin;

    private ulong timestampMax;

    private ulong groupId;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#center_lat_nano
    /// </summary>
    public long CenterLatNano { get => centerLatNano; set => centerLatNano = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#center_lon_nano
    /// </summary>
    public long CenterLonNano { get => centerLonNano; set => centerLonNano = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#radius_mm
    /// </summary>
    public uint RadiusMm { get => radiusMm; set => radiusMm = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#limit
    /// </summary>
    public uint Limit { get => limit; set => limit = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#timestamp_min
    /// </summary>
    public ulong TimestampMin { get => timestampMin; set => timestampMin = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#timestamp_max
    /// </summary>
    public ulong TimestampMax { get => timestampMax; set => timestampMax = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#group_id
    /// </summary>
    public ulong GroupId { get => groupId; set => groupId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-radius-filter#reserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct QueryPolygonFilter
{
    public const int SIZE = 128;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 88;
        private const int LENGTH = 88;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private uint vertexCount;

    private uint holeCount;

    private uint limit;

    private uint reservedAlign;

    private ulong timestampMin;

    private ulong timestampMax;

    private ulong groupId;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#vertex_count
    /// </summary>
    public uint VertexCount { get => vertexCount; set => vertexCount = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#hole_count
    /// </summary>
    public uint HoleCount { get => holeCount; set => holeCount = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#limit
    /// </summary>
    public uint Limit { get => limit; set => limit = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#_reserved_align
    /// </summary>
    public uint ReservedAlign { get => reservedAlign; set => reservedAlign = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#timestamp_min
    /// </summary>
    public ulong TimestampMin { get => timestampMin; set => timestampMin = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#timestamp_max
    /// </summary>
    public ulong TimestampMax { get => timestampMax; set => timestampMax = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#group_id
    /// </summary>
    public ulong GroupId { get => groupId; set => groupId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-polygon-filter#reserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct QueryLatestFilter
{
    public const int SIZE = 128;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 104;
        private const int LENGTH = 104;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private uint limit;

    private uint reservedAlign;

    private ulong groupId;

    private ulong cursorTimestamp;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/query-latest-filter#limit
    /// </summary>
    public uint Limit { get => limit; set => limit = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-latest-filter#_reserved_align
    /// </summary>
    public uint ReservedAlign { get => reservedAlign; set => reservedAlign = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-latest-filter#group_id
    /// </summary>
    public ulong GroupId { get => groupId; set => groupId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-latest-filter#cursor_timestamp
    /// </summary>
    public ulong CursorTimestamp { get => cursorTimestamp; set => cursorTimestamp = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/query-latest-filter#reserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

public enum TtlOperationResult : byte
{
    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#resultsuccess
    /// </summary>
    Success = 0,

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#resultentity_not_found
    /// </summary>
    EntityNotFound = 1,

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#resultinvalid_ttl
    /// </summary>
    InvalidTtl = 2,

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#resultnot_permitted
    /// </summary>
    NotPermitted = 3,

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#resultentity_immutable
    /// </summary>
    EntityImmutable = 4,

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlSetRequest
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 40;
        private const int LENGTH = 40;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint ttlSeconds;

    private uint flags;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#setentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#setttl_seconds
    /// </summary>
    public uint TtlSeconds { get => ttlSeconds; set => ttlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#setflags
    /// </summary>
    public uint Flags { get => flags; set => flags = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#setreserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlSetResponse
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = PaddingData.SIZE)]
    private unsafe struct PaddingData
    {
        public const int SIZE = 3;
        private const int LENGTH = 3;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 32;
        private const int LENGTH = 32;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint previousTtlSeconds;

    private uint newTtlSeconds;

    private TtlOperationResult result;

    private PaddingData padding;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-responseentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-responseprevious_ttl_seconds
    /// </summary>
    public uint PreviousTtlSeconds { get => previousTtlSeconds; set => previousTtlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-responsenew_ttl_seconds
    /// </summary>
    public uint NewTtlSeconds { get => newTtlSeconds; set => newTtlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-responseresult
    /// </summary>
    public TtlOperationResult Result { get => result; set => result = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-response_padding
    /// </summary>
    internal byte[] Padding { get => padding.GetData(); set => padding.SetData(value); }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#set-responsereserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlExtendRequest
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 40;
        private const int LENGTH = 40;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint extendBySeconds;

    private uint flags;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extendentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extendextend_by_seconds
    /// </summary>
    public uint ExtendBySeconds { get => extendBySeconds; set => extendBySeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extendflags
    /// </summary>
    public uint Flags { get => flags; set => flags = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extendreserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlExtendResponse
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = PaddingData.SIZE)]
    private unsafe struct PaddingData
    {
        public const int SIZE = 3;
        private const int LENGTH = 3;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 32;
        private const int LENGTH = 32;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint previousTtlSeconds;

    private uint newTtlSeconds;

    private TtlOperationResult result;

    private PaddingData padding;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-responseentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-responseprevious_ttl_seconds
    /// </summary>
    public uint PreviousTtlSeconds { get => previousTtlSeconds; set => previousTtlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-responsenew_ttl_seconds
    /// </summary>
    public uint NewTtlSeconds { get => newTtlSeconds; set => newTtlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-responseresult
    /// </summary>
    public TtlOperationResult Result { get => result; set => result = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-response_padding
    /// </summary>
    internal byte[] Padding { get => padding.GetData(); set => padding.SetData(value); }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#extend-responsereserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlClearRequest
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 44;
        private const int LENGTH = 44;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint flags;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clearentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clearflags
    /// </summary>
    public uint Flags { get => flags; set => flags = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clearreserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
public struct TtlClearResponse
{
    public const int SIZE = 64;


    [StructLayout(LayoutKind.Sequential, Size = PaddingData.SIZE)]
    private unsafe struct PaddingData
    {
        public const int SIZE = 3;
        private const int LENGTH = 3;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = ReservedData.SIZE)]
    private unsafe struct ReservedData
    {
        public const int SIZE = 36;
        private const int LENGTH = 36;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    private UInt128 entityId;

    private uint previousTtlSeconds;

    private TtlOperationResult result;

    private PaddingData padding;

    private ReservedData reserved;

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clear-responseentity_id
    /// </summary>
    public UInt128 EntityId { get => entityId; set => entityId = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clear-responseprevious_ttl_seconds
    /// </summary>
    public uint PreviousTtlSeconds { get => previousTtlSeconds; set => previousTtlSeconds = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clear-responseresult
    /// </summary>
    public TtlOperationResult Result { get => result; set => result = value; }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clear-response_padding
    /// </summary>
    internal byte[] Padding { get => padding.GetData(); set => padding.SetData(value); }

    /// <summary>
    /// https://docs.archerdb.io/reference/ttl#clear-responsereserved
    /// </summary>
    internal byte[] Reserved { get => reserved.GetData(); set => reserved.SetData(value); }

}

public enum InitializationStatus : uint
{
    Success = 0,

    Unexpected = 1,

    OutOfMemory = 2,

    AddressInvalid = 3,

    AddressLimitExceeded = 4,

    SystemResources = 5,

    NetworkSubsystem = 6,

}

internal enum ClientStatus : uint
{
    Ok = 0,

    Invalid = 1,

}

public enum PacketStatus : byte
{
    Ok = 0,

    TooMuchData = 1,

    ClientEvicted = 2,

    ClientReleaseTooLow = 3,

    ClientReleaseTooHigh = 4,

    ClientShutdown = 5,

    InvalidOperation = 6,

    InvalidDataSize = 7,

}

internal enum TBOperation : byte
{
    Pulse = 128,

    InsertEvents = 146,

    UpsertEvents = 147,

    DeleteEntities = 148,

    QueryUuid = 149,

    QueryRadius = 150,

    QueryPolygon = 151,

    QueryLatest = 154,

    QueryUuidBatch = 156,

    ArcherdbPing = 152,

    ArcherdbGetStatus = 153,

    CleanupExpired = 155,

    GetTopology = 157,

    TtlSet = 158,

    TtlExtend = 159,

    TtlClear = 160,

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
internal unsafe struct TBClient
{
    public const int SIZE = 32;


    [StructLayout(LayoutKind.Sequential, Size = OpaqueData.SIZE)]
    private unsafe struct OpaqueData
    {
        public const int SIZE = 32;
        private const int LENGTH = 4;

        private fixed ulong raw[LENGTH];

        public ulong[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<ulong>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(ulong[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a ulong[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<ulong>(ptr, LENGTH));
            }
        }
    }

    private OpaqueData opaque;

}

[StructLayout(LayoutKind.Sequential, Size = SIZE)]
internal unsafe struct TBPacket
{
    public const int SIZE = 88;


    [StructLayout(LayoutKind.Sequential, Size = OpaqueData.SIZE)]
    private unsafe struct OpaqueData
    {
        public const int SIZE = 64;
        private const int LENGTH = 64;

        private fixed byte raw[LENGTH];

        public byte[] GetData()
        {
            fixed (void* ptr = raw)
            {
                return new ReadOnlySpan<byte>(ptr, LENGTH).ToArray();
            }
        }

        public void SetData(byte[] value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if (value.Length != LENGTH)
            {
                throw new ArgumentException(
                    "Expected a byte[" + LENGTH + "] array",
                    nameof(value));
            }

            fixed (void* ptr = raw)
            {
                value.CopyTo(new Span<byte>(ptr, LENGTH));
            }
        }
    }

    public IntPtr userData;

    public IntPtr data;

    public uint dataSize;

    public ushort userTag;

    public byte operation;

    public PacketStatus status;

    private OpaqueData opaque;

}

internal static class Native
{
    private const string LIB_NAME = "arch_client";

    [DllImport(LIB_NAME, CallingConvention = CallingConvention.Cdecl)]
    public static unsafe extern InitializationStatus arch_client_init(
        TBClient* client_out,
        UInt128Extensions.UnsafeU128* cluster_id,
        byte* address_ptr,
        uint address_len,
        IntPtr completion_ctx,
        delegate* unmanaged[Cdecl]<IntPtr,
                                   TBPacket*, ulong,
                                   byte*, uint, void> completion_callback
    );

    [DllImport(LIB_NAME, CallingConvention = CallingConvention.Cdecl)]
    public static unsafe extern InitializationStatus arch_client_init_echo(
        TBClient* out_client,
        UInt128Extensions.UnsafeU128* cluster_id,
        byte* address_ptr,
        uint address_len,
        IntPtr completion_ctx,
        delegate* unmanaged[Cdecl]<IntPtr,
                                   TBPacket*, ulong,
                                   byte*, uint, void> completion_callback
    );

    [DllImport(LIB_NAME, CallingConvention = CallingConvention.Cdecl)]
    public static unsafe extern ClientStatus arch_client_submit(
        TBClient* client,
        TBPacket* packet
    );

    [DllImport(LIB_NAME, CallingConvention = CallingConvention.Cdecl)]
    public static unsafe extern ClientStatus arch_client_deinit(
        TBClient* client
    );
}

