##########################################################
## This file was auto-generated by arch_client_header.zig ##
##              Do not manually modify.                 ##
##########################################################
from __future__ import annotations

import ctypes
import enum
import sys
from dataclasses import dataclass
from collections.abc import Callable # noqa: TCH003
from typing import Any
if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

from .lib import c_uint128, archclient, validate_uint

# Use slots=True if the version of Python is new enough (3.10+) to support it.
if sys.version_info >= (3, 10):
    # mypy: ignore assignment (3.10+) and unused-ignore (pre 3.10)
    dataclass = dataclass(slots=True) # type: ignore[assignment, unused-ignore]


class Operation(enum.IntEnum):
    PULSE = 128
    GET_CHANGE_EVENTS = 137
    CREATE_ACCOUNTS = 138
    CREATE_TRANSFERS = 139
    LOOKUP_ACCOUNTS = 140
    LOOKUP_TRANSFERS = 141
    GET_ACCOUNT_TRANSFERS = 142
    GET_ACCOUNT_BALANCES = 143
    QUERY_ACCOUNTS = 144
    QUERY_TRANSFERS = 145
    INSERT_EVENTS = 146
    UPSERT_EVENTS = 147
    DELETE_ENTITIES = 148
    QUERY_UUID = 149
    QUERY_RADIUS = 150
    QUERY_POLYGON = 151
    QUERY_LATEST = 154
    ARCHERDB_PING = 152
    ARCHERDB_GET_STATUS = 153
    CLEANUP_EXPIRED = 155


class PacketStatus(enum.IntEnum):
    OK = 0
    TOO_MUCH_DATA = 1
    CLIENT_EVICTED = 2
    CLIENT_RELEASE_TOO_LOW = 3
    CLIENT_RELEASE_TOO_HIGH = 4
    CLIENT_SHUTDOWN = 5
    INVALID_OPERATION = 6
    INVALID_DATA_SIZE = 7


class InitStatus(enum.IntEnum):
    SUCCESS = 0
    UNEXPECTED = 1
    OUT_OF_MEMORY = 2
    ADDRESS_INVALID = 3
    ADDRESS_LIMIT_EXCEEDED = 4
    SYSTEM_RESOURCES = 5
    NETWORK_SUBSYSTEM = 6


class ClientStatus(enum.IntEnum):
    OK = 0
    INVALID = 1


class LogLevel(enum.IntEnum):
    ERR = 0
    WARN = 1
    INFO = 2
    DEBUG = 3


class RegisterLogCallbackStatus(enum.IntEnum):
    SUCCESS = 0
    ALREADY_REGISTERED = 1
    NOT_REGISTERED = 2


class GeoEventFlags(enum.IntFlag):
    NONE = 0
    LINKED = 1 << 0
    IMPORTED = 1 << 1
    STATIONARY = 1 << 2
    LOW_ACCURACY = 1 << 3
    OFFLINE = 1 << 4
    DELETED = 1 << 5


class InsertGeoEventResult(enum.IntEnum):
    OK = 0
    LINKED_EVENT_FAILED = 1
    LINKED_EVENT_CHAIN_OPEN = 2
    TIMESTAMP_MUST_BE_ZERO = 3
    RESERVED_FIELD = 4
    RESERVED_FLAG = 5
    ID_MUST_NOT_BE_ZERO = 6
    ENTITY_ID_MUST_NOT_BE_ZERO = 7
    INVALID_COORDINATES = 8
    LAT_OUT_OF_RANGE = 9
    LON_OUT_OF_RANGE = 10
    EXISTS_WITH_DIFFERENT_ENTITY_ID = 11
    EXISTS_WITH_DIFFERENT_COORDINATES = 12
    EXISTS = 13
    HEADING_OUT_OF_RANGE = 14
    TTL_INVALID = 15


class DeleteEntityResult(enum.IntEnum):
    OK = 0
    LINKED_EVENT_FAILED = 1
    ENTITY_ID_MUST_NOT_BE_ZERO = 2
    ENTITY_NOT_FOUND = 3


@dataclass
class GeoEvent:
    id: int = 0
    entity_id: int = 0
    correlation_id: int = 0
    user_data: int = 0
    lat_nano: int = 0
    lon_nano: int = 0
    group_id: int = 0
    timestamp: int = 0
    altitude_mm: int = 0
    velocity_mms: int = 0
    ttl_seconds: int = 0
    accuracy_mm: int = 0
    heading_cdeg: int = 0
    flags: GeoEventFlags = GeoEventFlags.NONE


@dataclass
class InsertGeoEventsResult:
    index: int = 0
    result: InsertGeoEventResult = InsertGeoEventResult.OK


@dataclass
class DeleteEntitiesResult:
    index: int = 0
    result: DeleteEntityResult = DeleteEntityResult.OK


@dataclass
class QueryUuidFilter:
    entity_id: int = 0
    limit: int = 0


@dataclass
class QueryRadiusFilter:
    center_lat_nano: int = 0
    center_lon_nano: int = 0
    radius_mm: int = 0
    limit: int = 0
    timestamp_min: int = 0
    timestamp_max: int = 0
    group_id: int = 0


@dataclass
class QueryPolygonFilter:
    vertex_count: int = 0
    limit: int = 0
    timestamp_min: int = 0
    timestamp_max: int = 0
    group_id: int = 0


@dataclass
class QueryLatestFilter:
    limit: int = 0
    _reserved_align: int = 0
    group_id: int = 0
    cursor_timestamp: int = 0


@dataclass
class QueryResponse:
    count: int = 0
    has_more: int = 0
    partial_result: int = 0


@dataclass
class PolygonVertex:
    lat_nano: int = 0
    lon_nano: int = 0


class CPacket(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="data_size", number=obj.data_size)
        validate_uint(bits=16, name="user_tag", number=obj.user_tag)
        validate_uint(bits=8, name="operation", number=obj.operation)
        return cls(
            user_data=obj.user_data,
            data=obj.data,
            data_size=obj.data_size,
            user_tag=obj.user_tag,
            operation=obj.operation,
            status=obj.status,
            opaque=obj.opaque,
        )

CPacket._fields_ = [ # noqa: SLF001
    ("user_data", ctypes.c_void_p),
    ("data", ctypes.c_void_p),
    ("data_size", ctypes.c_uint32),
    ("user_tag", ctypes.c_uint16),
    ("operation", ctypes.c_uint8),
    ("status", ctypes.c_uint8),
    ("opaque", ctypes.c_uint8 * 64),
]


class CClient(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        return cls(
            opaque=obj.opaque,
        )

CClient._fields_ = [ # noqa: SLF001
    ("opaque", ctypes.c_uint64 * 4),
]


class CGeoEvent(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="id", number=obj.id)
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=128, name="correlation_id", number=obj.correlation_id)
        validate_uint(bits=128, name="user_data", number=obj.user_data)
        validate_uint(bits=64, name="lat_nano", number=obj.lat_nano)
        validate_uint(bits=64, name="lon_nano", number=obj.lon_nano)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        validate_uint(bits=64, name="timestamp", number=obj.timestamp)
        validate_uint(bits=32, name="altitude_mm", number=obj.altitude_mm)
        validate_uint(bits=32, name="velocity_mms", number=obj.velocity_mms)
        validate_uint(bits=32, name="ttl_seconds", number=obj.ttl_seconds)
        validate_uint(bits=32, name="accuracy_mm", number=obj.accuracy_mm)
        validate_uint(bits=16, name="heading_cdeg", number=obj.heading_cdeg)
        return cls(
            id=c_uint128.from_param(obj.id),
            entity_id=c_uint128.from_param(obj.entity_id),
            correlation_id=c_uint128.from_param(obj.correlation_id),
            user_data=c_uint128.from_param(obj.user_data),
            lat_nano=obj.lat_nano,
            lon_nano=obj.lon_nano,
            group_id=obj.group_id,
            timestamp=obj.timestamp,
            altitude_mm=obj.altitude_mm,
            velocity_mms=obj.velocity_mms,
            ttl_seconds=obj.ttl_seconds,
            accuracy_mm=obj.accuracy_mm,
            heading_cdeg=obj.heading_cdeg,
            flags=obj.flags,
        )


    def to_python(self) -> GeoEvent:
        return GeoEvent(
            id=self.id.to_python(),
            entity_id=self.entity_id.to_python(),
            correlation_id=self.correlation_id.to_python(),
            user_data=self.user_data.to_python(),
            lat_nano=self.lat_nano,
            lon_nano=self.lon_nano,
            group_id=self.group_id,
            timestamp=self.timestamp,
            altitude_mm=self.altitude_mm,
            velocity_mms=self.velocity_mms,
            ttl_seconds=self.ttl_seconds,
            accuracy_mm=self.accuracy_mm,
            heading_cdeg=self.heading_cdeg,
            flags=GeoEventFlags(self.flags),
        )

CGeoEvent._fields_ = [ # noqa: SLF001
    ("id", c_uint128),
    ("entity_id", c_uint128),
    ("correlation_id", c_uint128),
    ("user_data", c_uint128),
    ("lat_nano", ctypes.c_int64),
    ("lon_nano", ctypes.c_int64),
    ("group_id", ctypes.c_uint64),
    ("timestamp", ctypes.c_uint64),
    ("altitude_mm", ctypes.c_int32),
    ("velocity_mms", ctypes.c_uint32),
    ("ttl_seconds", ctypes.c_uint32),
    ("accuracy_mm", ctypes.c_uint32),
    ("heading_cdeg", ctypes.c_uint16),
    ("flags", ctypes.c_uint16),
    ("reserved", ctypes.c_uint8 * 12),
]


class CInsertGeoEventsResult(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="index", number=obj.index)
        return cls(
            index=obj.index,
            result=obj.result,
        )


    def to_python(self) -> InsertGeoEventsResult:
        return InsertGeoEventsResult(
            index=self.index,
            result=InsertGeoEventResult(self.result),
        )

CInsertGeoEventsResult._fields_ = [ # noqa: SLF001
    ("index", ctypes.c_uint32),
    ("result", ctypes.c_uint32),
]


class CDeleteEntitiesResult(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="index", number=obj.index)
        return cls(
            index=obj.index,
            result=obj.result,
        )


    def to_python(self) -> DeleteEntitiesResult:
        return DeleteEntitiesResult(
            index=self.index,
            result=DeleteEntityResult(self.result),
        )

CDeleteEntitiesResult._fields_ = [ # noqa: SLF001
    ("index", ctypes.c_uint32),
    ("result", ctypes.c_uint32),
]


class CQueryUuidFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="limit", number=obj.limit)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            limit=obj.limit,
        )


    def to_python(self) -> QueryUuidFilter:
        return QueryUuidFilter(
            entity_id=self.entity_id.to_python(),
            limit=self.limit,
        )

CQueryUuidFilter._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("limit", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 108),
]


class CQueryRadiusFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=64, name="center_lat_nano", number=obj.center_lat_nano)
        validate_uint(bits=64, name="center_lon_nano", number=obj.center_lon_nano)
        validate_uint(bits=32, name="radius_mm", number=obj.radius_mm)
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=64, name="timestamp_min", number=obj.timestamp_min)
        validate_uint(bits=64, name="timestamp_max", number=obj.timestamp_max)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        return cls(
            center_lat_nano=obj.center_lat_nano,
            center_lon_nano=obj.center_lon_nano,
            radius_mm=obj.radius_mm,
            limit=obj.limit,
            timestamp_min=obj.timestamp_min,
            timestamp_max=obj.timestamp_max,
            group_id=obj.group_id,
        )


    def to_python(self) -> QueryRadiusFilter:
        return QueryRadiusFilter(
            center_lat_nano=self.center_lat_nano,
            center_lon_nano=self.center_lon_nano,
            radius_mm=self.radius_mm,
            limit=self.limit,
            timestamp_min=self.timestamp_min,
            timestamp_max=self.timestamp_max,
            group_id=self.group_id,
        )

CQueryRadiusFilter._fields_ = [ # noqa: SLF001
    ("center_lat_nano", ctypes.c_int64),
    ("center_lon_nano", ctypes.c_int64),
    ("radius_mm", ctypes.c_uint32),
    ("limit", ctypes.c_uint32),
    ("timestamp_min", ctypes.c_uint64),
    ("timestamp_max", ctypes.c_uint64),
    ("group_id", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 80),
]


class CQueryPolygonFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="vertex_count", number=obj.vertex_count)
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=64, name="timestamp_min", number=obj.timestamp_min)
        validate_uint(bits=64, name="timestamp_max", number=obj.timestamp_max)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        return cls(
            vertex_count=obj.vertex_count,
            limit=obj.limit,
            timestamp_min=obj.timestamp_min,
            timestamp_max=obj.timestamp_max,
            group_id=obj.group_id,
        )


    def to_python(self) -> QueryPolygonFilter:
        return QueryPolygonFilter(
            vertex_count=self.vertex_count,
            limit=self.limit,
            timestamp_min=self.timestamp_min,
            timestamp_max=self.timestamp_max,
            group_id=self.group_id,
        )

CQueryPolygonFilter._fields_ = [ # noqa: SLF001
    ("vertex_count", ctypes.c_uint32),
    ("limit", ctypes.c_uint32),
    ("timestamp_min", ctypes.c_uint64),
    ("timestamp_max", ctypes.c_uint64),
    ("group_id", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 96),
]


class CQueryLatestFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=32, name="_reserved_align", number=obj._reserved_align)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        validate_uint(bits=64, name="cursor_timestamp", number=obj.cursor_timestamp)
        return cls(
            limit=obj.limit,
            _reserved_align=obj._reserved_align,
            group_id=obj.group_id,
            cursor_timestamp=obj.cursor_timestamp,
        )


    def to_python(self) -> QueryLatestFilter:
        return QueryLatestFilter(
            limit=self.limit,
            _reserved_align=self._reserved_align,
            group_id=self.group_id,
            cursor_timestamp=self.cursor_timestamp,
        )

CQueryLatestFilter._fields_ = [ # noqa: SLF001
    ("limit", ctypes.c_uint32),
    ("_reserved_align", ctypes.c_uint32),
    ("group_id", ctypes.c_uint64),
    ("cursor_timestamp", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 104),
]


class CQueryResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="count", number=obj.count)
        validate_uint(bits=8, name="has_more", number=obj.has_more)
        validate_uint(bits=8, name="partial_result", number=obj.partial_result)
        return cls(
            count=obj.count,
            has_more=obj.has_more,
            partial_result=obj.partial_result,
        )


    def to_python(self) -> QueryResponse:
        return QueryResponse(
            count=self.count,
            has_more=self.has_more,
            partial_result=self.partial_result,
        )

CQueryResponse._fields_ = [ # noqa: SLF001
    ("count", ctypes.c_uint32),
    ("has_more", ctypes.c_uint8),
    ("partial_result", ctypes.c_uint8),
    ("reserved", ctypes.c_uint8 * 10),
]


class CPolygonVertex(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=64, name="lat_nano", number=obj.lat_nano)
        validate_uint(bits=64, name="lon_nano", number=obj.lon_nano)
        return cls(
            lat_nano=obj.lat_nano,
            lon_nano=obj.lon_nano,
        )


    def to_python(self) -> PolygonVertex:
        return PolygonVertex(
            lat_nano=self.lat_nano,
            lon_nano=self.lon_nano,
        )

CPolygonVertex._fields_ = [ # noqa: SLF001
    ("lat_nano", ctypes.c_int64),
    ("lon_nano", ctypes.c_int64),
]


# Don't be tempted to use c_char_p for bytes_ptr - it's for null terminated strings only.
OnCompletion = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.POINTER(CPacket),
                                ctypes.c_uint64, ctypes.c_void_p, ctypes.c_uint32)
LogHandler = ctypes.CFUNCTYPE(None, ctypes.c_uint, ctypes.c_void_p, ctypes.c_uint)

class InitParameters(ctypes.Structure):
    _fields_ = [("cluster_id", c_uint128), ("client_id", c_uint128),
                ("addresses_ptr", ctypes.c_void_p), ("addresses_len", ctypes.c_uint64)]

# Initialize a new ArcherDB client which connects to the addresses provided and
# completes submitted packets by invoking the callback with the given context.
arch_client_init = archclient.arch_client_init
arch_client_init.restype = InitStatus
arch_client_init.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(ctypes.c_uint8 * 16),
                           ctypes.c_char_p, ctypes.c_uint32, ctypes.c_void_p,
                           OnCompletion]

# Initialize a new ArcherDB client which echos back any data submitted.
arch_client_init_echo = archclient.arch_client_init_echo
arch_client_init_echo.restype = InitStatus
arch_client_init_echo.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(ctypes.c_uint8 * 16),
                                ctypes.c_char_p, ctypes.c_uint32, ctypes.c_void_p,
                                OnCompletion]

# Returns the cluster_id and addresses passed in to either arch_client_init or
# arch_client_init_echo.
arch_client_init_parameters = archclient.arch_client_init_parameters
arch_client_init_parameters.restype = ClientStatus
arch_client_init_parameters.argtypes = [ctypes.POINTER(CClient),
                                      ctypes.POINTER(InitParameters)]

# Closes the client, causing any previously submitted packets to be completed with
# `ARCH_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
# It is undefined behavior to use any functions on the client once deinit is called.
arch_client_deinit = archclient.arch_client_deinit
arch_client_deinit.restype = ClientStatus
arch_client_deinit.argtypes = [ctypes.POINTER(CClient)]

# Submit a packet with its operation, data, and data_size fields set.
# Once completed, `on_completion` will be invoked with `on_completion_ctx` and the given
# packet on the `arch_client` thread (separate from caller's thread).
arch_client_submit = archclient.arch_client_submit
arch_client_submit.restype = ClientStatus
arch_client_submit.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(CPacket)]

arch_client_register_log_callback = archclient.arch_client_register_log_callback
arch_client_register_log_callback.restype = RegisterLogCallbackStatus
# Need to pass in None to clear - ctypes will error if argtypes is set.
# arch_client_register_log_callback.argtypes = [LogHandler, ctypes.c_bool]


class AsyncStateMachineMixin:
    _submit: Callable[[Operation, Any, Any, Any], Any]
    async def insert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.INSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    async def upsert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.UPSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    async def delete_entities(self, entity_ids: list[int]) -> list[DeleteEntitiesResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.DELETE_ENTITIES,
            entity_ids,
            c_uint128,
            CDeleteEntitiesResult,
        )

    async def query_uuid(self, filter: QueryUuidFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_UUID,
            [filter],
            CQueryUuidFilter,
            CGeoEvent,
        )

    async def query_radius(self, filter: QueryRadiusFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_RADIUS,
            [filter],
            CQueryRadiusFilter,
            CGeoEvent,
        )

    async def query_polygon(self, filter: QueryPolygonFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_POLYGON,
            [filter],
            CQueryPolygonFilter,
            CGeoEvent,
        )

    async def query_latest(self, filter: QueryLatestFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_LATEST,
            [filter],
            CQueryLatestFilter,
            CGeoEvent,
        )



class StateMachineMixin:
    _submit: Callable[[Operation, Any, Any, Any], Any]
    def insert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.INSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    def upsert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.UPSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    def delete_entities(self, entity_ids: list[int]) -> list[DeleteEntitiesResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.DELETE_ENTITIES,
            entity_ids,
            c_uint128,
            CDeleteEntitiesResult,
        )

    def query_uuid(self, filter: QueryUuidFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_UUID,
            [filter],
            CQueryUuidFilter,
            CGeoEvent,
        )

    def query_radius(self, filter: QueryRadiusFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_RADIUS,
            [filter],
            CQueryRadiusFilter,
            CGeoEvent,
        )

    def query_polygon(self, filter: QueryPolygonFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_POLYGON,
            [filter],
            CQueryPolygonFilter,
            CGeoEvent,
        )

    def query_latest(self, filter: QueryLatestFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_LATEST,
            [filter],
            CQueryLatestFilter,
            CGeoEvent,
        )



