# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2025 ArcherDB Contributors
##########################################################
## This file was auto-generated by arch_client_header.zig ##
##              Do not manually modify.                 ##
##########################################################
from __future__ import annotations

import ctypes
import enum
import sys
from dataclasses import dataclass
from collections.abc import Callable # noqa: TCH003
from typing import Any
if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

from .lib import c_uint128, c_int128, archclient, validate_uint, validate_int

# Use slots=True if the version of Python is new enough (3.10+) to support it.
if sys.version_info >= (3, 10):
    # mypy: ignore assignment (3.10+) and unused-ignore (pre 3.10)
    dataclass = dataclass(slots=True) # type: ignore[assignment, unused-ignore]


class Operation(enum.IntEnum):
    PULSE = 128
    INSERT_EVENTS = 146
    UPSERT_EVENTS = 147
    DELETE_ENTITIES = 148
    QUERY_UUID = 149
    QUERY_RADIUS = 150
    QUERY_POLYGON = 151
    QUERY_LATEST = 154
    QUERY_UUID_BATCH = 156
    ARCHERDB_PING = 152
    ARCHERDB_GET_STATUS = 153
    CLEANUP_EXPIRED = 155
    GET_TOPOLOGY = 157
    TTL_SET = 158
    TTL_EXTEND = 159
    TTL_CLEAR = 160
    BATCH_QUERY = 161
    PREPARE_QUERY = 162
    EXECUTE_PREPARED = 163
    DEALLOCATE_PREPARED = 164


class PacketStatus(enum.IntEnum):
    OK = 0
    TOO_MUCH_DATA = 1
    CLIENT_EVICTED = 2
    CLIENT_RELEASE_TOO_LOW = 3
    CLIENT_RELEASE_TOO_HIGH = 4
    CLIENT_SHUTDOWN = 5
    INVALID_OPERATION = 6
    INVALID_DATA_SIZE = 7


class InitStatus(enum.IntEnum):
    SUCCESS = 0
    UNEXPECTED = 1
    OUT_OF_MEMORY = 2
    ADDRESS_INVALID = 3
    ADDRESS_LIMIT_EXCEEDED = 4
    SYSTEM_RESOURCES = 5
    NETWORK_SUBSYSTEM = 6


class ClientStatus(enum.IntEnum):
    OK = 0
    INVALID = 1


class LogLevel(enum.IntEnum):
    ERR = 0
    WARN = 1
    INFO = 2
    DEBUG = 3


class RegisterLogCallbackStatus(enum.IntEnum):
    SUCCESS = 0
    ALREADY_REGISTERED = 1
    NOT_REGISTERED = 2


class GeoEventFlags(enum.IntFlag):
    NONE = 0
    LINKED = 1 << 0
    IMPORTED = 1 << 1
    STATIONARY = 1 << 2
    LOW_ACCURACY = 1 << 3
    OFFLINE = 1 << 4
    DELETED = 1 << 5


class InsertGeoEventResult(enum.IntEnum):
    OK = 0
    LINKED_EVENT_FAILED = 1
    LINKED_EVENT_CHAIN_OPEN = 2
    TIMESTAMP_MUST_BE_ZERO = 3
    RESERVED_FIELD = 4
    RESERVED_FLAG = 5
    ID_MUST_NOT_BE_ZERO = 6
    ENTITY_ID_MUST_NOT_BE_ZERO = 7
    INVALID_COORDINATES = 8
    LAT_OUT_OF_RANGE = 9
    LON_OUT_OF_RANGE = 10
    EXISTS_WITH_DIFFERENT_ENTITY_ID = 11
    EXISTS_WITH_DIFFERENT_COORDINATES = 12
    EXISTS = 13
    HEADING_OUT_OF_RANGE = 14
    TTL_INVALID = 15
    ENTITY_ID_MUST_NOT_BE_INT_MAX = 16


class DeleteEntityResult(enum.IntEnum):
    OK = 0
    LINKED_EVENT_FAILED = 1
    ENTITY_ID_MUST_NOT_BE_ZERO = 2
    ENTITY_NOT_FOUND = 3
    ENTITY_ID_MUST_NOT_BE_INT_MAX = 4


class ShardStatus(enum.IntEnum):
    ACTIVE = 0
    SYNCING = 1
    UNAVAILABLE = 2
    MIGRATING = 3
    DECOMMISSIONING = 4


class TtlOperationResult(enum.IntEnum):
    SUCCESS = 0
    ENTITY_NOT_FOUND = 1
    INVALID_TTL = 2
    NOT_PERMITTED = 3
    ENTITY_IMMUTABLE = 4


@dataclass
class GeoEvent:
    id: int = 0
    entity_id: int = 0
    correlation_id: int = 0
    user_data: int = 0
    lat_nano: int = 0
    lon_nano: int = 0
    group_id: int = 0
    timestamp: int = 0
    altitude_mm: int = 0
    velocity_mms: int = 0
    ttl_seconds: int = 0
    accuracy_mm: int = 0
    heading_cdeg: int = 0
    flags: GeoEventFlags = GeoEventFlags.NONE


@dataclass
class InsertGeoEventsResult:
    index: int = 0
    result: InsertGeoEventResult = InsertGeoEventResult.OK


@dataclass
class DeleteEntitiesResult:
    index: int = 0
    result: DeleteEntityResult = DeleteEntityResult.OK


@dataclass
class QueryUuidFilter:
    entity_id: int = 0


@dataclass
class QueryUuidResponse:
    status: int = 0


@dataclass
class QueryUuidBatchFilter:
    count: int = 0


@dataclass
class QueryUuidBatchResult:
    found_count: int = 0
    not_found_count: int = 0


@dataclass
class QueryRadiusFilter:
    center_lat_nano: int = 0
    center_lon_nano: int = 0
    radius_mm: int = 0
    limit: int = 0
    timestamp_min: int = 0
    timestamp_max: int = 0
    group_id: int = 0


@dataclass
class QueryPolygonFilter:
    vertex_count: int = 0
    hole_count: int = 0
    limit: int = 0
    _reserved_align: int = 0
    timestamp_min: int = 0
    timestamp_max: int = 0
    group_id: int = 0


@dataclass
class QueryLatestFilter:
    limit: int = 0
    _reserved_align: int = 0
    group_id: int = 0
    cursor_timestamp: int = 0


@dataclass
class QueryResponse:
    count: int = 0
    has_more: int = 0
    partial_result: int = 0


@dataclass
class PolygonVertex:
    lat_nano: int = 0
    lon_nano: int = 0


@dataclass
class HoleDescriptor:
    vertex_count: int = 0


@dataclass
class PingRequest:
    ping_data: int = 0


@dataclass
class StatusRequest:
    pass


@dataclass
class PingResponse:
    pong: int = 0


@dataclass
class StatusResponse:
    ram_index_count: int = 0
    ram_index_capacity: int = 0
    ram_index_load_pct: int = 0
    _padding: int = 0
    tombstone_count: int = 0
    ttl_expirations: int = 0
    deletion_count: int = 0
    index_resize_status: int = 0
    membership_state: int = 0
    _status_padding: int = 0
    index_resize_progress: int = 0
    membership_voters_count: int = 0
    membership_learners_count: int = 0


@dataclass
class TopologyRequest:
    pass


@dataclass
class ShardInfo:
    id: int = 0
    primary: int[64] = 0
    replicas: int[64][6] = 0
    replica_count: int = 0
    status: ShardStatus = ShardStatus.ACTIVE
    entity_count: int = 0
    size_bytes: int = 0


@dataclass
class TopologyResponse:
    version: int = 0
    num_shards: int = 0
    cluster_id: int = 0
    last_change_ns: int = 0
    resharding_status: int = 0
    flags: int = 0
    _padding: int[6] = 0
    shards: ShardInfo[256] = 0


@dataclass
class TtlSetRequest:
    entity_id: int = 0
    ttl_seconds: int = 0
    flags: int = 0


@dataclass
class TtlSetResponse:
    entity_id: int = 0
    previous_ttl_seconds: int = 0
    new_ttl_seconds: int = 0
    result: TtlOperationResult = TtlOperationResult.SUCCESS
    _padding: int[3] = 0


@dataclass
class TtlExtendRequest:
    entity_id: int = 0
    extend_by_seconds: int = 0
    flags: int = 0


@dataclass
class TtlExtendResponse:
    entity_id: int = 0
    previous_ttl_seconds: int = 0
    new_ttl_seconds: int = 0
    result: TtlOperationResult = TtlOperationResult.SUCCESS
    _padding: int[3] = 0


@dataclass
class TtlClearRequest:
    entity_id: int = 0
    flags: int = 0


@dataclass
class TtlClearResponse:
    entity_id: int = 0
    previous_ttl_seconds: int = 0
    result: TtlOperationResult = TtlOperationResult.SUCCESS
    _padding: int[3] = 0


class CPacket(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="data_size", number=obj.data_size)
        validate_uint(bits=16, name="user_tag", number=obj.user_tag)
        validate_uint(bits=8, name="operation", number=obj.operation)
        return cls(
            user_data=obj.user_data,
            data=obj.data,
            data_size=obj.data_size,
            user_tag=obj.user_tag,
            operation=obj.operation,
            status=obj.status,
            opaque=obj.opaque,
        )

CPacket._fields_ = [ # noqa: SLF001
    ("user_data", ctypes.c_void_p),
    ("data", ctypes.c_void_p),
    ("data_size", ctypes.c_uint32),
    ("user_tag", ctypes.c_uint16),
    ("operation", ctypes.c_uint8),
    ("status", ctypes.c_uint8),
    ("opaque", ctypes.c_uint8 * 64),
]


class CClient(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        return cls(
            opaque=obj.opaque,
        )

CClient._fields_ = [ # noqa: SLF001
    ("opaque", ctypes.c_uint64 * 4),
]


class CGeoEvent(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="id", number=obj.id)
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=128, name="correlation_id", number=obj.correlation_id)
        validate_uint(bits=128, name="user_data", number=obj.user_data)
        validate_int(bits=64, name="lat_nano", number=obj.lat_nano)
        validate_int(bits=64, name="lon_nano", number=obj.lon_nano)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        validate_uint(bits=64, name="timestamp", number=obj.timestamp)
        validate_int(bits=32, name="altitude_mm", number=obj.altitude_mm)
        validate_uint(bits=32, name="velocity_mms", number=obj.velocity_mms)
        validate_uint(bits=32, name="ttl_seconds", number=obj.ttl_seconds)
        validate_uint(bits=32, name="accuracy_mm", number=obj.accuracy_mm)
        validate_uint(bits=16, name="heading_cdeg", number=obj.heading_cdeg)
        return cls(
            id=c_uint128.from_param(obj.id),
            entity_id=c_uint128.from_param(obj.entity_id),
            correlation_id=c_uint128.from_param(obj.correlation_id),
            user_data=c_uint128.from_param(obj.user_data),
            lat_nano=obj.lat_nano,
            lon_nano=obj.lon_nano,
            group_id=obj.group_id,
            timestamp=obj.timestamp,
            altitude_mm=obj.altitude_mm,
            velocity_mms=obj.velocity_mms,
            ttl_seconds=obj.ttl_seconds,
            accuracy_mm=obj.accuracy_mm,
            heading_cdeg=obj.heading_cdeg,
            flags=obj.flags,
        )


    def to_python(self) -> GeoEvent:
        return GeoEvent(
            id=self.id.to_python(),
            entity_id=self.entity_id.to_python(),
            correlation_id=self.correlation_id.to_python(),
            user_data=self.user_data.to_python(),
            lat_nano=self.lat_nano,
            lon_nano=self.lon_nano,
            group_id=self.group_id,
            timestamp=self.timestamp,
            altitude_mm=self.altitude_mm,
            velocity_mms=self.velocity_mms,
            ttl_seconds=self.ttl_seconds,
            accuracy_mm=self.accuracy_mm,
            heading_cdeg=self.heading_cdeg,
            flags=GeoEventFlags(self.flags),
        )

CGeoEvent._fields_ = [ # noqa: SLF001
    ("id", c_uint128),
    ("entity_id", c_uint128),
    ("correlation_id", c_uint128),
    ("user_data", c_uint128),
    ("lat_nano", ctypes.c_int64),
    ("lon_nano", ctypes.c_int64),
    ("group_id", ctypes.c_uint64),
    ("timestamp", ctypes.c_uint64),
    ("altitude_mm", ctypes.c_int32),
    ("velocity_mms", ctypes.c_uint32),
    ("ttl_seconds", ctypes.c_uint32),
    ("accuracy_mm", ctypes.c_uint32),
    ("heading_cdeg", ctypes.c_uint16),
    ("flags", ctypes.c_uint16),
    ("reserved", ctypes.c_uint8 * 12),
]


class CInsertGeoEventsResult(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="index", number=obj.index)
        return cls(
            index=obj.index,
            result=obj.result,
        )


    def to_python(self) -> InsertGeoEventsResult:
        return InsertGeoEventsResult(
            index=self.index,
            result=InsertGeoEventResult(self.result),
        )

CInsertGeoEventsResult._fields_ = [ # noqa: SLF001
    ("index", ctypes.c_uint32),
    ("result", ctypes.c_uint32),
]


class CDeleteEntitiesResult(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="index", number=obj.index)
        return cls(
            index=obj.index,
            result=obj.result,
        )


    def to_python(self) -> DeleteEntitiesResult:
        return DeleteEntitiesResult(
            index=self.index,
            result=DeleteEntityResult(self.result),
        )

CDeleteEntitiesResult._fields_ = [ # noqa: SLF001
    ("index", ctypes.c_uint32),
    ("result", ctypes.c_uint32),
]


class CQueryUuidFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
        )


    def to_python(self) -> QueryUuidFilter:
        return QueryUuidFilter(
            entity_id=self.entity_id.to_python(),
        )

CQueryUuidFilter._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("reserved", ctypes.c_uint8 * 16),
]


class CQueryUuidResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=8, name="status", number=obj.status)
        return cls(
            status=obj.status,
        )


    def to_python(self) -> QueryUuidResponse:
        return QueryUuidResponse(
            status=self.status,
        )

CQueryUuidResponse._fields_ = [ # noqa: SLF001
    ("status", ctypes.c_uint8),
    ("reserved", ctypes.c_uint8 * 15),
]


class CQueryUuidBatchFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="count", number=obj.count)
        return cls(
            count=obj.count,
        )


    def to_python(self) -> QueryUuidBatchFilter:
        return QueryUuidBatchFilter(
            count=self.count,
        )

CQueryUuidBatchFilter._fields_ = [ # noqa: SLF001
    ("count", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 12),
]


class CQueryUuidBatchResult(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="found_count", number=obj.found_count)
        validate_uint(bits=32, name="not_found_count", number=obj.not_found_count)
        return cls(
            found_count=obj.found_count,
            not_found_count=obj.not_found_count,
        )


    def to_python(self) -> QueryUuidBatchResult:
        return QueryUuidBatchResult(
            found_count=self.found_count,
            not_found_count=self.not_found_count,
        )

CQueryUuidBatchResult._fields_ = [ # noqa: SLF001
    ("found_count", ctypes.c_uint32),
    ("not_found_count", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 8),
]


class CQueryRadiusFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_int(bits=64, name="center_lat_nano", number=obj.center_lat_nano)
        validate_int(bits=64, name="center_lon_nano", number=obj.center_lon_nano)
        validate_uint(bits=32, name="radius_mm", number=obj.radius_mm)
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=64, name="timestamp_min", number=obj.timestamp_min)
        validate_uint(bits=64, name="timestamp_max", number=obj.timestamp_max)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        return cls(
            center_lat_nano=obj.center_lat_nano,
            center_lon_nano=obj.center_lon_nano,
            radius_mm=obj.radius_mm,
            limit=obj.limit,
            timestamp_min=obj.timestamp_min,
            timestamp_max=obj.timestamp_max,
            group_id=obj.group_id,
        )


    def to_python(self) -> QueryRadiusFilter:
        return QueryRadiusFilter(
            center_lat_nano=self.center_lat_nano,
            center_lon_nano=self.center_lon_nano,
            radius_mm=self.radius_mm,
            limit=self.limit,
            timestamp_min=self.timestamp_min,
            timestamp_max=self.timestamp_max,
            group_id=self.group_id,
        )

CQueryRadiusFilter._fields_ = [ # noqa: SLF001
    ("center_lat_nano", ctypes.c_int64),
    ("center_lon_nano", ctypes.c_int64),
    ("radius_mm", ctypes.c_uint32),
    ("limit", ctypes.c_uint32),
    ("timestamp_min", ctypes.c_uint64),
    ("timestamp_max", ctypes.c_uint64),
    ("group_id", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 80),
]


class CQueryPolygonFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="vertex_count", number=obj.vertex_count)
        validate_uint(bits=32, name="hole_count", number=obj.hole_count)
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=32, name="_reserved_align", number=obj._reserved_align)
        validate_uint(bits=64, name="timestamp_min", number=obj.timestamp_min)
        validate_uint(bits=64, name="timestamp_max", number=obj.timestamp_max)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        return cls(
            vertex_count=obj.vertex_count,
            hole_count=obj.hole_count,
            limit=obj.limit,
            _reserved_align=obj._reserved_align,
            timestamp_min=obj.timestamp_min,
            timestamp_max=obj.timestamp_max,
            group_id=obj.group_id,
        )


    def to_python(self) -> QueryPolygonFilter:
        return QueryPolygonFilter(
            vertex_count=self.vertex_count,
            hole_count=self.hole_count,
            limit=self.limit,
            _reserved_align=self._reserved_align,
            timestamp_min=self.timestamp_min,
            timestamp_max=self.timestamp_max,
            group_id=self.group_id,
        )

CQueryPolygonFilter._fields_ = [ # noqa: SLF001
    ("vertex_count", ctypes.c_uint32),
    ("hole_count", ctypes.c_uint32),
    ("limit", ctypes.c_uint32),
    ("_reserved_align", ctypes.c_uint32),
    ("timestamp_min", ctypes.c_uint64),
    ("timestamp_max", ctypes.c_uint64),
    ("group_id", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 88),
]


class CQueryLatestFilter(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="limit", number=obj.limit)
        validate_uint(bits=32, name="_reserved_align", number=obj._reserved_align)
        validate_uint(bits=64, name="group_id", number=obj.group_id)
        validate_uint(bits=64, name="cursor_timestamp", number=obj.cursor_timestamp)
        return cls(
            limit=obj.limit,
            _reserved_align=obj._reserved_align,
            group_id=obj.group_id,
            cursor_timestamp=obj.cursor_timestamp,
        )


    def to_python(self) -> QueryLatestFilter:
        return QueryLatestFilter(
            limit=self.limit,
            _reserved_align=self._reserved_align,
            group_id=self.group_id,
            cursor_timestamp=self.cursor_timestamp,
        )

CQueryLatestFilter._fields_ = [ # noqa: SLF001
    ("limit", ctypes.c_uint32),
    ("_reserved_align", ctypes.c_uint32),
    ("group_id", ctypes.c_uint64),
    ("cursor_timestamp", ctypes.c_uint64),
    ("reserved", ctypes.c_uint8 * 104),
]


class CQueryResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="count", number=obj.count)
        validate_uint(bits=8, name="has_more", number=obj.has_more)
        validate_uint(bits=8, name="partial_result", number=obj.partial_result)
        return cls(
            count=obj.count,
            has_more=obj.has_more,
            partial_result=obj.partial_result,
        )


    def to_python(self) -> QueryResponse:
        return QueryResponse(
            count=self.count,
            has_more=self.has_more,
            partial_result=self.partial_result,
        )

CQueryResponse._fields_ = [ # noqa: SLF001
    ("count", ctypes.c_uint32),
    ("has_more", ctypes.c_uint8),
    ("partial_result", ctypes.c_uint8),
    ("reserved", ctypes.c_uint8 * 10),
]


class CPolygonVertex(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_int(bits=64, name="lat_nano", number=obj.lat_nano)
        validate_int(bits=64, name="lon_nano", number=obj.lon_nano)
        return cls(
            lat_nano=obj.lat_nano,
            lon_nano=obj.lon_nano,
        )


    def to_python(self) -> PolygonVertex:
        return PolygonVertex(
            lat_nano=self.lat_nano,
            lon_nano=self.lon_nano,
        )

CPolygonVertex._fields_ = [ # noqa: SLF001
    ("lat_nano", ctypes.c_int64),
    ("lon_nano", ctypes.c_int64),
]


class CHoleDescriptor(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="vertex_count", number=obj.vertex_count)
        return cls(
            vertex_count=obj.vertex_count,
        )


    def to_python(self) -> HoleDescriptor:
        return HoleDescriptor(
            vertex_count=self.vertex_count,
        )

CHoleDescriptor._fields_ = [ # noqa: SLF001
    ("vertex_count", ctypes.c_uint32),
    ("reserved", ctypes.c_uint32),
]


class CPingRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=64, name="ping_data", number=obj.ping_data)
        return cls(
            ping_data=obj.ping_data,
        )


    def to_python(self) -> PingRequest:
        return PingRequest(
            ping_data=self.ping_data,
        )

CPingRequest._fields_ = [ # noqa: SLF001
    ("ping_data", ctypes.c_uint64),
]


class CStatusRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        return cls(
        )


    def to_python(self) -> StatusRequest:
        return StatusRequest(
        )

CStatusRequest._fields_ = [ # noqa: SLF001
    ("reserved", ctypes.c_uint64),
]


class CPingResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="pong", number=obj.pong)
        return cls(
            pong=obj.pong,
        )


    def to_python(self) -> PingResponse:
        return PingResponse(
            pong=self.pong,
        )

CPingResponse._fields_ = [ # noqa: SLF001
    ("pong", ctypes.c_uint32),
]


class CStatusResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=64, name="ram_index_count", number=obj.ram_index_count)
        validate_uint(bits=64, name="ram_index_capacity", number=obj.ram_index_capacity)
        validate_uint(bits=32, name="ram_index_load_pct", number=obj.ram_index_load_pct)
        validate_uint(bits=32, name="_padding", number=obj._padding)
        validate_uint(bits=64, name="tombstone_count", number=obj.tombstone_count)
        validate_uint(bits=64, name="ttl_expirations", number=obj.ttl_expirations)
        validate_uint(bits=64, name="deletion_count", number=obj.deletion_count)
        validate_uint(bits=8, name="index_resize_status", number=obj.index_resize_status)
        validate_uint(bits=8, name="membership_state", number=obj.membership_state)
        validate_uint(bits=16, name="_status_padding", number=obj._status_padding)
        validate_uint(bits=32, name="index_resize_progress", number=obj.index_resize_progress)
        validate_uint(bits=32, name="membership_voters_count", number=obj.membership_voters_count)
        validate_uint(bits=32, name="membership_learners_count", number=obj.membership_learners_count)
        return cls(
            ram_index_count=obj.ram_index_count,
            ram_index_capacity=obj.ram_index_capacity,
            ram_index_load_pct=obj.ram_index_load_pct,
            _padding=obj._padding,
            tombstone_count=obj.tombstone_count,
            ttl_expirations=obj.ttl_expirations,
            deletion_count=obj.deletion_count,
            index_resize_status=obj.index_resize_status,
            membership_state=obj.membership_state,
            _status_padding=obj._status_padding,
            index_resize_progress=obj.index_resize_progress,
            membership_voters_count=obj.membership_voters_count,
            membership_learners_count=obj.membership_learners_count,
        )


    def to_python(self) -> StatusResponse:
        return StatusResponse(
            ram_index_count=self.ram_index_count,
            ram_index_capacity=self.ram_index_capacity,
            ram_index_load_pct=self.ram_index_load_pct,
            _padding=self._padding,
            tombstone_count=self.tombstone_count,
            ttl_expirations=self.ttl_expirations,
            deletion_count=self.deletion_count,
            index_resize_status=self.index_resize_status,
            membership_state=self.membership_state,
            _status_padding=self._status_padding,
            index_resize_progress=self.index_resize_progress,
            membership_voters_count=self.membership_voters_count,
            membership_learners_count=self.membership_learners_count,
        )

CStatusResponse._fields_ = [ # noqa: SLF001
    ("ram_index_count", ctypes.c_uint64),
    ("ram_index_capacity", ctypes.c_uint64),
    ("ram_index_load_pct", ctypes.c_uint32),
    ("_padding", ctypes.c_uint32),
    ("tombstone_count", ctypes.c_uint64),
    ("ttl_expirations", ctypes.c_uint64),
    ("deletion_count", ctypes.c_uint64),
    ("index_resize_status", ctypes.c_uint8),
    ("membership_state", ctypes.c_uint8),
    ("_status_padding", ctypes.c_uint16),
    ("index_resize_progress", ctypes.c_uint32),
    ("membership_voters_count", ctypes.c_uint32),
    ("membership_learners_count", ctypes.c_uint32),
]


class CTopologyRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        return cls(
        )


    def to_python(self) -> TopologyRequest:
        return TopologyRequest(
        )

CTopologyRequest._fields_ = [ # noqa: SLF001
    ("reserved", ctypes.c_uint64),
]


class CShardInfo(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=32, name="id", number=obj.id)
        validate_uint(bits=8, name="replica_count", number=obj.replica_count)
        validate_uint(bits=64, name="entity_count", number=obj.entity_count)
        validate_uint(bits=64, name="size_bytes", number=obj.size_bytes)
        return cls(
            id=obj.id,
            primary=obj.primary,
            replicas=obj.replicas,
            replica_count=obj.replica_count,
            status=obj.status,
            entity_count=obj.entity_count,
            size_bytes=obj.size_bytes,
        )


    def to_python(self) -> ShardInfo:
        return ShardInfo(
            id=self.id,
            primary=self.primary,
            replicas=self.replicas,
            replica_count=self.replica_count,
            status=ShardStatus(self.status),
            entity_count=self.entity_count,
            size_bytes=self.size_bytes,
        )

CShardInfo._fields_ = [ # noqa: SLF001
    ("id", ctypes.c_uint32),
    ("primary", ctypes.c_uint8 * 64),
    ("replicas", ctypes.c_uint8 * 64 * 6),
    ("replica_count", ctypes.c_uint8),
    ("status", ctypes.c_uint8),
    ("entity_count", ctypes.c_uint64),
    ("size_bytes", ctypes.c_uint64),
]


class CTopologyResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=64, name="version", number=obj.version)
        validate_uint(bits=32, name="num_shards", number=obj.num_shards)
        validate_uint(bits=128, name="cluster_id", number=obj.cluster_id)
        validate_int(bits=128, name="last_change_ns", number=obj.last_change_ns)
        validate_uint(bits=8, name="resharding_status", number=obj.resharding_status)
        validate_uint(bits=8, name="flags", number=obj.flags)
        return cls(
            version=obj.version,
            num_shards=obj.num_shards,
            cluster_id=c_uint128.from_param(obj.cluster_id),
            last_change_ns=c_int128.from_param(obj.last_change_ns),
            resharding_status=obj.resharding_status,
            flags=obj.flags,
            _padding=obj._padding,
            shards=obj.shards,
        )


    def to_python(self) -> TopologyResponse:
        return TopologyResponse(
            version=self.version,
            num_shards=self.num_shards,
            cluster_id=self.cluster_id.to_python(),
            last_change_ns=self.last_change_ns.to_python(),
            resharding_status=self.resharding_status,
            flags=self.flags,
            _padding=self._padding,
            shards=self.shards,
        )

CTopologyResponse._fields_ = [ # noqa: SLF001
    ("version", ctypes.c_uint64),
    ("num_shards", ctypes.c_uint32),
    ("cluster_id", c_uint128),
    ("last_change_ns", c_int128),
    ("resharding_status", ctypes.c_uint8),
    ("flags", ctypes.c_uint8),
    ("_padding", ctypes.c_uint8 * 6),
    ("shards", CShardInfo * 256),
]


class CTtlSetRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="ttl_seconds", number=obj.ttl_seconds)
        validate_uint(bits=32, name="flags", number=obj.flags)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            ttl_seconds=obj.ttl_seconds,
            flags=obj.flags,
        )


    def to_python(self) -> TtlSetRequest:
        return TtlSetRequest(
            entity_id=self.entity_id.to_python(),
            ttl_seconds=self.ttl_seconds,
            flags=self.flags,
        )

CTtlSetRequest._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("ttl_seconds", ctypes.c_uint32),
    ("flags", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 40),
]


class CTtlSetResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="previous_ttl_seconds", number=obj.previous_ttl_seconds)
        validate_uint(bits=32, name="new_ttl_seconds", number=obj.new_ttl_seconds)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            previous_ttl_seconds=obj.previous_ttl_seconds,
            new_ttl_seconds=obj.new_ttl_seconds,
            result=obj.result,
            _padding=obj._padding,
        )


    def to_python(self) -> TtlSetResponse:
        return TtlSetResponse(
            entity_id=self.entity_id.to_python(),
            previous_ttl_seconds=self.previous_ttl_seconds,
            new_ttl_seconds=self.new_ttl_seconds,
            result=TtlOperationResult(self.result),
            _padding=self._padding,
        )

CTtlSetResponse._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("previous_ttl_seconds", ctypes.c_uint32),
    ("new_ttl_seconds", ctypes.c_uint32),
    ("result", ctypes.c_uint8),
    ("_padding", ctypes.c_uint8 * 3),
    ("reserved", ctypes.c_uint8 * 32),
]


class CTtlExtendRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="extend_by_seconds", number=obj.extend_by_seconds)
        validate_uint(bits=32, name="flags", number=obj.flags)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            extend_by_seconds=obj.extend_by_seconds,
            flags=obj.flags,
        )


    def to_python(self) -> TtlExtendRequest:
        return TtlExtendRequest(
            entity_id=self.entity_id.to_python(),
            extend_by_seconds=self.extend_by_seconds,
            flags=self.flags,
        )

CTtlExtendRequest._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("extend_by_seconds", ctypes.c_uint32),
    ("flags", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 40),
]


class CTtlExtendResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="previous_ttl_seconds", number=obj.previous_ttl_seconds)
        validate_uint(bits=32, name="new_ttl_seconds", number=obj.new_ttl_seconds)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            previous_ttl_seconds=obj.previous_ttl_seconds,
            new_ttl_seconds=obj.new_ttl_seconds,
            result=obj.result,
            _padding=obj._padding,
        )


    def to_python(self) -> TtlExtendResponse:
        return TtlExtendResponse(
            entity_id=self.entity_id.to_python(),
            previous_ttl_seconds=self.previous_ttl_seconds,
            new_ttl_seconds=self.new_ttl_seconds,
            result=TtlOperationResult(self.result),
            _padding=self._padding,
        )

CTtlExtendResponse._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("previous_ttl_seconds", ctypes.c_uint32),
    ("new_ttl_seconds", ctypes.c_uint32),
    ("result", ctypes.c_uint8),
    ("_padding", ctypes.c_uint8 * 3),
    ("reserved", ctypes.c_uint8 * 32),
]


class CTtlClearRequest(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="flags", number=obj.flags)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            flags=obj.flags,
        )


    def to_python(self) -> TtlClearRequest:
        return TtlClearRequest(
            entity_id=self.entity_id.to_python(),
            flags=self.flags,
        )

CTtlClearRequest._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("flags", ctypes.c_uint32),
    ("reserved", ctypes.c_uint8 * 44),
]


class CTtlClearResponse(ctypes.Structure):
    @classmethod
    def from_param(cls, obj: Any) -> Self:
        validate_uint(bits=128, name="entity_id", number=obj.entity_id)
        validate_uint(bits=32, name="previous_ttl_seconds", number=obj.previous_ttl_seconds)
        return cls(
            entity_id=c_uint128.from_param(obj.entity_id),
            previous_ttl_seconds=obj.previous_ttl_seconds,
            result=obj.result,
            _padding=obj._padding,
        )


    def to_python(self) -> TtlClearResponse:
        return TtlClearResponse(
            entity_id=self.entity_id.to_python(),
            previous_ttl_seconds=self.previous_ttl_seconds,
            result=TtlOperationResult(self.result),
            _padding=self._padding,
        )

CTtlClearResponse._fields_ = [ # noqa: SLF001
    ("entity_id", c_uint128),
    ("previous_ttl_seconds", ctypes.c_uint32),
    ("result", ctypes.c_uint8),
    ("_padding", ctypes.c_uint8 * 3),
    ("reserved", ctypes.c_uint8 * 36),
]


# Don't be tempted to use c_char_p for bytes_ptr - it's for null terminated strings only.
OnCompletion = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.POINTER(CPacket),
                                ctypes.c_uint64, ctypes.c_void_p, ctypes.c_uint32)
LogHandler = ctypes.CFUNCTYPE(None, ctypes.c_uint, ctypes.c_void_p, ctypes.c_uint)

class InitParameters(ctypes.Structure):
    _fields_ = [("cluster_id", c_uint128), ("client_id", c_uint128),
                ("addresses_ptr", ctypes.c_void_p), ("addresses_len", ctypes.c_uint64)]

# Initialize a new ArcherDB client which connects to the addresses provided and
# completes submitted packets by invoking the callback with the given context.
arch_client_init = archclient.arch_client_init
arch_client_init.restype = InitStatus
arch_client_init.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(ctypes.c_uint8 * 16),
                           ctypes.c_char_p, ctypes.c_uint32, ctypes.c_void_p,
                           OnCompletion]

# Initialize a new ArcherDB client which echos back any data submitted.
arch_client_init_echo = archclient.arch_client_init_echo
arch_client_init_echo.restype = InitStatus
arch_client_init_echo.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(ctypes.c_uint8 * 16),
                                ctypes.c_char_p, ctypes.c_uint32, ctypes.c_void_p,
                                OnCompletion]

# Returns the cluster_id and addresses passed in to either arch_client_init or
# arch_client_init_echo.
arch_client_init_parameters = archclient.arch_client_init_parameters
arch_client_init_parameters.restype = ClientStatus
arch_client_init_parameters.argtypes = [ctypes.POINTER(CClient),
                                      ctypes.POINTER(InitParameters)]

# Closes the client, causing any previously submitted packets to be completed with
# `ARCH_PACKET_CLIENT_SHUTDOWN` before freeing any allocated client resources from init.
# It is undefined behavior to use any functions on the client once deinit is called.
arch_client_deinit = archclient.arch_client_deinit
arch_client_deinit.restype = ClientStatus
arch_client_deinit.argtypes = [ctypes.POINTER(CClient)]

# Submit a packet with its operation, data, and data_size fields set.
# Once completed, `on_completion` will be invoked with `on_completion_ctx` and the given
# packet on the `arch_client` thread (separate from caller's thread).
arch_client_submit = archclient.arch_client_submit
arch_client_submit.restype = ClientStatus
arch_client_submit.argtypes = [ctypes.POINTER(CClient), ctypes.POINTER(CPacket)]

arch_client_register_log_callback = archclient.arch_client_register_log_callback
arch_client_register_log_callback.restype = RegisterLogCallbackStatus
# Need to pass in None to clear - ctypes will error if argtypes is set.
# arch_client_register_log_callback.argtypes = [LogHandler, ctypes.c_bool]


class AsyncStateMachineMixin:
    _submit: Callable[[Operation, Any, Any, Any], Any]
    async def insert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.INSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    async def upsert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.UPSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    async def delete_entities(self, entity_ids: list[int]) -> list[DeleteEntitiesResult]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.DELETE_ENTITIES,
            entity_ids,
            c_uint128,
            CDeleteEntitiesResult,
        )

    async def query_uuid(self, filter: QueryUuidFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_UUID,
            [filter],
            CQueryUuidFilter,
            CGeoEvent,
        )

    async def query_radius(self, filter: QueryRadiusFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_RADIUS,
            [filter],
            CQueryRadiusFilter,
            CGeoEvent,
        )

    async def query_polygon(self, filter: QueryPolygonFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_POLYGON,
            [filter],
            CQueryPolygonFilter,
            CGeoEvent,
        )

    async def query_latest(self, filter: QueryLatestFilter) -> list[GeoEvent]:
        return await self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_LATEST,
            [filter],
            CQueryLatestFilter,
            CGeoEvent,
        )



class StateMachineMixin:
    _submit: Callable[[Operation, Any, Any, Any], Any]
    def insert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.INSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    def upsert_events(self, events: list[GeoEvent]) -> list[InsertGeoEventsResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.UPSERT_EVENTS,
            events,
            CGeoEvent,
            CInsertGeoEventsResult,
        )

    def delete_entities(self, entity_ids: list[int]) -> list[DeleteEntitiesResult]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.DELETE_ENTITIES,
            entity_ids,
            c_uint128,
            CDeleteEntitiesResult,
        )

    def query_uuid(self, filter: QueryUuidFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_UUID,
            [filter],
            CQueryUuidFilter,
            CGeoEvent,
        )

    def query_radius(self, filter: QueryRadiusFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_RADIUS,
            [filter],
            CQueryRadiusFilter,
            CGeoEvent,
        )

    def query_polygon(self, filter: QueryPolygonFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_POLYGON,
            [filter],
            CQueryPolygonFilter,
            CGeoEvent,
        )

    def query_latest(self, filter: QueryLatestFilter) -> list[GeoEvent]:
        return self._submit(  # type: ignore[no-any-return]
            Operation.QUERY_LATEST,
            [filter],
            CQueryLatestFilter,
            CGeoEvent,
        )



