///////////////////////////////////////////////////////
// This file was auto-generated by node_bindings.zig //
//              Do not manually modify.              //
///////////////////////////////////////////////////////

export type GeoEvent = {
  id: bigint
  entity_id: bigint
  correlation_id: bigint
  user_data: bigint
  lat_nano: bigint
  lon_nano: bigint
  group_id: bigint
  timestamp: bigint
  altitude_mm: number
  velocity_mms: number
  ttl_seconds: number
  accuracy_mm: number
  heading_cdeg: number
  flags: number
}

export enum GeoEventFlags {
  none = 0,
  linked = (1 << 0),
  imported = (1 << 1),
  stationary = (1 << 2),
  low_accuracy = (1 << 3),
  offline = (1 << 4),
  deleted = (1 << 5),
}

export enum InsertGeoEventError {
  ok = 0,
  linked_event_failed = 1,
  linked_event_chain_open = 2,
  timestamp_must_be_zero = 3,
  reserved_field = 4,
  reserved_flag = 5,
  id_must_not_be_zero = 6,
  entity_id_must_not_be_zero = 7,
  invalid_coordinates = 8,
  lat_out_of_range = 9,
  lon_out_of_range = 10,
  exists_with_different_entity_id = 11,
  exists_with_different_coordinates = 12,
  exists = 13,
  heading_out_of_range = 14,
  ttl_invalid = 15,
}

export type InsertGeoEventsError = {
  index: number
  result: InsertGeoEventError
}

export enum DeleteEntityError {
  ok = 0,
  linked_event_failed = 1,
  entity_id_must_not_be_zero = 2,
  entity_not_found = 3,
}

export type DeleteEntitiesError = {
  index: number
  result: DeleteEntityError
}

export type QueryUuidFilter = {
  entity_id: bigint
  limit: number
}

export type QueryRadiusFilter = {
  center_lat_nano: bigint
  center_lon_nano: bigint
  radius_mm: number
  limit: number
  timestamp_min: bigint
  timestamp_max: bigint
  group_id: bigint
}

export type QueryPolygonFilter = {
  vertex_count: number
  limit: number
  timestamp_min: bigint
  timestamp_max: bigint
  group_id: bigint
}

export type QueryLatestFilter = {
  limit: number
  group_id: bigint
  cursor_timestamp: bigint
}

export type QueryResponse = {
  count: number
  has_more: number
  partial_result: number
}

export type PolygonVertex = {
  lat_nano: bigint
  lon_nano: bigint
}

export enum Operation {
  pulse = 128,
  get_change_events = 137,
  create_accounts = 138,
  create_transfers = 139,
  lookup_accounts = 140,
  lookup_transfers = 141,
  get_account_transfers = 142,
  get_account_balances = 143,
  query_accounts = 144,
  query_transfers = 145,
  insert_events = 146,
  upsert_events = 147,
  delete_entities = 148,
  query_uuid = 149,
  query_radius = 150,
  query_polygon = 151,
  query_latest = 154,
  archerdb_ping = 152,
  archerdb_get_status = 153,
  cleanup_expired = 155,
}

