///////////////////////////////////////////////////////
// This file was auto-generated by node_bindings.zig //
//              Do not manually modify.              //
///////////////////////////////////////////////////////

export type GeoEvent = {
  id: bigint
  entity_id: bigint
  correlation_id: bigint
  user_data: bigint
  lat_nano: bigint
  lon_nano: bigint
  group_id: bigint
  timestamp: bigint
  altitude_mm: number
  velocity_mms: number
  ttl_seconds: number
  accuracy_mm: number
  heading_cdeg: number
  flags: number
}

export enum GeoEventFlags {
  none = 0,
  linked = (1 << 0),
  imported = (1 << 1),
  stationary = (1 << 2),
  low_accuracy = (1 << 3),
  offline = (1 << 4),
  deleted = (1 << 5),
}

export enum InsertGeoEventError {
  ok = 0,
  linked_event_failed = 1,
  linked_event_chain_open = 2,
  timestamp_must_be_zero = 3,
  reserved_field = 4,
  reserved_flag = 5,
  id_must_not_be_zero = 6,
  entity_id_must_not_be_zero = 7,
  invalid_coordinates = 8,
  lat_out_of_range = 9,
  lon_out_of_range = 10,
  exists_with_different_entity_id = 11,
  exists_with_different_coordinates = 12,
  exists = 13,
  heading_out_of_range = 14,
  ttl_invalid = 15,
  entity_id_must_not_be_int_max = 16,
}

export type InsertGeoEventsError = {
  index: number
  result: InsertGeoEventError
}

export enum DeleteEntityError {
  ok = 0,
  linked_event_failed = 1,
  entity_id_must_not_be_zero = 2,
  entity_not_found = 3,
  entity_id_must_not_be_int_max = 4,
}

export type DeleteEntitiesError = {
  index: number
  result: DeleteEntityError
}

export type QueryUuidFilter = {
  entity_id: bigint
}

export type QueryUuidResponse = {
  status: number
}

export type QueryUuidBatchFilter = {
  count: number
}

export type QueryUuidBatchResult = {
  found_count: number
  not_found_count: number
}

export type QueryRadiusFilter = {
  center_lat_nano: bigint
  center_lon_nano: bigint
  radius_mm: number
  limit: number
  timestamp_min: bigint
  timestamp_max: bigint
  group_id: bigint
}

export type QueryPolygonFilter = {
  vertex_count: number
  hole_count: number
  limit: number
  timestamp_min: bigint
  timestamp_max: bigint
  group_id: bigint
}

export type QueryLatestFilter = {
  limit: number
  group_id: bigint
  cursor_timestamp: bigint
}

export type QueryResponse = {
  count: number
  has_more: number
  partial_result: number
}

export type PolygonVertex = {
  lat_nano: bigint
  lon_nano: bigint
}

export type HoleDescriptor = {
  vertex_count: number
}

export enum TtlOperationResult {
  success = 0,
  entity_not_found = 1,
  invalid_ttl = 2,
  not_permitted = 3,
  entity_immutable = 4,
}

export type TtlSetRequest = {
  entity_id: bigint
  ttl_seconds: number
  flags: number
}

export type TtlSetResponse = {
  entity_id: bigint
  previous_ttl_seconds: number
  new_ttl_seconds: number
  result: TtlOperationResult
}

export type TtlExtendRequest = {
  entity_id: bigint
  extend_by_seconds: number
  flags: number
}

export type TtlExtendResponse = {
  entity_id: bigint
  previous_ttl_seconds: number
  new_ttl_seconds: number
  result: TtlOperationResult
}

export type TtlClearRequest = {
  entity_id: bigint
  flags: number
}

export type TtlClearResponse = {
  entity_id: bigint
  previous_ttl_seconds: number
  result: TtlOperationResult
}

export type PingRequest = {
  ping_data: bigint
}

export type StatusRequest = {
  reserved: bigint
}

export type PingResponse = {
  pong: number
}

export type StatusResponse = {
  ram_index_count: bigint
  ram_index_capacity: bigint
  ram_index_load_pct: number
  tombstone_count: bigint
  ttl_expirations: bigint
  deletion_count: bigint
}

export type TopologyRequest = {
}

export type TopologyResponse = {
  version: bigint
  num_shards: number
  cluster_id: bigint
  last_change_ns: bigint
  resharding_status: number
  flags: number
  shards: Buffer
}

export type ShardInfo = {
  id: number
  primary: Buffer
  replicas: Buffer
  replica_count: number
  status: ShardStatus
  entity_count: bigint
  size_bytes: bigint
}

export enum ShardStatus {
  active = 0,
  syncing = 1,
  unavailable = 2,
  migrating = 3,
  decommissioning = 4,
}

export enum Operation {
  pulse = 128,
  insert_events = 146,
  upsert_events = 147,
  delete_entities = 148,
  query_uuid = 149,
  query_radius = 150,
  query_polygon = 151,
  query_latest = 154,
  query_uuid_batch = 156,
  archerdb_ping = 152,
  archerdb_get_status = 153,
  cleanup_expired = 155,
  get_topology = 157,
  ttl_set = 158,
  ttl_extend = 159,
  ttl_clear = 160,
  batch_query = 161,
  prepare_query = 162,
  execute_prepared = 163,
  deallocate_prepared = 164,
}

